ng-bootstrap/ng-bootstrap

- src/pagination/pagination.ts
https://github.com/angular/angular/issues/8242 was fixed so we can go back to using `ChangeDetectionStrategy.OnPush`
> refactor(pagination): bring back ChangeDetectionStrategy.OnPush

- DEVELOPER.md
- gulpfile.js
- package.json
- tsconfig.json
- typings.json
Changes:
New typings with its breaking changes.
I removed the postinstall. A library **shouldn't** have it because that will force all consumers to have typings installed globally and that is a no-no, so from now one, manual install for us (this doesn't involve anything for the end user).
Please delete your typings folder and install them again.
> chore: update to typings 1.x

- src/rating/rating.spec.ts
- src/rating/rating.ts
The cursor used on the stars of the rating component is a text selection cursor, which doesn't make it clear that they're clickable. The cursor stays the same if the rating component is readonly.
This commit sets a 'pointer' cursor on the stars, and a 'not-allowed' cursor when it's read-only.
> feat(rating): set cursor on stars of rating component

- gulpfile.js
Since this is a generated file, we just exclude it. We shouldn't worry to lint something that is generated with a tool that is not under our control.
Fixes #504
> chore: remove api-docs.ts from linting

- gulpfile.js
I used the same technique (more or less) than Angular so it should be good.
If we start adding more operators, I will simplify the setup a bit with a `rxjsExternal` or similar.
Fixes #548
> chore: remove forms, http and rxjs from UMD bundle

- demo/src/app/components/datepicker/demos/basic/datepicker-basic.html
- demo/src/app/components/datepicker/demos/basic/datepicker-basic.ts
- demo/src/app/components/datepicker/demos/config/datepicker-config.ts
- demo/src/app/components/datepicker/demos/customday/datepicker-customday.ts
- demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.ts
- src/datepicker/datepicker-i18n.spec.ts
- src/datepicker/datepicker-i18n.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-navigation-select.spec.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
- src/datepicker/ngb-calendar.spec.ts
- src/datepicker/ngb-calendar.ts
- src/datepicker/ngb-date-parser-formatter.spec.ts
- src/datepicker/ngb-date-parser-formatter.ts
- src/datepicker/ngb-date-struct.ts
Fixes #728
BREAKING CHANGE: now datepicker uses ISO 8601 for month and weekday numbers with default calendar
Before
0=Jan; 1=Feb; ... 11=Dec
0=Sun; 1=Mon; ... 6=Sat
Now
1=Jan; 2=Feb; ... 12=Dec
1=Mon; 2=Tue; ... 7=Sun
> refactor(datepicker): use ISO 8601 for month and weekday numbers

- demo/src/app/components/rating/demos/events/events.component.html
- demo/src/app/components/rating/demos/events/events.component.ts
- demo/src/app/components/rating/demos/events/index.ts
- demo/src/app/components/rating/demos/index.ts
- demo/src/app/components/rating/rating.component.html
Just a small demo to show the rating `[readonly]` feature and `(hover)` / `(leave)` events
> demo(rating): shows enter/leave usage and readonly ratings

- demo/src/app/components/rating/demos/index.ts
- demo/src/app/components/rating/demos/template/index.ts
- demo/src/app/components/rating/demos/template/template.component.html
- demo/src/app/components/rating/demos/template/template.component.ts
- demo/src/app/components/rating/rating.component.html
- src/rating/rating.spec.ts
- src/rating/rating.ts
Part of #801 
Adds a template to allow custom rating display
Default rendering still uses &#9733; and &#9734; symbols
```html
<template #t let-fill="fill">
</template>
<ngb-rating [(rate)]="currentRate" [starTemplate]="t"></ngb-rating>
```
> feat(rating): allow custom star templates

- demo/src/app/components/rating/demos/decimal/decimal.component.html
- demo/src/app/components/rating/demos/decimal/decimal.component.ts
- demo/src/app/components/rating/demos/decimal/index.ts
- demo/src/app/components/rating/demos/index.ts
- demo/src/app/components/rating/rating.component.html
- src/rating/rating.spec.ts
- src/rating/rating.ts
Part of #801 
Allows for fine-grained rating values like `3.72`. 
Properly handles decimal numbers and template `fill` value when updated via `[rate]` binding. 
Plus a small readonly demo.
> feat(rating): allow decimal numbers as rating values

- demo/src/app/components/datepicker/demos/customday/datepicker-customday.html
- demo/src/app/components/datepicker/demos/customday/datepicker-customday.ts
- src/datepicker/datepicker-config.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Small datepicker enhancement: now able to access current month value both in custom template and `markDisabled` callback.
That allows for instance to disable completely days that are outside of current month and collapse them (see 'custom day view' demo):
```typescript
[markDisabled]='markDisabled'
...
markDisabled = (date, current: {month: number}) {
return date.month != current.month;
};
...
<template let-date='date' let-currentMonth='currentMonth'>
<span [class.hide_day]='date.month !== currentMonth' ...>
</template>
...
.hide_day {
display: none; // or visibility: hidden; to avoid line collapse
}
```
Contains an example for #847 and #753
> feat(datepicker): pass current month value to 'markDisabled' callback

- demo/src/app/components/alert/demos/selfclosing/alert-selfclosing.ts
- demo/src/app/components/typeahead/demos/basic/typeahead-basic.ts
- demo/src/app/components/typeahead/demos/config/typeahead-config.ts
- demo/src/app/components/typeahead/demos/format/typeahead-format.ts
- demo/src/app/components/typeahead/demos/http/typeahead-http.ts
- demo/src/app/components/typeahead/demos/template/typeahead-template.ts
- demo/src/vendor.ts
- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
Changing rxjs imports as in this PR reduces our bundle size
from ~190k -> ~45k (before minification / gzip). Non-scientific
testing on my machine shows that the site load time drops by
around 300 - 400ms.
> chore: don't import from catch-all rxjs/Rx

- src/typeahead/typeahead.ts
> docs(typeahead): clarify 'this' binding of the 'ngbTypeahead' function

- src/test/common.ts
- src/test/matchers.ts
on common.ts, that return browser is never reached, that hurts the coverage.
On matchers, the message is a bit overcomplex and fails the coverage as well, now it pass coverage and works as expected as well.
> chore: adjust some test helpers

- package.json
- src/rating/rating.spec.ts
`typescript: ^2.0.6` installs the latest `2.1.4` version that breaks the build. 
So to unblock for now:
- freezing to latest `2.0.10` (angular doesn't work with `2.1` yet, and our ngc build fails)
- future-proofing: removing the useless check that breaks `2.1` in tests
> chore: freeze typescript version

- demo/src/app/components/rating/demos/form/rating-form.html
- demo/src/app/components/rating/demos/form/rating-form.ts
- demo/src/app/components/rating/demos/index.ts
- demo/src/app/components/rating/rating.component.html
- src/rating/rating.spec.ts
- src/rating/rating.ts
Enables form integration for rating:
- both template driven and reactive forms tests
- `rate` event emitter becomes asynchronous (same story as pagination)
- ability to use both `[(rate)]` and `[(ngModel)]`
- form integration demo with reactive
Fixes #1087
> feat(rating): enable form integration

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
- src/datepicker/ngb-calendar.spec.ts
- src/datepicker/ngb-calendar.ts
This will protect against invalid inputs for `minDate`, `maxDate` and `startDate` as well as `navigateTo(date)` and set them to default values
Fixes #1062
> fix(datepicker): protect against invalid min, max and start dates

- gulpfile.js
- karma.conf.js
- updating evergreen browsers to `latest` version
- adding `edge 14` and `safari 10`
- always using the latest selenium version
> chore: bump browser versions for sauce labs

- demo/src/app/components/shared/api-docs/api-docs-class.component.html
Fixes a typo introduced in e146a7a9f8c041b1ce6510ef4c41aa7becda2a10
cc @jnizet
> fix(demo): fix cell sizing of class documentation

- src/datepicker/datepicker-day-view.spec.ts
- src/datepicker/datepicker-day-view.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-month-view.spec.ts
- src/datepicker/datepicker-month-view.ts
- src/datepicker/datepicker-navigation.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Updating default datepicker look and feel as a part of #862 :
* Moving to flex layout instead of table layout
* More space and border around the datepicker
* Less pronounced weekdays
* Visual separation of the header from the body
* Buttons same as in the timepicker
* Prefixing css classes with `ngb-dp-`
Before:
After:
P.S. Will also add full month names with a separate request later
BREAKING CHANGES: switched to flex layout instead of table-based (drop IE9 support) and prefixed datepicker-related css classes with `ngb-dp-`
Fixes #706
> feat(datepicker): improve default look and feel

- demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.ts
- src/datepicker/datepicker-i18n.spec.ts
- src/datepicker/datepicker-i18n.ts
- src/datepicker/datepicker-month-view.ts
- src/datepicker/datepicker-navigation-select.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Adding full month names to the datepicker:
- full names are displayed above the grid with days
- short names are displayed in selectboxes
- renamed i18n methods for consistency
Short:
Full:
BREAKING CHANGES: `NgbDatepickerI18n` methods renamed
`getWeekdayName` to `getWeekdayShortName`
`getMonthName` to `getMonthShortName`
> feat(datepicker): add full month name versions to i18n

- src/datepicker/datepicker.ts
When `navigation == "arrows"` on the datepicker component, navigation arrows are under the `div.ngb-dp-month` element, which prevents the click event from reaching navigation arrows on Firefox.
As this is a CSS styling issue and there is not any end-to-end protractor tests configured yet, I have not included any test in this PR. The issue is reproducible on the [demo site](https://ng-bootstrap.github.io/#/components/datepicker), go to the "Multiple months" example, and choose "Without select boxes" in the select. Then click on the arrows to navigate in the date picker, and nothing happens in Firefox.
> fix(datepicker): navigation arrows not responding on Firefox when navigation == "arrows"

- README.md
- demo/src/app/app.component.html
- demo/src/app/getting-started/getting-started.component.html
- package.json
Haven't found any breaking changes between `beta.1` and `beta.2` that affect us. Locally all components seem to be ok.
> chore: use bootstrap 4.0.0-beta.2

- gulpfile.js
- karma.conf.js
Use two latest versions of Edge and Safari:
- Edge → 14 and 15, drop 13
- Safari → 11 and 10, drop 9
> chore: add Edge 15 and Safari 11 to SauceLabs

- src/datepicker/datepicker-navigation.ts
- src/timepicker/timepicker.ts
Following #1947 I add the class `btn` next to `btn-link` in the timepicker.
I also found that it need to be changed in the datepicker. There was already the issue #1851 with a fix with some css to hide the border but it is not needed if we add the class `btn`.
I also remove the other css of the `btn-link` because I think we should follow the bootstrap implementation (button without a link should not have a custom cursor and outline is for accessibility).
> fix timepicker and datepicker btn-link

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker-view-model.ts
- src/datepicker/datepicker.ts
As a part of moving the rest of the state from components to the `NgbDatepickerService`.
This is a prerequisite for fixing min/max dates handling
> refactor(datepicker): move 'navigation' type handling to service

- demo/src/app/components/datepicker/demos/calendars/islamic-calendars.html
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker-tools.spec.ts
- src/datepicker/datepicker-tools.ts
The regression: Impossible to select date using `ngModel` if the dates are not currently visible: ex. simple datepicker demo → 'Select Today' button sets `ngModel` to `null`
Introduced in #1888
Cause: `isDateSelectable(date)` method used to check if we should emit date selection event
Fix: rewrite `isDateSelectable(date)` to take into account `minDate`, `maxDate`, `disabled` and `markDisabled`, not only currently visible months
> fix(datepicker): date selection regression for non-visible dates

- src/accordion/accordion.spec.ts
- src/accordion/accordion.ts
Add `.collapse` class to panel. When `destoyOnHide` is set to `false`, the panel remains visible due to a missing bootstrap class
Fix issue: 1915
> fix(accordion): fix-bug-1915

- src/datepicker/datepicker-navigation.spec.ts
- src/datepicker/datepicker-navigation.ts
Close #2093
When min-date was set to January of a year, the back arrow was not disabled because the old algorithm checked that the previous month (December = 12) was inferior to the min-date month (January = 1).
Now when the year between the previous month and the min-date month are different and when the min-date month is January, the back arrow is also disabled.
Also I add some test when the year change.
> fix(datepicker): disable back arrow

- package.json
Just to unblock current situation, need to move to yarn or lock packages
`enforce-format` failing with `gulp-check-format` starting from `1.0.24`
> fix(build): freeze gulp-clang-format package

- src/typeahead/typeahead-window.ts
> refactor(typeahead): use CSS classes instead of inline styles

- src/tooltip/tooltip-config.spec.ts
- src/tooltip/tooltip-config.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
Introduce disable flag for `Tooltip` to be consistent with `Popover`
Example:
`<div [ngbTooltip]="Disabled!" [disableTooltip]="true"></div>`
`<div [ngbPopover]="Disabled!" [disablePopover]="true"></div>`
> feat(tooltip): intoduce disabled flag

- src/accordion/accordion.spec.ts
- src/accordion/accordion.ts
Fixes #2221
BREAKING CHANGE:
The "active" CSS class is no longer added to headers of an active panel.
This change assures that markup used by ng-bootstrap is in-line with the
markup described in:
https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example
> fix(accordion): remove active class from open panel titles

- package.json
- yarn.lock
This is in preparation for cutting an 2.0.0-rc.0
> chore: bump up Angular dependency to 6.0.0-rc.4

- src/util/focus-trap.spec.ts
- src/util/focus-trap.ts
PR introduces an internal service to setup a _focus-trap_ feature to be added to any element dynamically created by a widget.
Usage context: any datepicker popup, popover, modals...
Usage example:
+ provide the service in the widget module `providers: [NgbFocusTrapFactory]`
+ inject it in the widget constructor: `private _focusTrapFactory: NgbFocusTrapFactory`
+ call the create method specifying an element, it returns the newly created `NgbFocusTrap` instance
```typescript
this._focusTrap = this._focusTrapFactory.create(this.elementRef.nativeElement)
```
+ later on, when the dynamically created element is not needed, properly destroy the focustrap to release event listeners set on document: `this._focusTrap.destory()`
---
You can also decorate a node contained inside element with …
> feat: focustrap standalone service

- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker.module.ts
Straight forward implementation of focustrap for any datepicker opened in a popup via `NgbDatepickerInput`
This PR does not have any tests, as writing UT for that would end up in duplicating NgbFocusTrap UT.
Nonetheless, as soon as Protractor is setup on the project, we then can write a whole bunch of new dedicated tests.
> feat(datepicker): focustrap for popup datepickers

- karma.conf.js
Sauce Labs is failing because of Safari.
Version 11.0 is not available anymore on sauce labs for some reason after the latest mac os update.
Making versions less restrictive
> chore: make safari versions less restrictive for sauce labs

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker.module.ts
- src/util/focus-trap.spec.ts
- src/util/focus-trap.ts
Refactor existing implementation of the focus trap: handle only inside clicks and tab navigation. It doesn't steal outside focus anymore
Fixes #2406
Fixes #2390
Fixes #2372 (one more time)
> fix(datepicker): simplify focus trap with observables

- demo/src/app/components/datepicker/demos/multiple/datepicker-multiple.html
- demo/src/app/components/datepicker/demos/multiple/datepicker-multiple.ts
- src/datepicker/datepicker-month-view.spec.ts
- src/datepicker/datepicker-month-view.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker-tools.ts
- src/datepicker/datepicker-view-model.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
The last in series of moving logic from components to the service and utility functions
> refactor(datepicker): move 'outsideDays' generation to the service

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
The list of months and years was generated from the focused date rather than the first displayed date, which was inconsistent with the value used in the datepicker navigation component, which uses the first displayed date.
This inconsistency was not visible when displayMonths = 1 but it sometimes caused the following issue when several months were displayed: the month select box was empty as it did not contain the currently displayed month.
Closes #2377
> fix(datepicker): empty month select box when displayMonths > 1

- demo/src/style/app.scss
With the new demo layout, Carousel demo looks a bit broken on very large displays as images which are fetch have an hardcoded width of 900px
PR makes them fit the all space
> fix(demo): carousel displays images in full width on large screens

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-tools.spec.ts
- src/datepicker/datepicker-tools.ts
- src/datepicker/datepicker.spec.ts
Reuses data structures in the datepicker data model instead of building new objects each time the user navigates to a different month. As a consequence, DOM elements are no longer destroyed when changing month.
This fixes the following issue which occurred when BrowserAnimationsModule was used: when using the keyboard to navigate from one month to another, the focused element was destroyed during the change detection of the keyboard event, which synchronously triggered the focusout event in Chrome, leading to a change in the data model (and that change is still part of the data model only when BrowserAnimationsModule is used, because that module changes the behavior of Angular to not destroy views and their data model as quickly as when this module is not loaded), and this was causing the …
> fix(datepicker): ExpressionChangedAfterItHasBeenCheckedError

- demo/src/app/app.component.html
- demo/src/style/app.scss
Before (current live site):
After:
cc @benouat
> chore(demo): fix social buttons alignment

- misc/plunk-gen.js
After the migration to CLI, bundle name has changed to from `bundles/ng-bootstrap.js` to `bundles/ng-bootstrap.umd.js`
> chore: fix umd bundle name for plunker

- src/datepicker/adapters/ngb-date-adapter.ts
- src/datepicker/adapters/ngb-date-native-adapter.spec.ts
- src/datepicker/adapters/ngb-date-native-adapter.ts
- src/datepicker/datepicker-config.ts
- src/datepicker/datepicker-day-template-context.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-month-view.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker-tools.spec.ts
- src/datepicker/datepicker-tools.ts
- src/datepicker/datepicker-view-model.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
- src/test/datepicker/common.ts
Note: check 'hide whitespaces changes' in the diff view when looking at changes in `datepicker.spec.ts`
---
BREAKING CHANGE: all public datepicker APIs now use generic type <D> for the date model.
If you're using any kind of adapter with the datepicker (ex. `NgbDateNativeAdapter`), now all of the following public datepicker APIs will use your date model <D> and not `NgbDateStruct` as previously:
```typescript
class NgbDatepicker<D> {
@Input() markDisabled: (date: D, current: {year: number, month: number}) => boolean;
@Input() maxDate: D;
@Input() minDate: D;
@Output() select = new EventEmitter<D>();
}
class NgbInputDatepicker<D> {
@Input() markDisabled: (date: D, current: {year: number, month: number}) => boolean;
@Input() maxDate: D;
@Input() minDate: D;
@Output() dateSelect = new …
```
> feat(datepicker): use generic date model <D> for all public APIs

- src/dropdown/dropdown.spec.ts
- src/dropdown/dropdown.ts
* fixes a regression introduced in 2.2.1: click handler didn't mark component as dirty
* cleans up click handler correctly
* removes unnecessary checks in tests
Fixes #2559
> fix(dropdown): close dropdown correctly inside the OnPush component

- src/modal/modal-stack.ts
- src/modal/modal.spec.ts
- src/typeahead/typeahead.spec.ts
- `Injector.create()` in modal stack
- rxjs `merge` operator in typeahead tests
> chore: fix deprecations in the code

- src/modal/modal-stack.ts
- src/modal/modal.module.ts
- added `NgbModal` to the list of providers
- use `moduleCFR` instead
No idea how to add tests for this though...
Use case that wasn't working:
```ts
@NgModule({
/** no ng bootstrap deps here **/
})
class AppModule {}
@NgModule({
imports: [NgbModalModule],
entryComponents: [ModalContentComponent]
})
class LazyLoadedModule {}
```
> fix(modal): use correct ComponentFactoryResolver

- src/datepicker/datepicker-integration.spec.ts
- src/datepicker/datepicker.ts
Forgotten use case with multiple months view in just merged #2593
> fix(datepicker): correctly override year numerals for multiple months

- demo/src/app/components/shared/examples-page/examples.component.ts
`NgbdExamplesPage` has been defined to be `ChangeDetectionStrategy.OnPush` on last demos website refactor (#2520).
This breaks some demos. It must *not* be OnPush
> fix(demo): NgbdExamplesPage must not be OnPush

- demo/src/app/components/tooltip/demos/customclass/tooltip-customclass.html
- demo/src/app/components/tooltip/demos/customclass/tooltip-customclass.ts
- demo/src/app/components/tooltip/tooltip.module.ts
- src/tooltip/tooltip-config.spec.ts
- src/tooltip/tooltip-config.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
This PR implements the feature requested in #1349, and as @pkozlowski-opensource suggested, it is almost *exactly* a copy of what was done for popovers in 483bd05.
> feat(tooltip): ability to add custom CSS classes to tooltip window

- src/modal/modal-stack.ts
- src/modal/modal-window.ts
- src/util/scrollbar.ts
Minor change for the sake of consistency. Now all `@Inject(DOCUMENT)` injections in constructor look the same.
> refactor: specify _document type

- src/datepicker/adapters/ngb-date-native-utc-adapter.spec.ts
- src/datepicker/adapters/ngb-date-native-utc-adapter.ts
- src/datepicker/datepicker.module.ts
- src/index.ts
This PR implements a new adapter for the datepicker model which is very similar to `NgbDateNativeAdapter` with one difference: it uses the UTC date instead of the local date, as requested in #2631.
> feat(datepicker): NgbDateNativeUTCAdapter

- package.json
- src/karma.conf.js
Coverage was calculated incorrectly without source-maps. The build is slower, so had to bump `browserNoActivityTimeout`
> chore: enable source maps when testing with coverage

- demo/src/polyfills.ts
Demo uses `Object.values`, which is part of ES7, so it's not part of the `core-js/es6/object` polyfill. Because of that the demo doesn't work in the following browsers:
- Chrome < 54
- Edge < 14
- Firefox < 47
- Safari < 10.1
- IE
Source: [Object.values Browser compatibility on MDN ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values#Browser_compatibility)
Screenshot: https://i.imgur.com/wqgUF7s.png
> fix(demo) add Object.values polyfill

- src/timepicker/timepicker.ts
Fixes https://github.com/ng-bootstrap/ng-bootstrap/issues/2663
When width and height of the chevron don't match, the chevron might look chopped off at some root font sizes
**Default root font-size: 16px:** 
**Custom root font-size: 12px:** 
When width and height are equal, rendered chevron looks fine with any root font-size:
> fix(timepicker): chevron width and height must match

- src/datepicker/datepicker-navigation-select.ts
- src/datepicker/datepicker-navigation.ts
- src/timepicker/timepicker.ts
Fixes:
1. Native properties must go after prefixed ones
2. Remove `-ms-transform` (required only for IE9 ([caniuse](https://caniuse.com/#feat=transforms2d)))
3. Remove `-webkit-transform` (required only for Android 4.4+, Bootstrap supports Android 5.0+)
4. Add missing `-ms` flexbox prefixes (required for IE10)
5. Refactor flex properties:
```
-ms-flex: 1 1 9rem;
flex-grow: 1;
flex-basis: 9rem;
```
↓
```
-ms-flex: 1 1 9rem;
flex: 1 1 9rem;
```
P.S. I tested my changes in IE10, changed elements look good.
> Fix CSS prefixes

- src/popover/popover.spec.ts
- src/popover/popover.ts
Same case as for the tooltip in #2205 
Fixes #2688
> fix(popover): unregister event listener functions only if present

- src/datepicker/adapters/ngb-date-native-adapter.spec.ts
- src/datepicker/adapters/ngb-date-native-adapter.ts
- src/datepicker/adapters/ngb-date-native-utc-adapter.spec.ts
- src/datepicker/adapters/ngb-date-native-utc-adapter.ts
> fix(datepicker): convert years 0-99 correctly with native adapters

- src/datepicker/datepicker-config.ts
- src/datepicker/datepicker-day-template-context.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker-tools.ts
- src/datepicker/datepicker-view-model.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Many custom-day-display customisation cases can be solved by allowing to pass arbitrary user data to the day template context:
```html
<ng-template #t let-date="date" let-data="data">
{{ data }}    
<ng-template>
<ngb-datepicker [dayTemplate]="t" [dayTemplateData]="dayTemplateData"></ngb-datepicker>
```
```ts
dayTemplateData(date: NgbDate, currentMonth: {month, year}): any {
return 'custom data';
}
```
The big advantage is that this data is computed once when month view is constructed.
> feat(datepicker): allow to pass user data to the day template context

- demo/src/app/components/datepicker/demos/customday/datepicker-customday.html
- demo/src/app/components/datepicker/demos/range/datepicker-range.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
- demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts
- src/datepicker/datepicker-day-template-context.ts
- src/datepicker/datepicker-month-view.spec.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-tools.ts
Allows using $implicit shortcut for the day template context (previous `let-d='date'` also works):
```html
<ng-template #t let-d> {{ d.day }}</ng-template>
<ngb-datepicker [dayTemplate]="t"></ngb-datepicker>
```
cc @benouat
> feat(datepicker): add $implicit property for day template context

- demo/src/app/components/modal/demos/focus/modal-focus.html
- demo/src/app/components/modal/demos/focus/modal-focus.ts
- demo/src/app/components/modal/modal.module.ts
- misc/stackblitz-gen.js
- src/modal/modal-window.ts
- src/modal/modal.module.ts
- src/modal/modal.spec.ts
- src/util/focus-trap.ts
As mentioned in #2728 this PR introduced 2 new features:
+ ability to use a new `ngbAutofocus` attribute in your modal templates 
```html
<input type="text" ngbAutofocus />
```
+ introduction of a new `focusFirst` Modal Config option (will basically works as `ngbAutofocus` but finding automatically the first focusable element)
```typescript
/**
* Assign focus to the first focusable element when opened (true by default)
*/
focusFirst?: boolean;
```
---
Any newly opened modal will now do in that order:
- If `ngbAutofocus` is detected, it will be used to focus the decorated element.
- Else, it will look at `focusFirst` value (default to be `true`), find the first focusable element, and focus it.
- At this point, if nothing has been focus (not focusable element found, or `focusFirst` set to …
> feat(modal): [ngbAutofocus] option

- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
Regression introduced after marking carousel OnPush due to lack of tests. Now calling `detectChanges()` on interval and all public API actions.
Fixes #2766
> fix(carousel): change sildes on prev/next/select API calls with OnPush

- demo/src/app/components/datepicker/overview/datepicker-overview.component.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
- src/datepicker/ngb-date.spec.ts
- src/datepicker/ngb-date.ts
- relaxes implementation of `NgbDate` comparison methods
- updates documentation to clarify `NgbDate` vs `NgbDateStruct` differences
Don't squash, two separate commits
> refactor(datepicker): relax NgbDate comparison API to use NgbDateStruct

- yarn.lock
Adds yarn integrity hashes to lockfile. 
This feature is on by default with latest `yarn 1.10` → doing `yarn install` generates them automatically
> chore: add yarn integrity hashes

- e2e-app/e2e/src/datepicker/datepicker-autoclose.e2e-spec.ts
- e2e-app/e2e/src/datepicker/datepicker-autoclose.po.ts
- e2e-app/e2e/src/datepicker/datepicker-focus.e2e-spec.ts
- e2e-app/e2e/src/datepicker/datepicker-focus.po.ts
- e2e-app/e2e/src/datepicker/datepicker.po.ts
- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.html
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.ts
Part of #2463 
Adds autoclose tests for the datepicker to simplify unit testing with request animation frame
> test(datepicker): add e2e tests for autoClose

- e2e-app/e2e/src/dropdown/dropdown-autoclose.e2e-spec.ts
- e2e-app/e2e/src/dropdown/dropdown-autoclose.po.ts
- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.ts
Part of #2463 
Adds autoclose tests for the dropdown to simplify unit testing with request animation frame
> test(dropdown): add e2e tests for autoClose

- e2e-app/e2e/src/typeahead/typeahead-focus.e2e-spec.ts
- e2e-app/e2e/src/typeahead/typeahead.po.ts
- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/typeahead/focus/typeahead-focus.component.html
- e2e-app/src/app/typeahead/focus/typeahead-focus.component.ts
Part of #2463
Tests for typeahead focus. This is the implementation of what has been removed in #2464 (typeahead part).
> feat(typeahead): add e2e tests for focus

- e2e-app/e2e/src/tooltip/tooltip-autoclose.e2e-spec.ts
- e2e-app/e2e/src/tooltip/tooltip-autoclose.po.ts
- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.html
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.ts
Part of #2463
Adds autoclose tests for the tooltip to simplify unit testing with request animation frame
> test(tooltip): add e2e tests for autoClose

- e2e-app/e2e/src/popover/popover-autoclose.e2e-spec.ts
- e2e-app/e2e/src/popover/popover-autoclose.po.ts
- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/popover/autoclose/popover-autoclose.component.html
- e2e-app/src/app/popover/autoclose/popover-autoclose.component.ts
Part of #2463
Adds autoclose tests for the popover to simplify unit testing with request animation frame
> test(popover): add e2e tests for autoClose

- e2e-app/e2e/src/datepicker/datepicker-autoclose.e2e-spec.ts
- e2e-app/e2e/src/datepicker/datepicker-autoclose.po.ts
- e2e-app/e2e/src/datepicker/datepicker-focus.e2e-spec.ts
- e2e-app/e2e/src/datepicker/datepicker-focus.po.ts
- e2e-app/e2e/src/dropdown/dropdown-autoclose.e2e-spec.ts
- e2e-app/e2e/src/dropdown/dropdown-autoclose.po.ts
- e2e-app/e2e/src/modal/modal-focustrap.e2e-spec.ts
- e2e-app/e2e/src/modal/modal-focustrap.po.ts
- e2e-app/e2e/src/popover/popover-autoclose.e2e-spec.ts
- e2e-app/e2e/src/popover/popover-autoclose.po.ts
- e2e-app/e2e/src/start.e2e-spec.ts
- e2e-app/e2e/src/tools.ts
- e2e-app/e2e/src/tooltip/tooltip-autoclose.e2e-spec.ts
- e2e-app/e2e/src/tooltip/tooltip-autoclose.po.ts
- e2e-app/e2e/src/typeahead/typeahead-focus.e2e-spec.ts
- e2e-app/e2e/src/typeahead/typeahead.po.ts
- e2e-app/src/app/app.component.ts
- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.html
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.ts
- e2e-app/src/app/datepicker/focus/datepicker-focus.component.html
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
- e2e-app/src/app/modal/focustrap/modal-focustrap.component.ts
- e2e-app/src/app/navigation.component.ts
- e2e-app/src/app/popover/autoclose/popover-autoclose.component.html
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.html
- e2e-app/src/app/typeahead/focus/typeahead-focus.component.ts
- reset pages with router navigation instead of custom `.reset()` method
- add navigation to switch easily between test suites
> chore: add navigation to e2e tests to simplify resetting

- e2e-app/e2e/src/datepicker/datepicker-focus.e2e-spec.ts
- e2e-app/e2e/src/datepicker/datepicker.po.ts
Missing focustrap test for the datepicker
> test(datepicker): re-focus current date after inside click

- src/karma.sauce.conf.js
Edge: 15, 16 → 16, 17
Safari: 10, 11 → 11, 12
> chore: use latest Safari 12 and Edge 17 for testing

- src/datepicker/datepicker-navigation.scss
A hack has been necessary to target IE only.
The issue came from outline-style: auto, which doesn't work. 'auto' and 'solid' havn't the same aspect, so we need to keep 'auto' for other browsers.
> fix(datepicker): visual focus on arrows for ie

- src/modal/modal.spec.ts
- src/util/focus-trap.ts
When focus-trap needs to figure out what are the boundaries elements (first and last focusable elements) we need to perform an extra check to filter out elements with `tabindex="-1"`
Closes #2884
> fix(focustrap): discarding tabindex='-1' when finding element

- src/modal/modal-ref.ts
At first glance it was hard to differentiate `close` and `dismiss`.
> fix(modal): 'dimiss' ambiguity in docs

- src/datepicker/datepicker-keymap-service.ts
- src/rating/rating.ts
- src/typeahead/typeahead.ts
Before #2473 `Keys` corresponded ONLY to keys processed by the current widget
After the change `Keys` contain the list of ALL known Keys to ALL widgets.
Because of this some `preventDefault()` were called on keys not processed by current widget.
(2 commits)
Fixes #2895
P.S. Not sure what kind of tests to add for this
> Refactor keyboard handling to avoid event hijacking

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/typeahead/validation/typeahead-validation.component.html
- e2e-app/src/app/typeahead/validation/typeahead-validation.component.ts
- e2e-app/src/app/typeahead/validation/typeahead-validation.e2e-spec.ts
fix #2719 
Landed here the solution proposed in #2843 (thanks @wannadream !), with some changes:
- The fix for this particular issue is separated from the others,
- The 'if' inside the handleBlur has been simplified,
- Protractor tests have been added to cover this case
> fix(typeahead): prevent validation during an item click

- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
I refactored a bit (very very little bit) the way `showHint` and especially how to backup and restore input value properly when:
+ model gets reset
+ window is dismissed (Esc)
+ window is dismissed (click outside)
fixes #2816
closes #2850 (this PR closes and replaces that one)
PS: on the long run `showHint` would probably need a complete overhaul
> fix(typeahead): input value properly reset when hint/ngModel are used together

- demo/src/app/default/default.component.html
This wraps the statement about code coverage into the link,
to allow users see that coverage. Should enforce user trust.
Thanks!
> docs(home): add direct link to project code coverage

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
- src/util/util.spec.ts
- src/util/util.ts
Removes unnecessary model updates and change detections when focus moves
inside the datepicker
Before:
After:
Two commits, don't squash
> fix(datepicker): focus handling performance regression

- demo/src/app/app.module.ts
- demo/src/app/app.routing.ts
- demo/src/app/components/table/demos/basic/table-basic.html
- demo/src/app/components/table/demos/basic/table-basic.ts
- demo/src/app/components/table/demos/complete/countries.ts
- demo/src/app/components/table/demos/complete/country.service.ts
- demo/src/app/components/table/demos/complete/country.ts
- demo/src/app/components/table/demos/complete/sortable.directive.ts
- demo/src/app/components/table/demos/complete/table-complete.html
- demo/src/app/components/table/demos/complete/table-complete.ts
- demo/src/app/components/table/demos/filtering/table-filtering.html
- demo/src/app/components/table/demos/filtering/table-filtering.ts
- demo/src/app/components/table/demos/pagination/table-pagination.html
- demo/src/app/components/table/demos/pagination/table-pagination.ts
- demo/src/app/components/table/demos/sortable/table-sortable.html
- demo/src/app/components/table/demos/sortable/table-sortable.ts
- demo/src/app/components/table/overview/demo/table-overview-demo.component.ts
- demo/src/app/components/table/overview/table-overview.component.html
- demo/src/app/components/table/overview/table-overview.component.ts
- demo/src/app/components/table/table.module.ts
- demo/src/app/shared/side-nav/side-nav.component.ts
- demo/src/environments/environment.prod.ts
- demo/src/environments/environment.ts
- demo/src/environments/versions.ts
- demo/src/style/demos.css
- src/package.json
Adds the `Table` section to the demo site with an overview and several examples:
- basic table
- sorting
- pagination
- filtering
- async data service
cc @ExFlo, @pkozlowski-opensource, @benouat, @fbasso
> docs(table): add demo section about the table component

- demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts
Add a `[minDate]=today` to the demo. Makes sense to show off this feature, especially, because it is a demo of the vacation selector.
> docs(datepicker): add 'minDate' to demo in overview

- src/datepicker/hijri/ngb-calendar-islamic-civil.spec.ts
- src/datepicker/hijri/ngb-calendar-islamic-umalqura.spec.ts
Cycle though `expect()` instead of `it()` for calendar conversion tests
Before: 
```sh
Chrome 71.0.3578 (Mac OS X 10.12.6): Executed 8504 of 8504 SUCCESS (25.16 secs / 24.512 secs)
```
After: 
```sh
Chrome 71.0.3578 (Mac OS X 10.12.6): Executed 1217 of 1217 SUCCESS (21.951 secs / 21.531 secs)
```
> chore: make total unit test count refect reality

- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.html
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.ts
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.e2e-spec.ts
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.po.ts
- src/datepicker/datepicker-input.ts
- adds e2e tests for `autoClose` with `displayMonths` and clicks on outside days
- fixes an issue when datepicker popup was closed when using [autoClose]='outside' and clicking on outside days with multiple months opened
Fixes #2879
>  fix(datepicker): fix 'outsideDays' clicks for multiple months

- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.html
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.ts
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.e2e-spec.ts
- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.po.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.po.ts
- e2e-app/src/app/popover/autoclose/popover-autoclose.component.html
- e2e-app/src/app/popover/autoclose/popover-autoclose.component.ts
- e2e-app/src/app/popover/autoclose/popover-autoclose.e2e-spec.ts
- e2e-app/src/app/popover/autoclose/popover-autoclose.po.ts
- e2e-app/src/app/tools.po.ts
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.html
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.ts
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.e2e-spec.ts
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.po.ts
- e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.component.html
- e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.component.ts
- e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.e2e-spec.ts
- e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.po.ts
- src/datepicker/datepicker-input.ts
- src/dropdown/dropdown.spec.ts
- src/dropdown/dropdown.ts
- src/popover/popover.ts
- src/tooltip/tooltip.ts
- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
- src/util/autoclose.ts
The datepicker, dropdown, popover, tooltip and typeahead components share
the autoclose code.
The typeahead no longer registers a listener on the `document:click` event until the dropdown is open.
> refactor(autoclose): share autoclose code between components

- src/modal/modal-stack.ts
- src/modal/modal-window.ts
- src/modal/modal.spec.ts
- add missing `aria-modal` on the modal window.
- add `aria-hidden` on all sibling DOM branches from the modal window up to the document body
Fixes #2575
> fix(modal): add missing 'aria-modal' and 'aria-hidden' attributes

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
Fire `onTouched()` after the date selection in the popup
Fixes #2976
> fix(datepicker): update model correctly with updateOn: 'blur'

- README.md
- demo/src/app/getting-started/getting-started.component.html
Clarifies version ranges support, 
- shows we don't support NG 8 or BS 4.2.0 yet
- shows that we support BS 4.0.0 to 4.1.x
> chore: clarify supported version ranges in readme and docs

- src/rating/rating.ts
In Ivy, combining @Input and @ContentChild annotations is no longer supported
> refactor(rating): split the @Input and @ContentChild annotations

- src/dropdown/dropdown.module.ts
- src/index.ts
When building ng-bootstrap with Ivy, I'm getting the following error:
```
BUILD ERROR
src/buttons/label.ts(8,14): error TS-993001: Unsupported private class NgbButtonLabel. This class is visible to consumers via NgbButtonsModule -> NgbButtonLabel, but is not exported from the top-level library entrypoint.
src/buttons/radio.ts(80,14): error TS-993001: Unsupported private class NgbRadio. This class is visible to consumers via NgbButtonsModule -> NgbRadio, but is not exported from the top-level library entrypoint.
src/dropdown/dropdown.ts(71,14): error TS-993001: Unsupported private class NgbDropdownAnchor. This class is visible to consumers via NgbDropdownModule -> NgbDropdownAnchor, but is not exported from the top-level library entrypoint.
src/dropdown/dropdown.ts(95,14): error TS-993001: …
```
> fix: add missing exports

- src/buttons/checkbox.spec.ts
- src/buttons/checkbox.ts
- src/buttons/radio.spec.ts
- src/buttons/radio.ts
In short, the problem is that `ngModel` updates to the real value in the resolved promise, so we have to force mark for check all radios/checkboxes. Otherwise parent component with `OnPush` will prevent it.
Fixes #2980
> fix(buttons): display correct NgModel value inside OnPush component

- src/datepicker/datepicker-input.ts
- src/dropdown/dropdown.ts
- src/popover/popover.ts
- src/tooltip/tooltip.ts
- src/typeahead/typeahead.ts
- src/util/autoclose.ts
The motivation for this PR is to rollback breaking changes for those who extend autocloseable components (`NgbDatepickerInput`, `NgbTypeahead`, `NgbTooltip`, `NgbDropdown`, `NgbPopover`):
```ts
@Component()
class NgbPopover {
constructor(..., private _autoClose: AutoClose);
}
```
It was introduced in `4.0.1` and will break in `NgbPopover` children classes, because `AutoClose` is a private service.
---
**However, we don't want people to subclass our components** and https://github.com/ng-bootstrap/ng-bootstrap/issues/2623#issuecomment-413793539 is still true, but adding an injectable`AutoClose` change should have not been a part of a minor release IMO
> refactor(autoclose): transform service into a function to avoid DI

- demo/src/app/components/datepicker/datepicker.module.ts
- demo/src/app/components/datepicker/overview/datepicker-overview.component.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
- src/datepicker/datepicker-day-template-context.ts
- src/datepicker/datepicker-month-view.spec.ts
- src/datepicker/datepicker-month-view.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-tools.ts
Adds a custom CSS class `.ngb-dp-today` on a cell with today's date
and a custom `today: boolean` field in the day template context
Fixes #1470
> feat(datepicker): mark today's date with a custom class

- demo/src/app/components/pagination/demos/customization/pagination-customization.html
- demo/src/app/components/pagination/demos/customization/pagination-customization.ts
- demo/src/app/components/pagination/overview/pagination-overview.component.html
- demo/src/app/components/pagination/overview/pagination-overview.component.ts
- demo/src/app/components/pagination/pagination.module.ts
- src/index.ts
- src/pagination/pagination.module.ts
- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
Provides the way of customizing the markup of pagination links using child templates (in the cases where CSS is not enough):
```html
<ngb-pagination>
<ng-template ngbPaginationFirst>First</ng-template>
<ng-template ngbPaginationLast>Last</ng-template>
<ng-template ngbPaginationPrevious>Prev</ng-template>
<ng-template ngbPaginationNext>Next</ng-template>
<ng-template ngbPaginationEllipsis>...</ng-template>
<ng-template ngbPaginationNumber let-page>{{ page }}</ng-template>
</ngb-pagination>
```
Obviously one can customize only what's necessary, not everything.
`NgbPaginationNumber` template has the following context:
```ts
interface {
$implicit: number;   // page displayed by current cell
currentPage: number; // currently selected page
disabled: boolean;   // true, if current cell is …
```
> feat(pagination): allow customizing pagination links

- src/popover/popover-config.spec.ts
- src/popover/popover-config.ts
- src/popover/popover.spec.ts
- src/tooltip/tooltip-config.spec.ts
- src/tooltip/tooltip-config.ts
- src/tooltip/tooltip.spec.ts
The commit #2972  introduced a non backward changes on dropdown placement for some widgets. This is the revert for their default configurations.
> fix(positionning): auto positionning for tooltip and popover

- demo/src/app/components/popover/demos/delay/popover-delay.html
- demo/src/app/components/popover/demos/delay/popover-delay.ts
- demo/src/app/components/popover/popover.module.ts
- demo/src/app/components/tooltip/demos/delay/tooltip-delay.html
- demo/src/app/components/tooltip/demos/delay/tooltip-delay.ts
- demo/src/app/components/tooltip/tooltip.module.ts
- src/popover/popover-config.spec.ts
- src/popover/popover-config.ts
- src/popover/popover.ts
- src/tooltip/tooltip-config.spec.ts
- src/tooltip/tooltip-config.ts
- src/tooltip/tooltip.ts
- src/util/triggers.spec.ts
- src/util/triggers.ts
This PR is an implementation of the feature requested in #1052.
It adds the `triggerOpenDelay` and `triggerCloseDelay` properties on the `tooltip` and `popover` components.
Notes:
- **The API documentation will have to be updated for the new properties to include the `@since` keyword with the right version number.**
> feat(tooltip): add openDelay and closeDelay

- demo/src/app/components/accordion/accordion.module.ts
- demo/src/app/components/accordion/demos/header/accordion-header.html
- demo/src/app/components/accordion/demos/header/accordion-header.ts
- src/accordion/accordion.module.ts
- src/accordion/accordion.spec.ts
- src/accordion/accordion.ts
- src/index.ts
A more genetic alternative to #2845 to add any content to accordion header.
The idea is to introduce two directives `ng-template[ngbPanelHeader]` and `button[ngbPanelToggle]` to be used as follows:
```html
<ngb-accordion>
<ngb-panel>
<ng-template ngbPanelHeader let-opened="opened">
<button ngbPanelToggle>Panel Title</button>
</ng-template>
<ng-template ngbPanelContent> ... </ng-template>
</ngb-panel>
</ngb-accordion>
```
Demo shows an example of adding some controls to headers:
This will compliment and take precedence over two existing ways of providing a title:
```html
<ngb-accordion>
<ngb-panel title="Panel Title">
<ng-template ngbPanelContent> ... </ng-template>
</ngb-panel>
</ngb-accordion>
<ngb-accordion>
<ngb-panel>
<ng-template ngbPanelTitle>Panel Title</ng-template>
<ng-template …
```
> feat(accordion): allow any content in the accordion card header

- src/timepicker/timepicker.spec.ts
- src/timepicker/timepicker.ts
Mousewheel support is more controversial, and would probably
need an additional input + config to enable/disable it, as it's used by
users which are not proficient keyboard users to scroll the page.
But I think keyboard support is a must, and can be turned on always.
refs #459
> feat(timepicker): use arrow keys to increment/decrement values

- src/accordion/accordion.ts
Classes were forgotten for default card header implementation in #2981 
cc @benouat :)
> fix(accordion): restore forgotten 'btn btn-link' after refactoring

- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
Change the documentation for the DatePicker component in the isDisabled section example. Currently, day is undefined if user follows documentation.
> fix(docs): change day variable to correct argument reference

- misc/parse-demo-test-cases/multiple/one/test.component.ts
- misc/parse-demo-test-cases/multiple/one/test.module.ts
- misc/parse-demo-test-cases/multiple/two/test.component.ts
- misc/parse-demo-test-cases/multiple/two/test.module.ts
- misc/parse-demo.spec.ts
- misc/parse-demo.ts
Now parses all existing demos in one take and returns a Map → much faster compilation time compared to parsing demos one-by-one
> chore: update demo parsing for stackblitzes

- demo/src/app/components/typeahead/demos/http/typeahead-http.html
The wikipedia demo mentions the `do` operator but uses the `tap` operator.
> demo(typeahead): mention tap instead of do operator

- CONTRIBUTING.md
> docs: fix 'Code conventions' link in contribution doc

- src/popover/popover.spec.ts
- src/popover/popover.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
Forces change detection run on `.open()` to avoid having `ExpressionHasChanged` exception when opened after change detection was run (ex. from hooks)
Fixes #3130
> Open tooltip and popover correctly from hooks

- src/popover/popover.spec.ts
- src/test/common.ts
- src/tooltip/tooltip.spec.ts
With Ivy, DebugRenderer2 is going away.
It means that listeners added with Renderer2.listen() are no longer added to the DebugElement.
And so, DebugElement.triggerEventHandler() no longer trigger them.
As a consequence, most tooltip and popover tests are failing with Ivy.
> test: refactor tests with triggers (tooltip, popover)

- src/datepicker/datepicker.ts
datepicker accessed a view child from the ngAfterContentInit hook instead of accessing it from the ngAfterViewInit hook.
This doesn't work anymore with Ivy. That is a regression in Ivy, but is also an issue with ng-bootstrap which doesn't respect the standard life-cycle.
Besides, the component didn't implement the AfterContentInit interface.
It now implements the AfterViewInit interface.
fix #3150
> fix(datepicker): access view child from ngAfterViewInit

- angular.json
- e2e-app/tsconfig.spec.json
TSLint rule was in place, but not activated, because `e2e-app/tsconfig.spec.json` for e2e tests wasn't taken into account.
> chore: check for focused tests in e2e application

- src/index.ts
It wasn't exported from `index.ts` -> wasn't available from `@ng-bootstrap/ng-bootstrap`
Fixes #3160
> fix(datepicker): export NgbDatepickerNavigateEvent correctly

- demo/src/app/components/datepicker/calendars/datepicker-calendars.component.ts
- demo/src/app/components/datepicker/overview/datepicker-overview.component.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
- demo/src/app/components/pagination/overview/pagination-overview.component.html
- demo/src/app/components/pagination/overview/pagination-overview.component.ts
- demo/src/app/components/shared/examples-page/demo.component.html
- demo/src/app/components/shared/examples-page/demo.component.ts
- demo/src/app/getting-started/getting-started.component.html
- demo/src/app/getting-started/getting-started.component.ts
- demo/src/app/shared/code/code.component.ts
- demo/src/app/shared/code/snippet.ts
To define snippet information all in one place for clarity, avoid the multiplication of input properties on the `ngbd-code` component, and have common processing such as a handy indentation cleaner (common issue when defining multi-line strings with template strings).
> chore(demo): use Snippet model for ngbd-code

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Previous attempt in navigation cancellation changed was buggy → #3044
After cancellation year and month select boxes stayed unchanged, but the actual month content changed. 
Test expectations were incomplete.
> fix(datepicker): don't change month content if navigation is prevented

- demo/tsconfig.json
- tsconfig.json
Fixes #3174 
For the demo, we're actually sing `Object.values` polyfill and `es2017`
> chore: use es2015 lib version in tsconfig.json

- src/rating/rating.spec.ts
In VE, DebugElement.attributes reads values from an internal map which is updated by the the DebugRenderer2. It Ivy, it reads the DOM directly.
When an attribute is removed, DebugRenderer2 sets the value to null in the internal map. But reading it from the DOM returns undefined.
Tests relying on that null value fails in Ivy.
> test(rating): removed attribute can be null or undefined

- .travis.yml
- package.json
- yarn.lock
The only issue was `yarn check-format` that is the last task that uses gulp internally, so I just run `yarn upgrade gulp` that fixes the Node 10 compatibility issue. 
Node 8 still works.
> chore: upgrade 'gulp' package to be able to use node 10 LTS for builds

- src/popover/popover.ts
- src/tooltip/tooltip.ts
- src/typeahead/typeahead.ts
- src/util/popup.ts
Due to implementation details, it is not possible to rely only on ViewContainerRef to instantiate a template for the popup. It does fail either in Ivy or in the View Engine.
Using the ApplicationRef instead solves the issue.
> refactor(popup): use ApplicationRef to instantiate the template

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
This pull request adds "closed" event to NgbInputDatepicker, which is fired after closing datepicker window.
Example:
`<input ngbDatepicker (closed)="onClose()">`
Very useful for handling whenever user closing date-picker by clicking outside of dp box.
> feat(datepicker): add 'closed' event and fire after closing dp window

- .travis.yml
According to https://benlimmer.com/2019/01/14/travis-ci-xvfb/ `before_script` usage to start xvfb should not be used anymore.
> chore(ci): travis update for xvfb initialisation

- src/util/positioning.ts
Without forcing the popup in a separate layer, Safari and Firefox are doing a lot more work than necessary.
Example: trying to reposition datepicker 3 times, before finding an optimal position.
Quite significant changes in Safari → removes full page layout and compositing.
Safari Before:
Safari After:
In Firefox it removes unnecessary paints as well.
---
Concerning the `The translate3d/gpu acceleration render a blurry text on chrome, the next line is commented until a browser fix` → we're not using `translate3d`, but `translate`. And it looks fine in Chrome.
Related to #3199
> fix(positioning): put the popup in a separate layer

- demo/src/polyfills.ts
`Object.values` is used at runtime to compute all the table of content navigation.
Polyfill has been accidentally removed recently, crashing demo website on all IE browsers
> fix(demo): missing `Object.values()` polyfill for IE.

- src/accordion/accordion.module.ts
- src/alert/alert.module.ts
- src/buttons/buttons.module.ts
- src/carousel/carousel.module.ts
- src/collapse/collapse.module.ts
- src/datepicker/datepicker.module.ts
- src/dropdown/dropdown.module.ts
- src/index.ts
- src/modal/modal.module.ts
- src/pagination/pagination.module.ts
- src/popover/popover.module.ts
- src/progressbar/progressbar.module.ts
- src/rating/rating.module.ts
- src/tabset/tabset.module.ts
- src/timepicker/timepicker.module.ts
- src/tooltip/tooltip.module.ts
- src/typeahead/typeahead.module.ts
Deprecated in 3.0.0 and due removal since 4.0.0.
> Removes forRoot() from modules

- misc/generate-stackblitzes.ts
- misc/stackblitzes-templates/polyfills.ts
- package.json
- yarn.lock
Finally, for Angular 8 migration, we removed a bit eagerly all
references to 'core-js' due to differential loading being shipped.
According to Angular default scaffolded app generated from StackBlitz
it is still needed somehow.
Fixes #3251
> chore: missing 'core-js' for StackBlitz to work.

- src/index.ts
Main export of NgbToastModule was missing, which basically prevented
people to write
```typescript
import {NgbToastModule} from "@ng-bootstrap/ng-bootstrap";
```
Fixes #3258
> fix(toast): export NgbToastModule publicly

- src/accordion/accordion.module.ts
- src/alert/alert.module.ts
- src/buttons/buttons.module.ts
- src/carousel/carousel.module.ts
- src/collapse/collapse.module.ts
- src/datepicker/datepicker.module.ts
- src/dropdown/dropdown.module.ts
- src/index.ts
- src/modal/modal.module.ts
- src/pagination/pagination.module.ts
- src/popover/popover.module.ts
- src/progressbar/progressbar.module.ts
- src/rating/rating.module.ts
- src/tabset/tabset.module.ts
- src/timepicker/timepicker.module.ts
- src/tooltip/tooltip.module.ts
- src/typeahead/typeahead.module.ts
With #3231 (via 83f79cf) when all `.forRoot()` methods have been removed, cleaning unused imports has not been done.
→ `ModuleWithProviders` is not needed anymore.
> chore: removes `ModuleWithProviders` unused import

- demo/src/app/app.component.html
- demo/src/public/index.html
- demo/src/style/app.scss
Simply removes both social links buttons for Github and Twitter.
Replaces them with static links, pointing to the right location.
Both links have the proper `target="_blank"` associated with the `rel="nofollow noopener noreferrer"` combo.
Visual aspect of the new look
Twitter link is still using the [Web Intent](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent.html) API, and clicking it will forward you to Twitter with
Fixes #3254
> chore(demos): replaces social links buttons with static ones

- demo/src/app/components/carousel/demos/basic/carousel-basic.html
- demo/src/app/components/carousel/demos/config/carousel-config.html
- demo/src/app/components/carousel/demos/navigation/carousel-navigation.html
- demo/src/style/demos.css
The carousel samples in the demo site contain images that are loaded asynchronously. But as their size is not reserved beforehand, they shift the remaining content when loaded. As a consequence, the scrolling position that was set correctly to target a specific sample before the images are loaded is no longer correct after the images are loaded.
This PR reserves the space for the images by using the trick documented in the following link to also keep the responsive behavior:
https://itnext.io/how-to-stop-content-jumping-when-images-load-7c915e47f576
> fix(demo): direct link to specific carousel sample not working

- demo/src/app/components/table/demos/complete/country.service.ts
I noticed a small inconsistency on the demos for the table component. I searched for the term
"China" and expected it to return exactly one result, but none matched. The other table
demos handle this case correctly, so I thought something must be wrong with the complete example.
Turns out, there was just a `.toLowerCase()` missing, when the name of the country was compared to the search term. 
<hr>
> docs(table): fixed search for complete example

- src/dropdown/dropdown.spec.ts
- src/dropdown/dropdown.ts
fix #3269 when the dropdown is inside a navbar
> fix(dropdown): remove x-placement inside a navbar

- src/datepicker/hijri/ngb-calendar-islamic-umalqura.spec.ts
- src/datepicker/hijri/ngb-calendar-islamic-umalqura.ts
`NgbCalendarIslamicUmalqura.fromGregorian` returned a date one day after the correct date for dates containing a time in the afternoon.
Fixes #3237
> fix(datepicker): NgbCalendarIslamicUmalqura.fromGregorian with date in the afternoon

- demo/src/app/components/toast/demos/prevent-autohide/toast-prevent-autohide.html
- demo/src/app/components/toast/demos/prevent-autohide/toast-prevent-autohide.module.ts
- demo/src/app/components/toast/demos/prevent-autohide/toast-prevent-autohide.ts
- demo/src/app/components/toast/toast.module.ts
- src/toast/toast.spec.ts
- src/toast/toast.ts
Toasts initially setup with `[autohide]="true"`were wrongly still emitting `(hide)` output after toggling `autohide` to `false`.
A new demo has also been created to illustrate the `autohide` toggling support, 'Prevent autohide on mouseover'.
Fixes #3280
> fix(toast): proper handling of `autohide` toggling

- src/popover/popover.scss
To stick with Bootstrap, since https://github.com/twbs/bootstrap/pull/27750
It hasn't been done for the tooltip, I just do the change for the popover.
> fix(popover): apply arrow styles to direct descendant

- src/datepicker/datepicker.scss
- src/datepicker/datepicker.ts
- sets background color in ngb-dp-* classes instead of using .bg-light
closes #3244
> feat(datepicker): ease the styling of datepicker

- src/modal/modal-stack.ts
- src/modal/modal-window.ts
- src/modal/modal.scss
- src/modal/modal.spec.ts
In `5.0.0` we introduced the bootstrap scrollable content feature.
This behaviour appears to be broken with modal that have content generated
from a component. Overall styling is wrong, resulting in a broken modal
not scrollable.
~~The fix is duplicating the `.modal-content` css class on the component
host itself that will thus act as the
original `<div class="modal-content">`~~
~~**EDIT** after 32c400f : The fix is adding some extra styling in order to force the component
host to fit inside the parent `.model-content` flex display.~~
**EDIT** after 222752d: The fix is now adding some styling via a class to benefit from autoprefixer as IE10 does not understand `display: flex`
Fixes #3281
> fix(modal): component based content was not scrollable

- src/tabset/tabset.spec.ts
- src/tabset/tabset.ts
Align tabset aria attributes to Bootstrap one (https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior)
> fix(tabset): remove aria-expanded and use aria-selected instead

- demo/src/app/components/carousel/carousel.module.ts
- demo/src/app/components/carousel/demos/pause/carousel-pause.html
- demo/src/app/components/carousel/demos/pause/carousel-pause.module.ts
- demo/src/app/components/carousel/demos/pause/carousel-pause.ts
- src/carousel/carousel.module.ts
- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
- src/index.ts
After setting the carousel on pause through its `pause()` method and clicking on navigation arrows, the carousel no longer automatically restarts. Calling the `cycle()` method is needed to undo the effect of the `pause()` method.
When `pauseOnHover` is true, hovering on the carousel no longer uses the `pause()` and `cycle()` methods. The hover status is stored separately, so that calling `pause()` and removing the mouse from the carousel no longer restarts it automatically.
The slide event now has a "source" property allowing to know what triggered the event: "timer", "arrowLeft", "arrowRight" or "indicator".
The "pause" boolean status is now also included in the slide event.
Closes #3188
> feat(carousel): stay paused after calling `pause()` until `cycle()` is called

- yarn.lock
Updated Webdriver versions, so that Protractor's Webdriver is compatible with Chrome.
@benouat Please review
> fix(generic): Protractor Webdriver Combatibility

- src/datepicker/datepicker-month-view.ts
A finding of an a11y test on a project, where the Datepicker is used, was that the proposed columnheader role is missing, thus making the datepicker not accessible for blind users.
> fix(a11y): make datepicker more accessible

- src/datepicker/datepicker-month-view.scss
This is minor change that moves currently focus day within month view
above its siblings to let its outline be correctly rendered.
This is similar to minor stylistic corrections found in the BS:
https://git.io/fjyfh
The before rendering (Chrome/Mac OS):
And after the change:
Thanks!
> feat(datepicker): place active day above its siblings

- src/datepicker/datepicker-month-view.scss
- src/datepicker/datepicker-month-view.ts
- src/datepicker/datepicker.scss
@benouat 
@maxokorokov 
Please review
> fix(datepicker): remove hardcoded bg-light

- e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
- src/datepicker/datepicker-input.ts
At the moment the focus is lost, so it will be restored to the
previously focused element (before datepicker was opened)
Fixes #3317
Fixes #3358
> fix(datepicker): restore focus after closing popup

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/datepicker/datepicker.po.ts
- e2e-app/src/app/modal/nesting/modal-nesting.component.html
- e2e-app/src/app/modal/nesting/modal-nesting.component.ts
- e2e-app/src/app/modal/nesting/modal-nesting.e2e-spec.ts
- e2e-app/src/app/modal/nesting/modal-nesting.po.ts
- e2e-app/src/app/tools.po.ts
- src/modal/modal-window.spec.ts
- src/modal/modal-window.ts
- src/modal/modal.spec.ts
- src/util/autoclose.ts
Fixes an issue for datepicker, typeahead, dropdown inside the modal.
When these components are closed on ESC, modal stays open.
The idea is to:
- use the same `keyup` for all ESC autoclose handling
- make modal `keyup` check run after all other autoclose checks
- don't close the modal if event was default prevented
Fixes #3358
> fix(modal): don't close popup on ESC when closing nested components

- demo/src/app/components/progressbar/demos/basic/progressbar-basic.html
- demo/src/app/components/progressbar/demos/config/progressbar-config.html
- src/progressbar/progressbar-config.spec.ts
- src/progressbar/progressbar.spec.ts
- src/progressbar/progressbar.ts
This change outlines that types are based on Bootstrap background color
variants, thus allowing types like 'dark', 'light', etc.
Closes: #3391
Sample from updated docs section:
> docs(progressbar): extend documentation for types

- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
- for editable false clear the value on input change instead of on suggestions fetched
Closes #3262
> fix(typeahead): for editable false clear the value on input change

- demo/src/style/app.scss
The side bar is not easily usable when the device height is too short, on laptop for example.
> demo: provide a scrollbar on the sidebar for short height

- e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-tools.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/ngb-calendar.spec.ts
- src/datepicker/ngb-calendar.ts
@benouat 
@maxokorokov 
Rebased and updated tests.
Please review.
> Calendar get prev get next focus on same day instead of first

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-tools.spec.ts
- src/datepicker/datepicker-tools.ts
Limits the number of years displayed in the select box to 1000 at a time.
Fixes #3338
> fix(datepicker): performance issues when huge min/max dates

- angular.json
- demo/tsconfig.ie.json
- package.json
Apparently, a separate build configuration is required for Angular CLI 8 targeting `es5` for serving during development. Production build is unchanged.
> chore: add demo serve configuration for IE/es5

- src/datepicker/datepicker-navigation-select.ts
In View Engine, directives are updated before property bindings. So <option> elements are created/updated before the [value] binding is set/updated in <select>. In the end, the right option is selected in the browser.
In Ivy, things are executed in the reverse order. Setting the value property of a <select> when there is no matching <option> does nothing in a real browser. As a result, the first option is always selected after the first render.
> refactor(datepicker): move <select> value binding to lifecycle hook

- src/toast/toast.spec.ts
- src/toast/toast.ts
This is cleanup change, removing unused binding from source code.
Closes: #3383
> chore(toast): remove unused css host class binding

- src/buttons/checkbox.spec.ts
- src/buttons/checkbox.ts
This attribute is yet to be supported by specs.
See: https://git.io/JesTb and #3376
> fix(checkbox): remove autocomplete attribute

- demo/src/app/components/datepicker/demos/popup/datepicker-popup.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
Fixes #3306 by adding an "info" alert below the "Datepicker in a popup" demo explaining that you must provide the icon yourself.
> docs(datepicker): add information about datepicker icon (#3306)

- package.json
- src/karma.conf.js
- yarn.lock
The project comes with confgiguration for local IE build supporting ES5
and for SouceLabs remote configuration for IE browsers, but it has no
relevant entry to allow tests on local setup. This are minimal changes
to allow local tests with IE on Windows box.
Example syntax:
```bash
yarn test --browsers IENoExtensions --configuration ie
```
There is no configuration for size of the launched IE instance, so in
order to have tests depending on the viewport size - like overlays
positioning on top/left/right/bottom, the IE instance has been
configured to run in the kiosk mode ('-k').
Aftermant of the discussion here:
https://github.com/ng-bootstrap/ng-bootstrap/pull/3406#issuecomment-539904150
```cmd …
```
> test(ie): local configuration for InternetExplorer

- src/rating/rating.spec.ts
This should cover missing block in the coverage for `rating.ts`.
Thanks!
> test(rating): add missing coverage block

- src/modal/modal-config.spec.ts
- src/modal/modal-config.ts
This fixes compile error when a user tries to set any of this fields in a `NgbModalConfig` instance.
> fix(modal): add missing fields to `NgbModalConfig`

- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
This fixes issues with custom tooltip class changes  not being applied after
tooltip creation.
Fixes: #3335
> fix(tooltip): implement change detection

- src/datepicker/datepicker-navigation.spec.ts
- src/datepicker/datepicker-navigation.ts
This fixes an issue on some clients due to browser being inconsistent on
handling focus on the button clicks. After the change the navigation
button within the datepicker will retain focus to allow subsequent
keyboard based navigation within datepicker instance.
Fixes: #2780
This is quite established problem and here is most recent article on the topic:
https://zellwk.com/blog/inconsistent-button-behavior/
Thanks!
> fix(datepicker): retain focus on navigation links

- src/modal/modal-ref.ts
- src/modal/modal.spec.ts
- src/modal/modal.ts
This should be mostly compatible with current branch. As latest version of this use Angular 6.1 and Angular itself uses TS2.9, I take the liberty to update those dependencies to latest of each branch to be able to use conditional types. 
Using conditional types I manage to strong type the `componentInstance` property only when you open a Component. However by using default types, developers should have the same experience that they currently have, meaning, the `componentInstance` property is default to any. Regardless that, this could have some breaking scenarios, but please notice that those scenarios should not be working on the first place as this change only typing, and not behavior.
Fix: …
> feat(modal): set strong typing in componentInstance getter property

- src/popover/popover.spec.ts
- src/popover/popover.ts
Changing `[popoverClass]="expr"` while the popover is opened was not correctly propagated to the popover window
Similar to the fix for the tooltip (#3335), but for the popover.
@peterblazejewicz FYI
> fix(popover): propagate 'popoverClass' change correctly

- e2e-app/src/app/dropdown/focus/dropdown-focus.component.html
`ngbDropdownMenu` uses `@ContentChildren` query to get `ngbDropdownItem`'s that wont't work with NG9
> test(dropdown): use 'ng-template' instead of 'ng-container'

- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
Fixes #1235.
I haven't implemented the complex change of logic that was talked about in [this comment](https://github.com/ng-bootstrap/ng-bootstrap/issues/1235#issuecomment-274068255), but I have fixed the simple case where a single page number was replaced with an ellipsis. I thought that fixing this would be better than nothing. 😁 
You can see this change of behavior in the demo under the [_Advanced pagination_](https://ng-bootstrap.github.io/#/components/pagination/examples#advanced) section. 
* The first pagination component would hide page 11 when the selected page was anywhere from 6 to 10.
* The second pagination component would hide page 2 when the selected page was 5.
* The second …
> fix(pagination): don't hide single page number with ellipsis (#1235)

- src/dropdown/dropdown.module.ts
- src/index.ts
Building with NG9 produced a warning for the forgotten export
> fix(dropdown): export `NgbNavbar` correctly

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/modal/focus/modal-focus.component.html
- e2e-app/src/app/modal/focus/modal-focus.component.ts
- e2e-app/src/app/modal/focus/modal-focus.e2e-spec.ts
- e2e-app/src/app/modal/stack/modal-stack.component.html
- e2e-app/src/app/modal/stack/modal-stack.component.ts
- e2e-app/src/app/modal/stack/modal-stack.e2e-spec.ts
- e2e-app/src/app/modal/stack/modal-stack.po.ts
- e2e-app/src/app/tools.po.ts
- src/modal/modal-window.ts
- src/modal/modal.spec.ts
> fix(modal): keep focus trap between stack modals

- src/progressbar/progressbar.spec.ts
- src/progressbar/progressbar.ts
closes #3386
Currently the following is displayed when max is set to 0, null or undefined:
After this change the max value will be set to 100 if it is invalid so that a progressbar with a valid value can be displayed.
> fix(progressbar): display progressbar correctly for invalid max value

- demo/src/app/components/dropdown/demos/navbar/dropdown-navbar.html
- src/util/autoclose.ts
This fixes multiple issues related to popup components auto closing.
Don't use touch events anymore as everything works fine with `mouseup/down`
Fixes #3446
Fixes #3437
Fixes #3412
Fixes #3192
Fixes #3145
Fixes #3024
> fix(autoclose): fix popup components auto closing in Safari 13

- src/modal/modal-window.spec.ts
- src/modal/modal-window.ts
- src/modal/modal.spec.ts
- src/util/autoclose.ts
Keyboard events in modal and autoclose handling use 'keydown' instead of 'keyup'
Fixes #3439 
---
Unfortunately no way of adding e2e tests for this case
> fix(modal): don't close modal on ESC if file dialog is open

- src/datepicker/datepicker-input.ts
- src/modal/modal-stack.ts
- src/util/focus-trap.ts
Runs `ngbFocusTrap` outside angular (similarly to what is done for `ngbAutoClose`) to avoid triggering unnecessary CDs.
Basically just wraps contents with `runOutsideAngular()`:
```ts
ngbFocusTrap(zone: NgZone, ...) {
zone.runOutsideAngular(() => {
// ...
});
}
```
> fix(focustrap): run focus trap event handlers outside Angular

- demo/src/app/components/collapse/collapse.module.ts
- demo/src/app/components/collapse/demos/navbar/collapse-navbar.html
- demo/src/app/components/collapse/demos/navbar/collapse-navbar.module.ts
- demo/src/app/components/collapse/demos/navbar/collapse-navbar.ts
I've created a basic responsive navbar example using an `ngbCollapse` directive.
Fixes #2928.
> docs(collapse): add example for responsive navbar (#2928)

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/modal/autoclose/modal-autoclose.component.html
- e2e-app/src/app/modal/autoclose/modal-autoclose.component.ts
- e2e-app/src/app/modal/autoclose/modal-autoclose.e2e-spec.ts
- e2e-app/src/app/modal/autoclose/modal-autoclose.po.ts
- e2e-app/src/app/modal/stack/modal-stack.e2e-spec.ts
- src/modal/modal-window.spec.ts
- src/modal/modal-window.ts
- src/modal/modal.spec.ts
This uses a combination of 'mousedown/up' events instead of 'click'.
Aligns behavior with bootstrap and helps with closing modal accidentally (ex. when selecting text)
Some tests had to be converted to e2e
Closes #3415
Fixes #1950
> fix(modal): ignore accidental backdrop clicks

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/timepicker/filter/timepicker-filter.component.html
- e2e-app/src/app/timepicker/filter/timepicker-filter.component.ts
- e2e-app/src/app/timepicker/filter/timepicker-filter.e2e-spec.ts
- e2e-app/src/app/timepicker/filter/timepicker-filter.po.ts
- src/timepicker/timepicker.ts
Finally a better proposal than #3236 to fix #2334
- The timepicker inputs are filtered (so a better approach than type="number" which supported differently depending on the browsers), 
- inputmode="numeric" is used to open the numeric keypad on mobile device, which is basically the purpose of this attribute, for the supported browsers (https://caniuse.com/#feat=input-inputmode : Chrome, Opera, iOs safari, Android, Samsung Internet)
> feat(timepicker): input filter to accept only numbers

- demo/src/app/components/progressbar/demos/texttypes/progressbar-texttypes.html
- demo/src/app/components/progressbar/demos/texttypes/progressbar-texttypes.module.ts
- demo/src/app/components/progressbar/demos/texttypes/progressbar-texttypes.ts
- demo/src/app/components/progressbar/progressbar.module.ts
- src/progressbar/progressbar-config.spec.ts
- src/progressbar/progressbar-config.ts
- src/progressbar/progressbar.spec.ts
- src/progressbar/progressbar.ts
This is a change request PR:
As advised on the Bootstrap documentation page when using some
background variants that is advisable to change the text color
accordingly, for example for readability purposes. The `textType` input
property allows to achieve this, adding support for binding text types
to `text-*` utility class on the progress bar.
Common scenario: progress bar with 'warning' type renders a white text on
the yellow background (assuming default BS). This change allows users to opt to
'dark' text type to improve the readability.
ref:
https://getbootstrap.com/docs/4.3/utilities/colors/#background-color
> chore(progressbar): allow to specify progressbar text type

- demo/src/app/components/datepicker/demos/config/datepicker-config.html
- demo/src/app/components/datepicker/demos/config/datepicker-config.ts
- src/datepicker/datepicker-input-config.spec.ts
- src/datepicker/datepicker-input-config.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker.module.ts
- src/index.ts
> feat(datepicker): input datepicker global config

- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
This commit adds support for aria-current attribute as per:
https://getbootstrap.com/docs/4.3/components/pagination/#disabled-and-active-states
https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Pagination
Thanks!
> feat(pagination): `aria-current` attribute support

- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
As per discussion in #3470 and as per:
https://getbootstrap.com/docs/4.3/components/pagination/#disabled-and-active-states
> feat(pagination): add 'aria-disabled' attribute

- demo/src/app/app.component.ts
- demo/src/app/app.routing.ts
Fixes the way anchor scrolling is handled in demo application:
- does NOTHING, if there is no fragment in the url (no scroll → no style/layout)
- uses `RAF` to adjust scroll **right before** the first paint
- uses standard `ViewportScroller`
- runs all outside of the zone
- removes this layout/style recalculation from the JS block
> demo: use `ViewportScroller` to adjust scroll position

- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
Small refactoring after #3468 and #3471:
- ellipsis should always be disabled
- use `prevDisabled()` and `nextDisabled()` where possible
> refactor(pagination): simplify the way disabled links are handled

- e2e-app/src/app/timepicker/filter/timepicker-filter.e2e-spec.ts
Neither COMMAND+C nor CONTROL+C are working on OSX and test itself is not very important considering the way character filtering is implemented now.
> chore: remove a test failing on OSX

- demo/src/app/components/typeahead/demos/http/typeahead-http.html
- demo/src/app/components/typeahead/demos/http/typeahead-http.ts
This wraps the form control into the container to properly render inline
form controls and also replaces span with help small text for activity
status hint.
Before:
After:
Thanks!
> docs(typeahead): refine http example inline layout

- demo/src/app/components/alert/demos/closeable/alert-closeable.ts
- demo/src/app/components/components.e2e-spec.ts
- demo/src/app/components/pagination/demos/disabled/pagination-disabled.ts
- e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.ts
- e2e-app/src/app/dropdown/position/dropdown-position.e2e-spec.ts
- e2e-app/src/app/typeahead/validation/typeahead-validation.e2e-spec.ts
- misc/check-ts.ts
- package.json
- src/buttons/radio.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-month-view.spec.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
- src/dropdown/dropdown.spec.ts
- src/popover/popover.spec.ts
- src/popover/popover.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
- src/typeahead/typeahead-window.spec.ts
- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
- src/util/positioning.spec.ts
- yarn.lock
Adds TS level checking for unused imports as a part of CI
Just adding `noUnusedLocals` to the `tsconfig.json` might be too restrictive during development and ng-packagr doesn't build the library correctly when it is activated.
> chore: add strict unused imports/variables check at TS level

- src/util/scrollbar.ts
Now the actual width of the scrollbar is used to detect if it is present or not, instead of using the wrong hypothesis that if body's rect's width is smaller than viewport's width then there is a scrollbar. Now the difference in width is compared to the width of the scrollbar.
Closes #3448
----
I am sorry I am mixing the fix along with a bit of variables renaming and comments rewriting (but I felt separating commits/PRs would be too cumbersome, and at the same time the code was not self-explanatory enough).
The core of the fix really resides: 
- in `compensate` which now passes the scrollbar width not only to `_adjustBody` but also to `_isPresent`
- and in `_isPresent` which now uses this width to refine widths comparison and more accurately determine if a scrollbar is present or not
> fix(modal): fix scrollbar compensation in some scaling situations

- src/typeahead/highlight.ts
- src/typeahead/typeahead.ts
> feat(typeahead): use readonly arrays for inputs (#2773)

- src/tabset/tabset-config.spec.ts
This minor change make sure test covers all default properties of the
tabset configuration.
This reflect the tests from:
https://github.com/ng-bootstrap/ng-bootstrap/blob/abfe76c5cd7d26673ca7d31c143c9f26e5dc0bb7/src/nav/nav-config.spec.ts
Thanks!
> test(tabset): test oriantation default value

- src/datepicker/datepicker-navigation-select.scss
This change ensures the arrow icon on selects doesn't disappear when it gains focus, issue #3526
> IE11, Edge: This change ensures the arrow icon on selects doesn't disappears on focus

- e2e-app/src/app/modal/autoclose/modal-autoclose.e2e-spec.ts
- e2e-app/src/app/modal/autoclose/modal-autoclose.po.ts
- src/modal/modal-window.ts
Have to use `mousedown` - `mouseup` - `click` to handle closing correctly:
- using `click` fixes the #3518
- using `mousedown` - `mouseup` fixes closing on accidental drags from modal dialog → backdrop
Fixes #3518
> fix(modal): prevent modal from closing when using scrollbar

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.component.html
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.component.ts
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.e2e-spec.ts
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.po.ts
- src/modal/modal-window.ts
At the moment key/mouse handlers are removed when modal triggers dismiss event. The problem is that modal closure could be cancelled with `beforeDismiss` and modal will stay opened, but handlers will be removed.
This commit introduces `closed$` event triggered inside `onDestroy` to clean up handlers.
Fixes #3515
> fix(modal): remove key/mouse handlers only when modal is destroyed

- e2e-app/src/app/tools.po.ts
Some of the components use `requestAnimationFrame()` as a part of keyboard handling.
This might make some tests flaky when doing for example:
```ts
await sendKey(Keys.ESC);
expect(await page.getSomeElement());
```
Expectation in this case might fail or it might not.
So this commit forces tick in the the `sendKeys()` systematically after sending the key.
> test: fix flaky e2e keyboard tests

- src/accordion/accordion.ts
- src/carousel/carousel.ts
- src/modal/modal-backdrop.ts
- src/progressbar/progressbar.ts
- src/rating/rating.ts
- src/tabset/tabset.ts
- src/typeahead/typeahead-window.ts
Previously it was added only to components with custom styles
Fixes #3479
> feat: add `ViewEncapsulation.None` to the rest of components

- demo/src/app/components/datepicker/demos/range/datepicker-range.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.html
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
- demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
This commit changes name of the component custom event to avoid
conflicts with native 'select' event.
Existing event name is marked as deprecated for backward compatibility.
Fixes #3444
Thanks!
> feat(datepicker): change 'select' event to 'dateSelect'

- src/datepicker/datepicker-day-template-context.ts
- src/datepicker/datepicker-month-view.spec.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-tools.ts
> feat(datepicker): add 'currentYear' to the day template

- src/datepicker/datepicker-input-config.spec.ts
- src/datepicker/datepicker-input-config.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
`restoreFocus` input will define re-focusing strategy when closing the input datepicker.
```ts
@Input() restoreFocus: true | string | HTMLElement; // defaults to true
```
By default it re-focuses element focused at the moment of datepicker opening.
Otherwise accepts either selector or element reference.
Fixes #3483
> feat(datepicker): add 'restoreFocus' input

- demo/src/app/components/modal/demos/options/modal-options.ts
- misc/api-doc-test-cases/interface-with-properties.ts
- misc/api-doc.spec.ts
- misc/api-doc.ts
- src/modal/modal-config.ts
- src/modal/modal.spec.ts
Size type now incudes 'string' and changes to `size?: 'sm' | 'lg' | 'xl' | string;`
Main issue was to extract documentation correctly:
Fixes #3013
P.S. Two commits here
> feat(modal): allow any string as modal size option

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
As focusing is asynchronous and unstable in IE it is simpler to disable it
> fix(datepicker): add additional checks for 'restoreFocus' in IE

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/datepicker/datepicker.po.ts
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.component.html
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.component.ts
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.e2e-spec.ts
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.po.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker.ts
> fix(datepicker): focus on multiple instances (#3494)

- demo/src/app/app.component.html
- demo/src/app/app.component.ts
- demo/src/style/app.scss
Adding NPM download stats to the header of demos website.
Code is only retrieving the live count when in production mode.
When in dev mode
When in production mode
> demos: npm downloads count

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/dropdown/click/dropdown-click.component.ts
- e2e-app/src/app/dropdown/click/dropdown-click.e2e-spec.ts
- e2e-app/src/app/dropdown/click/dropdown-click.po.ts
- src/dropdown/dropdown.ts
> fix(dropdown): execute user (click) handlers on Enter and Space

- src/nav/nav.spec.ts
- src/nav/nav.ts
> fix(nav): don't emit '(navChange)' when 'activeId' is not set initially

- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Previously internally calling
```ts
service.minDate = ...;
service.maxDate = ...;
```
resulted in two observable emissions, one per input change.
Now the API is changed to:
```ts
service.set({minDate: ..., maxDate: ...})
```
which results in a single emission for any number of inputs changed at the same time.
Fixes #3545
> fix(datepicker): handle multiple input changes once

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-month-view.ts
> fix(datepicker): handle clicks correctly inside the <label>

- demo/src/app/components/nav/overview/nav-overview.component.html
- src/nav/nav.spec.ts
- src/nav/nav.ts
> fix(nav): allow having falsy values like 0 and 'false' for nav ids

- src/rating/rating.spec.ts
- src/rating/rating.ts
> fix(rating): fixed model change by clicking on disabled rating element

- src/util/autoclose.ts
Couldn't find a better alternative at the moment, autoclose needs rethinking...
Fixes #3582
> fix(tooltip): prevent autoclose with default triggers on Android

- src/accordion/accordion.spec.ts
- src/accordion/accordion.ts
Enable customization of accordion panel conditionally according to being disabled or not.
Fixes #2262
> feat(accordion): add custom class on card level

- src/accordion/accordion.spec.ts
- src/accordion/accordion.ts
Fixes a bug in #3563 
Accordion was generating 'card undefined' class if [cardClass] was not provided
cc @gpolychronis, @benouat
> fix(accordion): don't generate custom 'undefined' class

- DEVELOPER.md
- commitlint.config.js
Currently the `'demo'` is part of the scopes, not types in commit linting.
So if I want to update one of the accordion demos, it is only possible to have commits like:
```
fix(demo): ...
docs(accordion): ...
```
Also `'fix'` commits would end up in release notes.
I would expect to have commits like:
```
demo(accordion): ...
demo(datepicker): ...
```
That would have a demo site as the scope.
WDYT?
> ci: add 'demo' type to commit messages

- src/modal/modal-config.ts
- src/modal/modal-stack.ts
- src/modal/modal.spec.ts
> feat(modal): pass an `HTMLElement` to modal container option (#3584)

- demo/src/app/components/accordion/demos/header/accordion-header.html
- demo/src/app/components/accordion/demos/header/accordion-header.ts
> demo(accordion): add the `[cardClass]` usage example

- src/util/autoclose.ts
Same as #3582, but for the iPadOS 13
Fixes #3591
> fix(tooltip): prevent autoclose with default triggers on iPadOS 13

- demo/src/app/components/tabset/demos/config/tabset-config.ts
- demo/src/app/components/tabset/demos/preventchange/tabset-preventchange.ts
- demo/src/app/components/tabset/tabset-warning.component.ts
- src/index.ts
- src/tabset/tabset-config.spec.ts
- src/tabset/tabset-config.ts
- src/tabset/tabset.module.ts
- src/tabset/tabset.spec.ts
- src/tabset/tabset.ts
`NgbTabset` is deprecated and will no longer be supported. Please use `NgbNav` instead as a more flexible alternative
Demo looks like this:
> docs(tabset): deprecate NgbTabset component

- src/popover/popover.spec.ts
- src/util/popup.ts
Fixes a regression in the popup service after migrating to ivy
Fixes #3602
> fix(popover): make tooltip and popover work on the same element

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
Fixes #2922
BREAKING CHANGE:
'ngbDate' validator error messages were changed to be more explicit and aligned with Angular validators.
For the following use-case `<ngb-datepicker [ngModel]="{year: 2019, month: 12, day: 31}" [minDate]="{year: 2020, month: 1, day: 1}"></ngb-datepicker>` form control errors are:
Before
```
ngbDate: {
requiredBefore: { year: 2020, month: 1, day: 1 }
}
```
After
```
ngbDate: {
minDate: {
minDate: { year: 2020, month: 1, day: 1 },
actual: { year: 2019, month: 12, day: 31 }
}
```
Same change is applied for `requiredAfter` and `maxDate`.
> fix(datepicker): change min/max date error message

- demo/src/app/components/components.e2e-spec.ts
- demo/src/app/tools.po.ts
When the screen height is not large enough, the elements on the left menu need to be scrolled before clicking, otherwise the test fails with 'element not clickable'.
> test: e2e demo tests fail on small screens

- src/dropdown/dropdown.ts
- src/util/positioning.spec.ts
- src/util/positioning.ts
Fixes #3580 and #3640
Adds `overflow:hidden` on dropdown.
Issue affects all derrative components i.e. datepicker upon popup, tooltip, typeahead etc.
CC: @maxokorokov @benouat Please review
> fix(dropdown): ngbDropdown adds vertical scrollbar ... (#3580)

- README.md
- demo/src/app/pages/getting-started/getting-started.component.html
- demo/src/app/pages/getting-started/getting-started.component.ts
As more people are unclear what to do with CSS, here is another update to installation instructions. Based on  https://github.com/ng-bootstrap/ng-bootstrap/issues/2203#issuecomment-450644888
<details>
<summary>Click to see the screenshot</summary>
</details>
But we'd better release updated schematics.
> docs: update installation instructions

- README.md
- demo/src/app/pages/getting-started/getting-started.component.html
- demo/src/app/pages/getting-started/getting-started.component.ts
Updated installation instructions that use schematics by default:
Collapsed section looks like this.
<details>
<summary>Click to see the screenshot</summary>
</details>
There is also a new section called "Alternative Imports". Previously part of installation, now it should be visible, event if detailed instructions are collapsed
P.S. yes, the commit message, should be `docs:`, not `schematics:`
> Schematics installation documentation

- demo/src/app/default/default.component.html
- demo/src/app/default/default.component.ts
I also changed the threshold for responsive switch from `md` to `lg`. Basically the change occurs earlier.
> docs: homepage installation snippet

- demo/src/app/shared/component-wrapper/component-wrapper.component.html
- demo/src/style/app.scss
The issue came form the dimensions of the right menu, not well aligned with other elements. 
The main problem was the bottom of the scrollbar, which was out of the viewport.
> demo: better display of the right menu when the scrollbar is displayed

- demo/src/app/components/alert/demos/closeable/alert-closeable.html
- demo/src/app/components/alert/demos/selfclosing/alert-selfclosing.html
- demo/src/app/components/alert/demos/selfclosing/alert-selfclosing.ts
- src/alert/alert-config.spec.ts
- src/alert/alert-config.ts
- src/alert/alert.spec.ts
- src/alert/alert.ts
- src/environment.test.ts
- src/environment.ts
- src/karma.conf.js
- src/karma.sauce.conf.js
- src/test/common.ts
- src/test/ngb-config-animation.ts
- src/test/test-styles.css
- src/util/transition/ngbFadingTransition.ts
- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
- src/util/transition/util.spec.ts
- src/util/transition/util.ts
This is completely based on cherry-picked #2817. It contains extracted alert animations and initial version of the `ngbRunTransition`
What is does on top in 3 separate commits is:
- refactors `ngbRunTransition` leaving only what is necessary for alert
- adds unit tests for `ngbRunTransition` with full coverage
- adds unit tests for alert animations with full coverage
Alert animations API at the moment is:
```html
<ngb-alert #a #ngIf="closed" (close)="closed = true"></ngb-alert>
<button (click)="a.close()">Close</button>
```
Unclear points for me are:
cc @fbasso, @benouat 
P.S. Coverage:
> Alert animations

- commitlint.config.js
- demo/src/app/components/collapse/demos/basic/collapse-basic.html
- src/collapse/collapse.spec.ts
- src/collapse/collapse.ts
- src/test/test-styles.css
- src/util/transition/ngbCollapseTransition.ts
- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
- src/util/util.ts
Again the collapsing implementation is cherry-picked and is based on #2817.
This contains several commits (**please review in the historical order with whitespaces/lines diff turned off for simplicity**):
- a bugfix for duration calculation
- add `endFn()` along with `startFn()` for transition
- support transition reverting with `runningTransition: stop`
- introduction of transition context to store parameters and data
- finally cherry-picked collapsed implementation and tests
Changes to the original PR are:
- end function has no arguments and simply using a closure (see these tests to get the idea of how it works → https://github.com/ng-bootstrap/ng-bootstrap/pull/3727/commits/5a8bebd0d3f2244b17da51f0fcd3b32a4d6b0723#diff-ec1addfdfcf53282cbf22a4f924fad6bR206-R264)
- using a transaction …
> Collapse animations

- src/collapse/collapse-config.spec.ts
- src/collapse/collapse-config.ts
- src/collapse/collapse.module.ts
- src/collapse/collapse.ts
- src/index.ts
We didn't have `NgbCollapseConfig` before and were using `NgbConfig` directly
> feat(collapse): add 'NgbCollapseConfig'

- demo/src/app/components/table/demos/pagination/table-pagination.html
- demo/src/app/components/table/demos/pagination/table-pagination.ts
The pagination example re-created the array of countries to display at each change detection, which is not only a performance problem, but also causes problems if popovers or tooltips are used inside the table for example.
fix #3675
> demo(table): avoid re-creation of array at each change detection

- demo/src/app/components/toast/demos/closeable/toast-closeable.html
- demo/src/app/components/toast/demos/closeable/toast-closeable.ts
- demo/src/app/components/toast/demos/custom-header/toast-custom-header.html
- demo/src/app/components/toast/demos/custom-header/toast-custom-header.ts
- demo/src/app/components/toast/demos/howto-global/toasts-container.component.ts
- demo/src/app/components/toast/demos/inline/toast-inline.html
- demo/src/app/components/toast/demos/inline/toast-inline.ts
- src/alert/alert.spec.ts
- src/toast/toast-config.spec.ts
- src/toast/toast-config.ts
- src/toast/toast.scss
- src/toast/toast.spec.ts
- src/toast/toast.ts
- src/util/transition/ngbFadingTransition.ts
- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
Inspired by #2817, not cherry-picked because the toast animations are finally quite different compared to the alert.
This PR has 3 commits:
- toast animations implementation
- fix some test, due to a change on ngbTransition (the startFn function and its optional callback are now run even if animation = false)
- The changes in the demo examples
The toast animations are defined as follow:
- The `fade` class exists only when the animations are defined,
- When visible, the toast contains the class `show`,
- When not visible, the toast contains the class `hide` (if, for any reason, the developer choose to keep the toast in the dom),
- When closing, the `show` class is removed to start the transition, then the `hide` class is added once finished,
- When opening, the `hide` class is removed, the …
> Toast animations

- e2e-app/src/app/app.component.ts
- src/modal/modal-backdrop.spec.ts
- src/modal/modal-backdrop.ts
- src/modal/modal-config.spec.ts
- src/modal/modal-config.ts
- src/modal/modal-ref.ts
- src/modal/modal-stack.ts
- src/modal/modal-window.ts
- src/modal/modal.spec.ts
- src/test/test-styles.css
- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
Again this is inspired by #2817, not cherry-picked though, because there were several issues with the implementation.
This PR has 3 commits:
- fix for nested `transitionend` events in `ngbRunTransition` with tests
- disabling of animations for e2e tests
- modal animations implementation
Key implementation points are:
- fade in animation starts on `modal.open()` and is reversible.
- fade out animation starts when modal is closed/dismissed and is not reversible.
- modal is focused at the same time as fade in animation starts
- focus is restored and all modal key/mouse event handling is disabled as soon as fade out animation starts
- had to refactor `modal-window.ts` quite a lot... :/
- a new API to notify when animation is finished
```ts
const modalRef = modal.open(content); …
```
> Modal animations

- demo/src/environments/versions.ts
- package.json
- yarn.lock
Internet Explorer ES5 build was broken because of the introduction of `semver` dependency.
It was wrongly bundled as ESM inside the ES5 bundle which was obviously causing IE to crash.
I move back to string manipulation, but did not revert the commit, to actually take into consideration any eventual Bootstrap rc usage.
Previously, we were using (broken with alpha/beta/rc pattern)
```typescript
bootstrap = bootstrap.substr(0, bootstrap.lastIndexOf('.'));
```
Now I used
```typescript
bootstrap = bootstrap.split('.').slice(0, 2).join('.');
```
Fixes #3751
> demo: removed unnecessary semver dep

- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
Fixes an issue when the context was not passed across two transitions when `animation = false` (see test for the example)
> fix(animations): pass transition context with animation disabled

- src/collapse/collapse.spec.ts
- src/collapse/collapse.ts
- src/util/transition/ngbTransition.ts
This is a refactor of ngbTransition to fix an issue around the transition detection.
The main problem comes from the order startFn is run and the transition computed style.
It's easier to explain the issue with the collapse widget:
What Bootstrap do :
- The transition is set on the `collapsing` class,
- When reduce motion is activated, Bootstrap set this transition to none.
Before this PR :
- We get the transition value for mthe element computed style,
- if this transition is `none`, we consider that there is no animation and we run the startFn  an endFn synchronously.
This is wrong, as it's the startFn purpose is to change collapse to collapsing, we can't compute the `transition` property of `collapsing` before running it.
What this PR do:
- Always run startFn 
- If no animation (via the …
> feat(animations): refactor ngbTransition

- src/modal/modal-window.ts
- src/modal/modal.spec.ts
fix #3768
Note: this is my first PR on animations, and I don't really master everything. 
There are 3 points that I'm not sure about in the submitted code:
- should I pass 'continue' or 'stop'. I chose 'continue', and it seems to behave correctly, and the same way as the native bootstrap modal, but maybe I'm missing something
- in the unit tests, I don't know how to test that the `modal-static` class disappears at the end of the transition: nothing is emitted when that happens, and I didn't want to introduce an output only useful for tests. (see TODO in the test)
- I'm not sure exactly what the `reduceMotion` flag is supposed to do. I have noticed that the `modal-static` is not added when `reduceMotion` is true, and I guess it's a feature, but I'm not sure. (see TODO in the test)
> feat(modal): add scale animation when static backdrop is clicked

- src/popover/popover-config.spec.ts
- src/popover/popover-config.ts
- src/popover/popover.spec.ts
- src/popover/popover.ts
- src/tooltip/tooltip.ts
- src/typeahead/typeahead.ts
- src/util/popup.ts
Again this is cherry-picked and fixed/adapted from #2817.
The popover API is the same as before:
```html
<div ngbPopover="Look at me!" (shown)="..." (hidden)="..."></div>
```
`(shown)` and `(hidden)` emit synchronously as before in case of reduced motion or no animations
Will open the same thing for the tooltip once this is merged
> Popover animations

- src/index.ts
- src/nav/nav-config.spec.ts
- src/nav/nav-config.ts
- src/nav/nav-outlet.ts
- src/nav/nav.module.ts
- src/nav/nav.spec.ts
- src/nav/nav.ts
- src/util/transition/ngbFadingTransition.ts
Again this is inspired by #2817, not cherry-picked though, because there were several issues with the implementation.
Contains 2 main changes:
- a bugfix in `ngbRunTransition` so it would still pass context even if animations are disabled
- nav animations implementation
- `NgbNav` notifies `NgbNavOutlet` when the active item was changed via `(click)`, `[activeId]` or `.select()`
- `NgbNavOutlet` manages the stream of these `navItemChange` events and handles fade in/out transitions on `NgbNavPanes`
- new additional `(shown)` and `(hidden)` outputs both at `NgbNavItem` and at `NgbNav` level:
```html
<ul ngbNav #n="ngbNav" class="nav-tabs" (shown)="..." (hidden)="...">
<li ngbNavItem (shown)="..." (hidden)="...">
<a ngbNavLink>link</a>
<ng-template ngbNavContent>content</ng-template>
</li> …
```
> Nav animations

- src/test/test-styles.css
- src/tooltip/tooltip-config.spec.ts
- src/tooltip/tooltip-config.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
Same as popover in #3792, but for the tooltip
Again this is cherry-picked and fixed/adapted from #2817.
The popover API is the same as before:
<div ngbPopover="Look at me!" (shown)="..." (hidden)="..."></div>
(shown) and (hidden) emit synchronously as before in case of reduced motion or no animations
Will open the same thing for the tooltip once this is merged
> Tooltip animations

- demo/src/app/components/dropdown/demos/navbar/dropdown-navbar.html
- demo/src/style/app.scss
Bootstrap automatically sets the cursor to pointer when the element has role button.
But links without href are not tabbable by default, which makes them keyboard-inaccessible if tabindex is not set
> fix(demo): remove cursor, add tabindex on navbar dropdown toggles

- README.md
- demo/src/app/components/toast/overview/toast-overview.component.html
- demo/src/app/components/toast/overview/toast-overview.component.ts
- demo/src/app/components/toast/toast.module.ts
- demo/src/app/pages/getting-started/getting-started.component.html
- demo/src/app/pages/getting-started/getting-started.component.ts
Contains two commits:
- first one fixes places in the documentation where Bootstrap version was hardcoded
- second bumps Angular to 10 and Bootstrap to 4.5 in the docs
> Update Angular and Bootstrap versions in the docs for 7.0

- e2e-app/src/app/dropdown/focus/dropdown-focus.e2e-spec.ts
- src/dropdown/dropdown.ts
- src/util/autoclose.ts
- src/util/focus-trap.ts
This PR is a follow up PR to #3625 which introduced the ability to close the dropdown when leaving it by the last elements.
Unfortunately, it did not fix the keyboard navigation when using `container="body"` is used.
Leaving the dropdown menu from the bottom when container is set to "body" leaves the user in a broken state, where the browser window url bar gets the focus.
The PR introduces a mechanism to _catch_ the last <kbd>Tab</kbd> from the dropdown menu, and temporary set the focus back in a synchronous fashion to the dropdown anchor, hence letting the browser placing the focus on the next focusable element.
It also makes sure now that whenever the user wants to close the dropdown from the keyboard with <kbd>Esc</kbd>, the focus gets back to the dropdown toggle element.
This used to …
> fix(dropdown): container body keyboard navigation

- src/util/util.spec.ts
- src/util/util.ts
When autoclosing a dropdown by clicking the scrollbar, an error would be
thrown in Edge 44.18362.449.0. This was due to the HTMLDocument not
supporting `Element.prototype.closest`.
By emulating `Element.prototype.closest` for this specific node, this
commit circumvents the issue.
> fix(dropdown): support closest for HTMLDocument (#3783)

- src/dropdown/dropdown.spec.ts
- src/dropdown/dropdown.ts
Closes #3331
To remove aria-haspop from the dropdown component to allow the component to
be read by screen reader like NVDA/JAWS. To make the dropdown component
more accessible
BREAKING CHANGE: None
- [] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
- [] built and tested the changes locally.
> fix(dropdown): remove aria-haspop for accessibility

- demo/src/app/components/carousel/demos/pause/carousel-pause.html
- demo/src/app/components/carousel/demos/pause/carousel-pause.ts
- src/carousel/carousel-config.ts
- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
This PR adds accessibility to the carousel:
- the carousel is now automatically paused when the focus is inside it (this can be controlled with the `pauseOnFocus` property)
- some roles and aria attributes are added to make it easier to use the carousel with a screen reader. This mostly relies on the carousel indicators that act like tabs.
In the future, it would be nice to integrate [assistive-webdriver](https://github.com/AmadeusITGroup/Assistive-Webdriver) to execute end-to-end tests with a screen reader.
Fixes #3755
> feat(carousel): accessibility

- src/carousel/carousel-config.spec.ts
- src/carousel/carousel-config.ts
- src/carousel/carousel-transition.ts
- src/carousel/carousel.module.ts
- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
- src/test/test-styles.css
Cherry-picked form #2817, then simplified and adapted to be aligned with recent widget development.
To be noticed:
- The `slid` event has been added (when the transition finish),
- The revert can be done only if the previous slide is selected.
> feat(carousel): add animations

- src/accordion/accordion-config.spec.ts
- src/accordion/accordion-config.ts
- src/accordion/accordion.spec.ts
- src/accordion/accordion.ts
Cherry picked from #2817, with some changes.
The key points are:
- Animations are managed one panel at a time, in the original code, a loop was done on all panels to guess if an animation is required, for each panel. The code is simpler this way, and aligned with ngbTransition API,
- ngbCollapseChange event  have been added. It follows the collapse widget, to discuss if the name/API must be changed,
- A little change in ngbTransition has been required, to provide the context when animations are deactivated,
- Tests have been done the same way the collpase widget,
- Some `detectChanges` have been added in the previous tests, because of the `changeDetector.detectChanges()` required in `_runTransition`,
- Only one commit in this PR, as there are only a few impacted files.
> feat(accordion): add animations

- src/util/transition/ngbCollapseTransition.ts
Fixes an issue where collapsing transition is not compatible with SSR when launched from component lifecycle methods like `onInit`:
```
ERROR TypeError: element.getBoundingClientRect is not a function
[express]     at measureCollapsingElementHeightPx (/Users/mokorokov/Dev/Angular/core/ssr-app/dist/server/main.js:1557:28)
[express]     at ngbCollapsingTransition (/Users/mokorokov/Dev/Angular/core/ssr-app/dist/server/main.js:1568:21)
[express]     at ngbRunTransition (/Users/mokorokov/Dev/Angular/core/ssr-app/dist/server/main.js:1519:19)
[express]     at NgbCollapse._runTransition (/Users/mokorokov/Dev/Angular/core/ssr-app/dist/server/main.js:3027:9)
[express]     at NgbCollapse.ngOnInit (/Users/mokorokov/Dev/Angular/core/ssr-app/dist/server/main.js:3008:14)
```
> fix(animations): make collapsing transition work with SSR

- src/rating/rating.ts
A tiny simplification to the existing `_getFillValue` in the rating:
* we've got already a utility to trim numbers to a given range so let's use it
* we can round numbers without converting them to a string :-)
> refactor(rating): simplify _getFillValue implementation

- src/datepicker/datepicker-month.spec.ts
- src/datepicker/datepicker.ts
BREAKING CHANGE: datepicker `(select)` output  deprecated in 6.0.0 is now removed
Before:
```
<ngb-datepicker (select)="inDateSelect($event)"></ngb-datepicker>
```
After:
```
<ngb-datepicker (dateSelect)="inDateSelect($event)"></ngb-datepicker>
```
> feat(datepicker): remove deprecated 'select' output

- src/alert/alert.spec.ts
- src/buttons/radio.spec.ts
- src/datepicker/datepicker.spec.ts
- src/modal/modal.spec.ts
- src/rating/rating.spec.ts
- src/timepicker/timepicker.spec.ts
- src/toast/toast.spec.ts
- src/typeahead/typeahead.spec.ts
This addresses the `async` function deprecation introduced in `Angular 10`:
```
WARNING: 65:53     deprecation  async is deprecated: use `waitForAsync()`, (expected removal in v12)
```
Went through all unit tests and used `fakeAsync` where possible instead.
> test: don't use deprecated 'async' function

- src/nav/nav-outlet.ts
- src/nav/nav.spec.ts
- src/nav/nav.ts
Fixes a regression in 8.0.0 after the introduction of animations.
Also adds a forgotten subscription cleanup in the nav outlet.
Fixes #3892
cc @fbasso
> fix(nav): correctly work with conditional nav items

- src/typeahead/typeahead.spec.ts
`<input autocapitalize />` attribute accepts either 'off' or 'none'.
https://html.spec.whatwg.org/multipage/interaction.html#autocap-hint-none
Fixes #3912
> test(typeahead): fix test failing in FF 83

- src/buttons/checkbox.ts
- src/buttons/radio.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-month.spec.ts
- src/datepicker/datepicker.ts
- src/rating/rating.ts
- src/timepicker/timepicker.ts
- src/typeahead/typeahead.ts
To fix dead code elimination in Angular 11.
See https://github.com/angular/angular-cli/issues/19572#issuecomment-741017976 for more details. The *inline* option was chosen as ng-bootstrap does not need to export these providers and they're only used by a single component. This option appears the simplest to me, it is less likely to regress in the future and should work independently of whether consumer uses Angular CLI or custom tooling to build their application. At the cost of slightly worse code readability.
Fixes #3904
Not sure how to add a test for size regressions. Any suggestions?
So far tested manually on the reproduction from the issue and it results in 3.3K according to source-map-explorer.
Before submitting a pull request, please make sure you have at least performed the …
> refactor: inline providers with forwardRef()

- src/util/popup.ts
Forcing to run ngbRunTransition inside angular zone, because NgZone.onStable is called outside angular zone.
closes #3896
> fix(popover,tooltip): run transaction inside angular zone

- demo/src/app/components/shared/api-docs/api-docs-class.component.html
- demo/src/app/components/shared/api-docs/api-docs-config.component.html
- [ x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
- [ x] built and tested the changes locally.
- [x ] added/updated any applicable demos.
> demo: removed redundant class 'title-fragment' for api-docs titles

- src/datepicker/datepicker-navigation.scss
Now using `ngb-dp-arrow.right .ngb-dp-navigation-chevron` instead of `.right .ngb-dp-navigation-chevron`.
Fixes #3872
> fix(datepicker): improve right arrow css selector

- src/nav/nav-outlet.ts
A regression introduced with animations.
We already have all tests in place that cover the use case in the issue if we mark `ngbNavOutlet` with `OnPush` itself.
Fixes #3930
> fix(nav): work corretly inside components with OnPush

- src/nav/nav-outlet.ts
- src/nav/nav-transition.ts
- src/nav/nav.spec.ts
Double reflow issue caused styles + layout calculation with tab pane hidden (without `.active`).
This caused window scroll positition adjustment as if tab pane wasn't there.
```
Before:
- reflow() in ngbRunTransition
- add('.active') in ngbNavFadeInTransition
- reflow() in ngbNavFadeInTransition
- add('.show') in ngbNavFadeInTransition
After:
- add('.active') in NgbNavOutlet
- reflow() in ngbRunTransition
- add('.show') in ngbNavFadeInTransition
```
P.S. No idea how to add tests for this...
Fixes #3900
> fix(nav): avoid doing double reflow for fade in transition

- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
- src/test/test-styles.css
- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
fix #3911 
This fix force the (missing) active class on the active slide, when the content has changed. Any running transition is stopped, but trying to keep all the current classes (to try to continue the transition with the new content) produces some strange behaviors.
> fix(carousel): update active class when the content changes

- demo/src/app/app.routing.ts
- src/accordion/accordion-config.ts
- src/alert/alert-config.ts
- src/carousel/carousel-config.ts
- src/collapse/collapse-config.ts
- src/collapse/collapse.ts
- src/modal/modal-config.ts
- src/modal/modal.ts
- src/nav/nav-config.ts
- src/ngb-config.spec.ts
- src/popover/popover-config.ts
- src/toast/toast-config.ts
- src/tooltip/tooltip-config.ts
Component configs now delegate the `animation` flag to `NgbConfig` if it is not set explicitly.
Fixes #3893
> fix(animations): delegate 'animation' flag to 'NgbConfig'

- angular.json
- demo/tsconfig.json
- e2e-app/tsconfig.json
- src/.browserslistrc
- ssr-app/tsconfig.json
- downgrade target to `es2015`
- adjust ng-bootstrap `.browserslistrc`
- clean up deprecated flag
> Minor build fixes for v9

- README.md
- demo/src/app/pages/getting-started/getting-started.component.html
> docs: bump version requirements for ng-bootstrap 9.0.0

- src/accordion/accordion.ts
- src/carousel/carousel-transition.ts
- src/collapse/collapse.ts
- src/modal/modal-backdrop.ts
- src/modal/modal-window.ts
- src/nav/nav-transition.ts
- src/toast/toast-transition.ts
- src/util/transition/ngbCollapseTransition.ts
- src/util/transition/ngbTransition.spec.ts
- src/util/transition/ngbTransition.ts
Replace a generic `reflow()` call in `ngbRunTransition`:
- introduce granular per-component reflows only when necessary
- take into account `animation` flag for reflows
Fixes #3954
Fixes #3952
> fix(animations): don't reflow in 'ngbRunTransition'

- .travis.yml
- angular.json
- e2e-app/setup.pw-spec.ts
- e2e-app/src/app/tools.pw-po.ts
- e2e-app/tsconfig.json
- package.json
- playwright/controller.ts
- use `--prod` for e2e-app build when running e2e tests
- extract coverage only from chromium (no point in doing it for all browsers)
- reload the page properly between each test (fixes webkit issues)
> Use production build for Playwright tests

- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.pw-spec.ts
- e2e-app/src/app/datepicker/focus/datepicker-focus.pw-spec.ts
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.component.html
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.pw-spec.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.pw-spec.ts
- e2e-app/src/app/dropdown/click/dropdown-click.component.ts
- e2e-app/src/app/dropdown/click/dropdown-click.pw-spec.ts
- e2e-app/src/app/dropdown/focus/dropdown-focus.pw-spec.ts
- e2e-app/src/app/dropdown/position/dropdown-position.pw-spec.ts
- e2e-app/src/app/popover/autoclose/popover-autoclose.pw-spec.ts
- e2e-app/src/app/timepicker/filter/timepicker-filter.pw-spec.ts
- e2e-app/src/app/timepicker/navigation/timepicker-navigation.pw-spec.ts
- e2e-app/src/app/tools.pw-po.ts
- e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.pw-spec.ts
- e2e-app/src/app/tooltip/focus/tooltip-focus.pw-spec.ts
- e2e-app/src/app/tooltip/position/tooltip-position.pw-spec.ts
- e2e-app/src/app/tooltip/tooltip.ts
- e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.pw-spec.ts
- e2e-app/src/app/typeahead/focus/typeahead-focus.component.html
- e2e-app/src/app/typeahead/focus/typeahead-focus.pw-spec.ts
- e2e-app/src/app/typeahead/validation/typeahead-validation.component.html
- e2e-app/src/app/typeahead/validation/typeahead-validation.pw-spec.ts
- removed redundant checks around `waitForSelector`
- added waiting for explicit conditions before each test, ex `await test.page.waitForSelector('h3:text("Datepicker autoclose")');` to ensure the page is actually loaded
> Playwright waitForSelector refactoring

- e2e-app/setup.pw-spec.ts
- e2e-app/src/app/datepicker/focus/datepicker-focus.pw-spec.ts
- e2e-app/src/app/datepicker/multiple/datepicker-multiple.pw-spec.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.pw-spec.ts
- e2e-app/src/app/dropdown/click/dropdown-click.pw-spec.ts
- e2e-app/src/app/dropdown/focus/dropdown-focus.pw-spec.ts
- e2e-app/src/app/timepicker/navigation/timepicker-navigation.pw-spec.ts
- e2e-app/src/app/tools.pw-po.ts
- e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.pw-spec.ts
- e2e-app/src/app/typeahead/focus/typeahead-focus.pw-spec.ts
The purpose is to render the tests more stable with all the browsers
> test: waitForFocus instead of expectFocused

- e2e-app/playwright.conf.ts
- e2e-app/src/app/dropdown/position/dropdown-position.pw-spec.ts
- e2e-app/src/app/modal/autoclose/modal-autoclose.pw-spec.ts
- e2e-app/src/app/modal/autoclose/modal-autoclose.ts
- e2e-app/src/app/modal/focus/modal-focus.pw-spec.ts
- e2e-app/src/app/modal/focus/modal-focus.ts
- e2e-app/src/app/modal/modal.ts
- e2e-app/src/app/modal/nesting/modal-nesting.pw-spec.ts
- e2e-app/src/app/modal/nesting/modal-nesting.ts
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.component.html
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.pw-spec.ts
- e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.ts
- e2e-app/src/app/modal/stack/modal-stack.component.html
- e2e-app/src/app/modal/stack/modal-stack.pw-spec.ts
- e2e-app/src/app/modal/stack/modal-stack.ts
- e2e-app/src/app/tools.pw-po.ts
- e2e-app/src/app/tooltip/focus/tooltip-focus.pw-spec.ts
- e2e-app/src/app/typeahead/focus/typeahead-focus.pw-spec.ts
- package.json
- yarn.lock
Enable Playwright tests for the modal.
I still have an issue locally with FF and webkit:
- from time to time, a modal backdrop stay in the dom, so the remaining tests fail,
- It happens only with when some specs files are run together (including the modal ones of course),
- It never happens on Chrome,
- The more difficult, it's random (sometime it passes).
Let's see if there is the same issue on Travis.
> test(modal): migrate e2e tests to Playwright

- src/datepicker/datepicker-i18n.ts
- src/datepicker/datepicker-integration.spec.ts
- src/datepicker/datepicker.module.ts
- src/datepicker/datepicker.ts
- src/index.ts
- introduces a new `getMonthLabel(date: NgbDateStruct): string` method to datepicker i18n
- makes default i18n datepicker implementation accessible publicly
Fixes #3863
> feat(datepicker): allow overriding month label correctly

- demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.ts
- demo/src/app/components/datepicker/demos/islamiccivil/datepicker-islamiccivil.ts
- demo/src/app/components/datepicker/demos/islamicumalqura/datepicker-islamicumalqura.ts
- demo/src/app/components/datepicker/demos/jalali/datepicker-jalali.ts
- demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
- src/datepicker/datepicker-config.ts
- src/datepicker/datepicker-day-view.spec.ts
- src/datepicker/datepicker-i18n.spec.ts
- src/datepicker/datepicker-i18n.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker-month.spec.ts
- src/datepicker/datepicker-month.ts
- src/datepicker/datepicker-service.spec.ts
- src/datepicker/datepicker-service.ts
- src/datepicker/datepicker-tools.spec.ts
- src/datepicker/datepicker-tools.ts
- src/datepicker/datepicker-view-model.ts
- src/datepicker/datepicker-weekday-format.ts
- src/datepicker/datepicker.module.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
- src/datepicker/hebrew/datepicker-i18n-hebrew.spec.ts
- src/datepicker/hebrew/datepicker-i18n-hebrew.ts
- src/index.ts
- reverts the #3803, because of breaking changes and different API
- introduces new `@Input() weekday: boolean | TranslationWidth` in `NgbDatepicker` and `NgbInputDatepicker`
- introduces new `getWeekdayLabel(date, width)` in `NgbDatepickerI18n`
Fixes #2516
> feat(datepicker): allow configuring weekday format

- demo/src/app/components/typeahead/demos/basic/typeahead-basic.ts
- demo/src/app/components/typeahead/demos/focus/typeahead-focus.ts
- demo/src/app/components/typeahead/demos/format/typeahead-format.ts
- demo/src/app/components/typeahead/demos/http/typeahead-http.ts
- demo/src/app/components/typeahead/demos/prevent-manual-entry/typeahead-prevent-manual-entry.ts
- demo/src/app/components/typeahead/demos/template/typeahead-template.ts
- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
Improves "search" function typings by using standard rxjs `OperatorFunction` type and making search function optional
```ts
// before
@Input() ngbTypeahead: (text: Observable<string>) => Observable<readonly any[]>;
// after
@Input() ngbTypeahead: OperatorFunction<string, readonly any[]>| null | undefined;
```
Fixes #3907
> fix(typeahead): improve 'ngbTypeahead' typings

- src/util/util.ts
This is caused by the Terser `pure_getters` optimization.
If used only once (ex. when importing ONLY `NgbCollapseModule`), the `reflow` function is broken:
```ts
// source
export function reflow(element: HTMLElement) {
return (element || document.body).offsetHeight;
}
reflow(el);
// inlined in production
function(element) {
element || document
}(element)
```
Fixes #3972
> fix(collapse): no animations in production mode

- src/typeahead/typeahead-window.ts
- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
This PR enables providing one or more custom classes to the typeahead window. It's intended to help solve #3778 as per [my comment](https://github.com/ng-bootstrap/ng-bootstrap/issues/3778#issuecomment-759833406).
I modeled the behavior and implementation after `windowClass` from `NgbModal`.The main intent here is allowing users to provide a custom `z-index` value along with the `container="body"` option for their specific needs. But ultimately, it can be used to override any attributes on the `ngb-typeahead-window`.
I did not feel we needed to update the demo, but I would be happy to do so if needed.
> feat(typeahead): allow custom class on window for modal issue

- demo/src/app/components/modal/demos/component/modal-component.html
- demo/src/app/components/modal/demos/component/modal-component.module.ts
entryComponents is not needed anymore since Angular 9.
fix #3722
> demo(modal): improve explanations on entryComponents

- src/popover/popover.scss
- src/tooltip/tooltip.scss
This fixes #3997. I was able to reproduce the problem in the issue manually with tooltips and popovers on the demo site in Chrome, but writing automated tests for it would not be straightforward. It could be possible with a test that simulates moving the mouse slowly on top of a tooltip/popover, but I'm not sure if that's worth the effort.
I did verify that if I completely disable pointer events from these elements (i.e. omit the `"pointer-events: auto;"` definitions), several "Tooltip Autoclose" and "Popover Autoclose" e2e tests fail. So at least the existing tests verify that these changes don't cause regressions in those scenarios.
> fix(tooltip/popover): enable pointer events only for tooltip/popover content

- src/accordion/accordion.ts
The issue comes from the accordion-body, which is defined on the root element where the body template is generated. (the class accordion-body has a padding).
The Bootstrap 5 markup requires a second container, as [in this documentation](https://getbootstrap.com/docs/5.0/components/accordion/#example). (It was the case in the main branch, I don't know why I removed this level 😕).
> fix(accordion): broken collapse animation

- src/datepicker/datepicker-navigation.ts
Following the fix done with #4023, `i18n.getMonthLabel` is now also used in the navigation section.
> fix(datepicker): forgotten fix for #3863

- src/popover/popover.scss
fix #4103.
This PR reverts partially the PR #4076 which fixed #3997 (the fix on the tooltip has been kept for now). A unified solution needs to be found.
> Re-enable the pointer events on popover

- demo/src/app/components/accordion/demos/header/accordion-header.html
- demo/src/app/components/accordion/demos/header/accordion-header.ts
The demo was broken because of missing `.accordion-button` class when doing custom headers
https://user-images.githubusercontent.com/8074436/124276798-8fb20600-db44-11eb-87ae-ef595e263f6f.mp4
https://user-images.githubusercontent.com/8074436/124276823-98a2d780-db44-11eb-8770-c20387eda87c.mp4
> demo(accordion): fix custom header demo

- e2e-app/coverage.webpack.js
- e2e-app/removeLangSelector.js
- e2e-app/setup.e2e-spec.ts
Reverts commit a8b2575ceadca25f8b6c3c1b07f50e4cabf49e87 and adds a webpack loader to remove from bootstrap during the e2e-app build the `:lang(en)` selector that causes the warning.
> build: re-enable console warning reporting in e2e tests

- demo/src/app/components/alert/demos/custom/alert-custom.ts
This removes warning from thewq: build output:
```txt
Warning:  > .../ng-bootstrap/demo/src/app/components/alert/demos/custom/alert-custom.ts-angular-inline--4.css:2:11:
warning: Unexpected ">"
2 │     :host >>> .alert-custom {
```
Thanks!
> demo(alert): drop deep css selector

- demo/src/style/app.scss
Before this PR:
After this PR:
Now, horizontal and vertical padding is more consistent.
> demo: removing custom padding in overview alerts

- src/modal/modal-backdrop.ts
> fix(modal): upgrade z-index for backdrop

- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
- In Bootstrap 5 the CSS selector matching indicators has changed and included `data-bs-target` attribute that we were missing
- Recommended carousel markup changed from using `ul`, `li` and `a` to using `button` elements
- Had to refactor tests as selectors were not precise enough
On Bootstrap side see:
- https://github.com/twbs/bootstrap/pull/32661
- https://github.com/twbs/bootstrap/pull/32627
Fixes #4200
Fixes #4253
> fix(carousel): fix hidden carousel indicators

- e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.e2e-spec.ts
- e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
- src/datepicker/datepicker-input.ts
- src/dropdown/dropdown.ts
Closes #4219 
I added the feature to datepicker as well as dropdown because it's equally applicable there. popover, tooltip and typeahead also use autoClose but I can't imagine any use case for this feature in a non-interactive component.
> fix: dropdown and datepicker respond to autoClose input changes

- src/modal/modal-config.ts
> fix(modal): allows to set an HTMLElement as container in NgbModalConfig

- e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
It looks like this test sometimes fails on webkit because of a timeout that is too small.
(cf for example https://github.com/ng-bootstrap/ng-bootstrap/actions/runs/1910949270)
> fix(test): increase timeout in datepicker-focus.e2e-spec (especially for webkit)

- demo/src/app/components/buttons/buttons-warning.component.ts
- demo/src/app/components/buttons/buttons.module.ts
- demo/src/app/components/buttons/overview/buttons-overview.component.html
- demo/src/app/components/buttons/overview/buttons-overview.component.ts
- src/buttons/buttons.module.ts
- src/buttons/checkbox.spec.ts
- src/buttons/checkbox.ts
- src/buttons/label.ts
- src/buttons/radio.spec.ts
- src/buttons/radio.ts
- src/index.ts
We forgot to do it properly for the 12.0.0
In Bootstrap 5 CSS there is no more need it button directives, everything can be handled with pure Angular.
This change:
- adds the 'overview' page detailing changes between Bootstrap 4 and 5
- marks button directives as deprecated
Fixes #4257
---
<details>
<summary>
Overview page looks like this:
</summary>
</details>
> docs(buttons): mark button directives as deprecated

- demo/src/app/components/toast/demos/howto-global/toast-global.component.ts
- demo/src/app/components/toast/demos/howto-global/toast-service.ts
This avoids the toasts to reappear when leaving the demo page while toasts are open and then coming back.
> demo(toast): clear toasts from the service when the demo is destroyed

- demo/playwright.config.ts
- e2e-app/playwright.config.ts
- package.json
- ssr-app/playwright.config.ts
- yarn.lock
As discussed in [#4269](https://github.com/ng-bootstrap/ng-bootstrap/pull/4269#issuecomment-1057124826), I am opening this PR to enable the new [fullyParallel](https://playwright.dev/docs/api/class-testconfig#test-config-fully-parallel) option in playwright tests.
> test: update playwright and enable fullyParallel

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
Delaying setting focus until after the popup is positioned with popper.
Fixes #4290
> fix(datepicker): do not scroll when opening with container='body'

- src/modal/modal-stack.ts
- src/modal/modal.spec.ts
Twitch was caused by removing classes/styles from the `<body>` too early after `result` promise was resolved, but animation was potentially on-going.
Now the cleanup is done only after BOTH `result` promise is resolved and `(hidden)` event was emitted on animation completion.
Fixes #4293
> fix(modal): remove visual 'twitch' when closing

- e2e-app/src/app/app.module.ts
- e2e-app/src/app/app.routing.ts
- e2e-app/src/app/datepicker/container/datepicker-container.component.html
- e2e-app/src/app/datepicker/container/datepicker-container.component.ts
- e2e-app/src/app/datepicker/container/datepicker-container.e2e-spec.ts
- e2e-app/src/app/datepicker/container/datepicker-container.po.ts
- src/datepicker/datepicker.scss
When using container="body", the datepicker's `z-index` must be equal
or above the modal window's one (as defined in `modal.scss`).
Fixes #4278
- [n/a] added/updated any applicable API documentation.
- [n/a] added/updated any applicable demos.
> fix(datepicker): ensure popup is shown above modal

- src/test/test-styles.css
Reduces animation timing for offcanvas tests.
@jnizet FYI, I've also completely forgot about `reduce-motion` in tests as well as animation timing.
> test(offcanvas): fix animation timings for tests

- demo/src/app/components/popover/demos/config/popover-config.ts
- src/datepicker/datepicker-input-config.spec.ts
- src/datepicker/datepicker-input-config.ts
- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/dropdown/dropdown-config.spec.ts
- src/dropdown/dropdown-config.ts
- src/dropdown/dropdown.spec.ts
- src/dropdown/dropdown.ts
- src/popover/popover-config.spec.ts
- src/popover/popover-config.ts
- src/popover/popover.spec.ts
- src/popover/popover.ts
- src/tooltip/tooltip-config.spec.ts
- src/tooltip/tooltip-config.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
- src/typeahead/typeahead-config.spec.ts
- src/typeahead/typeahead-config.ts
- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
- src/util/positioning-util.ts
- src/util/positioning.spec.ts
First draft about how to give access to the popper options.
> feat(positionning): open popperOptions api

- src/rating/rating-config.spec.ts
- src/rating/rating-config.ts
- src/rating/rating.spec.ts
- src/rating/rating.ts
Hi,
I am using the rating control and was unable to set the tabindex on the control. Have I missed something or is this pull request required to be able to set the tabindex of the html element?
The change was tested using the demo-site.
Best regards,
Ashwani Mehlem
> feat(rating): Allow to set tabindex using [tabIndex].

- demo/src/app/components/collapse/collapse.module.ts
- demo/src/app/components/collapse/demos/horizontal/collapse-horizontal.html
- demo/src/app/components/collapse/demos/horizontal/collapse-horizontal.module.ts
- demo/src/app/components/collapse/demos/horizontal/collapse-horizontal.ts
- src/accordion/accordion.ts
- src/collapse/collapse-config.ts
- src/collapse/collapse.spec.ts
- src/collapse/collapse.ts
- src/util/transition/ngbCollapseTransition.ts
I have added the horizontal option to the collapse widget.
It has the same requirement as in [Bootstrap 5](https://getbootstrap.com/docs/5.2/components/collapse/#horizontal): the immediate child elements must have a width.
> feat(collapse): add horizontal collapse

- src/datepicker/datepicker.module.ts
- src/index.ts
Hi :)
Thanks for building this great lib. 
Currently, we use `NgbDatepicker` and the `NgbDateNativeAdapter ` to track our models as native ES Dates globally across our project.
In a specific module, we wanted override this and use the standard behavior via `NgbDateStructAdapter`. However, this implementation isn't exported and thus, not accessible to us. Trying to import it results in a path like this and won't compile:
`import { NgbDateStructAdapter } from '@ng-bootstrap/ng-bootstrap/datepicker/adapters/ngb-date-adapter';`
I don't see a reason not to export it since it could profit some people (like our project) that want to use it outside of the default behavior.
This PR adds the …
> fix(datepicker): export NgbDateStructAdapter

- demo/src/app/components/collapse/demos/basic/collapse-basic.html
- src/collapse/collapse.ts
I have removed the OnChange in the ngbCollapse directive to avoid starting the animation twice.
I have used a setter and a flag. The setter executes the "_runTransitionWithEvents" while the flag is used to avoid running the animation during initialisation.
> fix(collapse): solved running transition twice

- demo/src/app/components/collapse/demos/horizontal/collapse-horizontal.html
- src/util/transition/ngbCollapseTransition.ts
This PR restores the previous collapse transition logic that was changed with #4370.
Without this PR, the show and hide phases are inconsistent: the hide phase is from the full size of the container to `0px`, and the show phase is from `0px` to the `scrollWidth`/`scrollHeight` of the container and then there is a sudden change when the classes are changed at the end of the transition.
Using `scrollWidth` / `scrollHeight` does not feel right for me. We should use whatever size the container will have when changing the classes at the end of the transition, which is what `measureCollapsingElementDimensionPx` measures correctly. I have added `style="max-width:300px;"` on the container in the demo so that the animation matches the visible content.
Before submitting a pull request, please make …
> fix(collapse): restore previous transition logic

- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
Removes `aria-multiline="false"`, which is invalid on comboboxes.
Fixes #4181
> fix(typeahead): remove aria-multiline attribute

- src/toast/toast-transition.ts
- src/toast/toast.spec.ts
Toast animations have been broken since the update to Bootstrap v5.2, which changed it's internal api for transitions. This PR mimics the behavior of the logic in bootstrap.js and removes the use of the deprecated class `hide`.
> refactor(toast): update toast transitions to Bootstrap 5.2

- src/modal/modal-lazy-module.spec.ts
- src/modal/modal-stack.ts
- src/modal/modal.module.ts
- src/modal/modal.spec.ts
Provides `NgbModal` at the `NgbModalModule` level as well as at the 'root' level. Provides environment injector based on the `contentInjector` and not the `appRef.injector` when using component as modal content.
Fixes #4447
> fix(modal): provide `NgbModal` at the correct level

- src/accordion/accordion.directive.spec.ts
- src/accordion/accordion.directive.ts
Previously `closeOthers` consistency was enforced only at the accordion level with `accordion.toggle(itemId)`, `accordion.expand(itemId)`, etc.
This change ensures that:
- `item.toggle()`, `item.expand()` and `item.collapsed = false` respect that only one item stays open
- only one item can be opened initially even with several with `[collapse]="false"`
cc @ValentinNelu
> fix(accordion): fixes inconsistent `closeOthers` behavior

- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
Not necessary to have them since `aria-current` was introduced
Fixes #3870
> fix(pagination): remove `.visually-hidden` spans

- src/dropdown/dropdown.module.ts
- src/dropdown/dropdown.ts
- src/index.ts
The NgbNavbar directive is not removed, but simply deprecated, in order to avoid a breaking change for people who have imported it in their modules or standalone components.
fix #4462
> feat(dropdown): replace NgbNavbar usage by DOM call to closest()

- misc/stackblitzes-templates/main.ts.ejs
This change provides an HttpClient to all the stackblitz demos to ensure they function like they do on the demo site. Currently the HttpClient is the only provider needed, but the stackblitz template `misc/stackblitzes-templates/main.ts.ejs` should be kept in sync with `demo/src/main.ts` to ensure the individual examples have all their dependencies provided.
The needed providers can also be provided to the demo modules themselves or as context to the template renderer, but that may be more effort than its worth and while providing the dependencies to all the examples is overkill it will ensure they all work correctly.
> demo: use `provideHttpClient` in stackblitz demos

- demo/src/app/components/popover/demos/tplwithcontext/popover-tplwithcontext.html
- demo/src/app/components/tooltip/demos/tplwithcontext/tooltip-tplwithcontext.html
- src/popover/popover.spec.ts
- src/popover/popover.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
- yarn.lock
Currently for popover and tooltip components, the only way to specify a template context is by using the `open` method manually. This add ability to directly specify the template context, so we can create template with custom context without any function call. This default context for `TemplateRef` can also be override by the `open` method.
I've also added the demo, and the documentation.  Hoping this will be merged and released soon.
> feat(popover/tooltip): add default TemplateRef context

- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
Moves the aria-activedescendant attribute from the root element to the '.carousel-indicators' element which has a compatible 'tablist' role. Checked with lighthouse and axe devtools, both don't show the role mismatch warning on carousels.
Fixes #4416
> fix(carousel): move 'aria-activedescendant' attribute to indicators

- src/carousel/carousel.spec.ts
- src/carousel/carousel.ts
Reverts ng-bootstrap/ng-bootstrap#4524
While a11y warnings in question are gone, screen readers actually perform much worse in my manual tests.
> Revert "fix(carousel): move 'aria-activedescendant' attribute to indicators"

- src/alert/alert.ts
> Fix NgbAlert dismissable mentions 'close' output instead of 'closed'

- src/rating/rating.spec.ts
- src/rating/rating.ts
readonly -> `aria-readonly`
disabled -> `aria-disabled`
Previously `aria-disabled` was generated in case of readonly rating and nothing when disabled
> fix(rating): generate correct `aria-readonly/disabled` attributes

- src/dropdown/dropdown.spec.ts
- src/dropdown/dropdown.ts
The `show` class on dropdown toggle will keep the button element in active state, inditicating that dropdown is open. This small change was made between Bootstrap v4 and v5.
Fixes #4531
> fix(dropdown): add `show` class to dropdown toggle when dropdown is open

- src/datepicker/datepicker-config.ts
- src/datepicker/datepicker.spec.ts
> fix(datepicker): `startDate` type should accept dates withe days

- demo/src/app/components/datepicker/calendars/datepicker-calendars.component.ts
- demo/src/app/components/datepicker/demos/ethiopian/datepicker-ethiopian.html
- demo/src/app/components/datepicker/demos/ethiopian/datepicker-ethiopian.ts
- src/datepicker/datepicker.module.ts
- src/datepicker/ethiopian/datepicker-i18n-amharic.ts
- src/datepicker/ethiopian/ethiopian.ts
- src/datepicker/ethiopian/ngb-calendar-ethiopian.spec.ts
- src/datepicker/ethiopian/ngb-calendar-ethiopian.ts
- src/index.ts
a new feature for the datepicker, NgbCalenderEthiopia and datepicker-i18n-amharic is implemented.
fix #4499
> feat(datepicker): add ethiopian date picker

- src/typeahead/typeahead-window.ts
Since the list or results if provided by the user code, we can't ensure that the list doesn't contain duplicates. Tracking by index is a safer default and won't generate a warning or a crash as mentioned in the issue.
fix #4702
> fix(typeahead): track results by index in NgbTypeahead

- src/datepicker/datepicker.ts
Because weekdays can be the same now, tracking by the $index remove the warning.
> fix(datepicker): track weekdays by $index

- src/tooltip/tooltip.ts
> demo(tooltip): rephrased comments in tooltip

- demo/src/app/components/pagination/overview/pagination-overview.component.html
Fixed mistyped word: `mentionned` to correct: `mentioned` in [pagination usage example](https://ng-bootstrap.github.io/#/components/pagination/overview)
> (docs) pagination: fix misspelled word in pagination usage example

- demo/src/app/components/scrollspy/overview/scrollspy-overview.component.html
Fixed mistyped word: `Fpr` to correct: `For` in [scrollspy overview](https://ng-bootstrap.github.io/#/components/scrollspy/overview)
> (docs) scrollspy: fix misspelled word in scrollspy overview docs

- src/datepicker/datepicker-i18n.ts
`timeZone` defaults to the user's timezone, which means that the week names might be returned in an unexpected order:
```
> TZ=Europe/Copenhagen node --eval "console.log([...Array(7).keys()].map((day) => Intl.DateTimeFormat('en', { weekday: 'narrow' }).format(new Date(Date.UTC(2021, 5, day - 1)))))"
[
'S', 'M', 'T',
'W', 'T', 'F',
'S'
]
> TZ=America/New_York  node --eval "console.log([...Array(7).keys()].map((day) => Intl.DateTimeFormat('en', { weekday: 'narrow' }).format(new Date(Date.UTC(2021, 5, day - 1)))))"
[
'S', 'S', 'M',
'T', 'W', 'T',
'F'
]
```
This would have been caught if the unit tests were run in different timezones (presumably they are run with `TZ=UTC` in CI?), as they are currently either passing or failing, depending on the timezone they are run in:
```
> TZ=UTC npm run …
```
> fix(datepicker): generate weekday labels in correct order

- src/datepicker/datepicker-input.spec.ts
- src/datepicker/datepicker-input.ts
- src/datepicker/datepicker.spec.ts
- src/datepicker/datepicker.ts
Note that the proposed fix for #4697 will not resolve the issue when `NgbDatepicker.navigateTo()` is called manually, only when it is called by setting the `[startDate]` input. It seems reasonable to expect users not to call functions on components before they're initialized, so I believe this fix to be sufficient. That said, I'm more than happy to hear any feedback.
Fixes #4697
Fixes #3848
> fix(datepicker): config not applied

- src/util/positioning.ts
While investigating https://github.com/ng-bootstrap/ng-bootstrap/issues/4678 I discovered that ng-bootstrap seems to override popper's native `preventOverflow` function, which so far as I can tell seems un-helpful. I also note that in the original PR which added this, maxokorokov noted that it is probably not necessary (I see no response to the comment and the change was left in): https://github.com/ng-bootstrap/ng-bootstrap/pull/4129#discussion_r704246424
I'm unsure whether you guys would consider this breaking, from my perspective its sort of the opposite, but given its been this way for literally a couple of years I dont want to understate the potential ramifications. Certainly all tests pass and my suspicion is the majority of users will see no changes from this (if someone is adding …
> fix(core): restore popper default preventOverflow function

- src/tooltip/tooltip.ts
docs(tooltip): replace term `popover` with `tooltip` in `isOpen()` method description.
> docs(tooltip): replace term popover with tooltip in isOpen() method description.

- e2e-app/src/app/app.routes.ts
- e2e-app/src/app/modal/role/modal-role.component.html
- e2e-app/src/app/modal/role/modal-role.component.ts
- e2e-app/src/app/modal/role/modal-role.e2e-spec.ts
- e2e-app/src/app/modal/role/modal-role.po.ts
- src/modal/modal-config.spec.ts
- src/modal/modal-config.ts
- src/modal/modal-ref.ts
- src/modal/modal-window.spec.ts
- src/modal/modal-window.ts
> feat(modal): add role option

- src/pagination/pagination.spec.ts
- src/pagination/pagination.ts
Focusable pagination element should be marked with `aria-current` for the SR to read it properly (NVDA works with the attribute set on li but JAWS needs it to be on <a> element). 
reference of the `aria-current` and recommended usage: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current#example
> fix(pagination): put aria-current on link element instead of li for a11y

- demo/src/app/components/popover/demos/delay/popover-delay.html
- demo/src/app/components/tooltip/demos/delay/tooltip-delay.html
- src/popover/popover.spec.ts
- src/popover/popover.ts
- src/tooltip/tooltip.spec.ts
- src/tooltip/tooltip.ts
- src/util/triggers.ts
When using a hover trigger and a close delay, tooltips/popovers will be kept open if the mouse leaves the trigger element and enters the tooltip/popover element before the close delay times out.
Fixes #4168
> fix(tooltip,popover): keep tooltip/popover open when it is hovered

- src/datepicker/datepicker-navigation.spec.ts
- src/datepicker/datepicker-navigation.ts
When using a screen reader, month(s) updates are not announced.
(Especially for previous and next arrow buttons)
This PR solves it by adding a visually hidden live area announcing the month updates.
> feat(datepicker): add live area to announce selected month(s) update

- src/timepicker/timepicker.ts
Toggling the meridian option with empty model wrongly sets the hour without any user input on it.
Fixes #4797
> fix(timepicker): wrong auto-setting of hour value

- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
`combobox` needs `aria-controls` to be specified:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/combobox_role
> fix(typeahead): add aria-controls for accessibility

- src/typeahead/typeahead.spec.ts
- src/typeahead/typeahead.ts
fix #4777
BREAKING CHANGE:
When typing into a non-editable typeahead and not selecting any value, the associated form control value is set to null instead of undefined.
> fix: set the value of typeahead's control to null instead of undefined

- src/datepicker/datepicker.module.ts
- src/index.ts
`DayTemplateContext` is now exported from the ng-bootstrap public API.
DayTemplateContext is referenced in the official documentation as the type for the `[dayTemplate]` input of the datepicker component. [https://ng-bootstrap.github.io/#/components/datepicker/api#DayTemplateContext](https://ng-bootstrap.github.io/#/components/datepicker/api#DayTemplateContext)
This change makes DayTemplateContext available for import, enabling consumers to define type-safe properties and templates that interact with the datepicker’s day template context, as described in the documentation.
```typescript
import { DayTemplateContext, NgbDatepickerConfig } from '@ng-bootstrap/ng-bootstrap';
...
@Input() customTemplate: TemplateRef<DayTemplateContext> | undefined;
constructor(
public config: …
```
> feat(datepicker): export DayTemplateContext
