demo/src/app/components/accordion/accordion.component.html
demo/src/app/components/accordion/accordion.component.ts
demo/src/app/components/accordion/demos/ngb-accordion.json
demo/src/app/components/accordion/demos/ngb-panel.json
demo/src/app/components/shared/component-docs/component-docs.component.html
demo/src/app/components/shared/component-docs/component-docs.component.ts
demo/src/app/components/shared/component-docs/index.ts
demo/src/app/components/shared/example-box/example-box.component.html
demo/src/app/components/shared/example-box/example-box.component.ts
demo/src/app/components/shared/example-box/index.ts
demo/src/app/components/shared/index.ts
demo/src/app/components/shared/instructions-item/instructions-item.component.html
demo/src/app/components/shared/instructions-item/instructions-item.component.ts

A bit of a refactor, is not much, but I want to stop bikeshedding on that for a bit.
Now we can add effort into real docs.

docs: refactor structure a bit

---

demo/src/app/app.component.html
demo/src/app/home/home.component.html
demo/src/app/shared/side-nav/side-nav.component.html

Let's just keep stuff for which we've got content...

demo(docs): various demo docs corrections

---

demo/src/app/components/shared/api-docs/api-docs.component.ts

Pull it to see them in action!

docs(demo): visual changes to the API docs

---

.travis.yml

chore: install typings on travis

---

gulpfile.js

chore(build): added sourcemap generation for cjs build

---

demo/src/app/app.component.ts
demo/src/app/components/accordion/demos/preventChange/accordion-preventChange.ts
demo/src/app/components/accordion/demos/toggle/accordion-toggle.ts
demo/src/app/components/collapse/collapse.component.ts
demo/src/app/components/rating/rating.component.ts
demo/src/app/components/shared/api-docs/api-docs.component.ts
demo/src/app/components/shared/example-box/example-box.component.ts
demo/src/app/default/default.component.ts
demo/src/app/getting-started/getting-started.component.ts
demo/src/app/shared/content-wrapper/content-wrapper.component.ts
demo/src/app/shared/side-nav/side-nav.component.ts

demo: remove more require() calls

---

tsconfig-es2015.json
tsconfig.json

chore: break build on TS errors

---

demo/src/app/getting-started/getting-started.component.html

This should help guide users to the ng-bootstrap questions on stackoverflow.

chore(doc): add ng-bootstrap tag to SO link

---

src/alert/alert.spec.ts
src/carousel/carousel.spec.ts
src/collapse/collapse.spec.ts
src/pagination/pagination.spec.ts
src/rating/rating.spec.ts

test: TestBed migration leftovers

---

demo/src/app/components/alert/demos/custom/alert-custom.ts

* fix custom style on custom alert due to changes in RC6.
Fixes #659

fix(alert): fix custom style on custom alert demo

---

demo/src/app/components/pagination/demos/config/pagination-config.html
demo/src/app/components/pagination/demos/config/pagination-config.ts
demo/src/app/components/pagination/demos/index.ts
demo/src/app/components/pagination/pagination.component.ts
src/index.ts
src/pagination/pagination-config.spec.ts
src/pagination/pagination-config.ts
src/pagination/pagination.module.ts
src/pagination/pagination.spec.ts
src/pagination/pagination.ts

feat(pagination): add config service to provide default values

---

src/modal/modal.ts

chore(modal): fixes typos

---

README.md
demo/src/app/getting-started/getting-started.component.html

docs: clarify 'NgbModule.forRoot()' usage

---

.gitignore
DEVELOPER.md
misc/api-doc.js
misc/api-doc.spec.js
misc/get-doc.js

chore: clean-up typings leftovers

---

src/datepicker/datepicker-navigation.ts

fix(datepicker): use `td` in arrows navigation

---

postcss.config.js

Closes #1215
More info in https://github.com/ng-bootstrap/ng-bootstrap/issues/1215#issuecomment-273151844

chore(build): add postcss loader config

---

src/datepicker/datepicker-navigation-select.spec.ts
src/datepicker/datepicker-navigation-select.ts

fix(datepicker): account for undefined values in ngOnChanges

---

package.json

See [issue#14579](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14579) regarding @types/jasmine . 

fix(build): freeze @types/jasmine version

---

demo/src/public/index.html

demo: add lang reference for accessibility purpose

---

src/buttons/checkbox.spec.ts
src/buttons/label.ts
src/buttons/radio.spec.ts

refactor(buttons): use binding instead of Renderer interactions

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts

fix(datepicker): popup disabled state

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts
src/datepicker/datepicker-service.spec.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts

fix(datepicker): Close date picker after selecting the same date

---

src/timepicker/timepicker.ts

https://github.com/ng-bootstrap/ng-bootstrap/issues/1851

fix(timepicker): btn-link style

---

src/datepicker/datepicker-navigation.ts

https://github.com/ng-bootstrap/ng-bootstrap/issues/1851

fix(datepicker): btn-link style

---

demo/src/app/components/progressbar/demos/config/progressbar-config.ts
demo/src/app/components/progressbar/demos/height/progressbar-height.html
demo/src/app/components/progressbar/demos/height/progressbar-height.ts
demo/src/app/components/progressbar/demos/index.ts
demo/src/app/components/progressbar/progressbar.component.ts
src/progressbar/progressbar-config.ts
src/progressbar/progressbar.spec.ts
src/progressbar/progressbar.ts

feat(progressbar): specify height

---

demo/src/app/components/datepicker/datepicker.component.ts
demo/src/app/components/datepicker/demos/adapter/datepicker-adapter.html
demo/src/app/components/datepicker/demos/adapter/datepicker-adapter.ts
demo/src/app/components/datepicker/demos/index.ts
src/datepicker/datepicker.module.ts
src/datepicker/datepicker.ts
src/datepicker/ngb-date-adapter.spec.ts
src/datepicker/ngb-date-adapter.ts
src/index.ts

This is a continuation of #1816 since the original requester(@edriang) said he will no longer work on it. I added the changes requested by @maxokorokov 
Closes #1816

 feat(datepicker): enable user to define his own date structure 

---

src/typeahead/typeahead.ts

fix
https://github.com/ng-bootstrap/ng-bootstrap/issues/1559

feat(ngbTypeahead): add exportAs property for ngbTypeahead

---

demo/src/app/components/datepicker/demos/adapter/datepicker-adapter.ts
src/datepicker/datepicker-input.spec.ts

Fixes #2060
Fixes #2098
Closes #2060
- [] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
- [] built and tested the changes locally.

fix(datepicker): native date adapter

---

src/timepicker/timepicker.ts

fix(timepicker): Add CSS for IE10 flexbox

---

src/datepicker/datepicker-navigation.spec.ts
src/datepicker/datepicker-navigation.ts
src/datepicker/datepicker-service.spec.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker-tools.ts
src/datepicker/datepicker-view-model.ts
src/datepicker/datepicker.ts

A part in series of moving state/logic from components to the service

refactor(datepicker): enable/disable navigation buttons in the service

---

src/datepicker/datepicker-tools.spec.ts
src/datepicker/datepicker-tools.ts

refactor(datepicker): simplify first view date calculation

---

demo/src/app/components/shared/api-docs/api-docs-badge.component.ts
demo/src/app/components/shared/api-docs/api-docs-class.component.html
demo/src/app/components/shared/api-docs/api-docs-config.component.html
demo/src/app/components/shared/api-docs/api-docs.component.html

demo: display 'since' for new directives, classes, services, etc.

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts
src/datepicker/datepicker-month-view.spec.ts
src/datepicker/datepicker-month-view.ts
src/datepicker/datepicker-navigation-select.ts
src/datepicker/datepicker-navigation.ts
src/datepicker/datepicker-service.spec.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker-tools.ts
src/datepicker/datepicker-view-model.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts

feat(datepicker): keyboard navigation for accessibility

---

src/typeahead/typeahead.module.ts
src/typeahead/typeahead.spec.ts
src/typeahead/typeahead.ts
src/util/accessibility/live.spec.ts
src/util/accessibility/live.ts

feat(typeahead): accessibility, options summary status message

---

demo/src/app/components/modal/demos/basic/modal-basic.html
demo/src/app/components/modal/demos/basic/modal-basic.ts
src/modal/modal-stack.ts
src/modal/modal-window.ts
src/modal/modal.spec.ts
src/modal/modal.ts

Opened attribute `aria-labelledby`.
close #1477

feat(modal): opened aria attribute aria-labelledby for accessibility

---

src/datepicker/datepicker-input.ts

* run handlers outside of the zone
* improve readability by extracting `_shouldCloseOnOutsideClick` function
* remove unnecessary `take(1)` operator
* user `NEVER` instead of `null`
* remove `clang-format off`

refactor(datepicker): clean up observables that close popup

---

.travis.yml
src/karma.conf.js

An experiment to use headless chrome instead of Firefox for CI

chore: use headless chrome for CI

---

demo/src/app/default/default.component.html

- remove left `text-muted` styles
- reword the main message to be simpler and readable
- remove redundant`(`, `)`, `...`, `,` symbols for readability

chore: refine wording on the front page

---

demo/src/app/components/datepicker/overview/datepicker-overview.component.html
src/datepicker/datepicker-config.ts
src/datepicker/datepicker-day-template-context.ts
src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts
src/datepicker/datepicker-month-view.ts
src/datepicker/datepicker-service.spec.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker-tools.spec.ts
src/datepicker/datepicker-tools.ts
src/datepicker/datepicker-view-model.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts
src/test/datepicker/common.ts

Contains two commits, so preferably do not squash
Reverts 83930cd
Reverts 392279d

revert: datepicker generic date type <D>

---

demo/src/app/components/datepicker/demos/basic/datepicker-basic.ts
demo/src/app/components/datepicker/demos/config/datepicker-config.ts
demo/src/app/components/datepicker/demos/customday/datepicker-customday.ts
demo/src/app/components/datepicker/demos/disabled/datepicker-disabled.ts
demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.ts
demo/src/app/components/datepicker/demos/range/datepicker-range.html
demo/src/app/components/datepicker/demos/range/datepicker-range.ts
demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts

demo(datepicker): update demos to use 'NgbDate'

---

src/alert/alert.spec.ts
src/alert/alert.ts

refactor(alert): remove intermediate 'div' element

---

demo/src/app/components/datepicker/datepicker.component.ts
demo/src/app/components/datepicker/demos/index.ts
demo/src/app/components/datepicker/demos/jalali/datepicker-jalali.html
demo/src/app/components/datepicker/demos/jalali/datepicker-jalali.ts
src/datepicker/datepicker.module.ts
src/datepicker/jalali/jalali.ts
src/datepicker/jalali/ngb-calendar-persian.ts
src/index.ts

Persian calendar

---

src/carousel/carousel.spec.ts
src/datepicker/datepicker-input.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker-tools.spec.ts
src/datepicker/datepicker-view-model.ts
src/datepicker/datepicker.spec.ts
src/dropdown/dropdown.ts
src/popover/popover.spec.ts
src/popover/popover.ts
src/timepicker/timepicker.spec.ts
src/tooltip/tooltip.spec.ts
src/tooltip/tooltip.ts
src/typeahead/typeahead.spec.ts
tslint.json

Two commits here:
- `semicolon` tslint rule wasn't working for a looong time → turned on an fixed issues
- `member-ordering` rule also had syntax issues

chore: fix linting configuration issues

---

demo/src/app/app.component.html

fix(demo): missing / in bootstrap href link

---

src/tabset/tabset.spec.ts
src/tabset/tabset.ts

feat(tabset): allow arbitrary nav type

---

src/datepicker/datepicker-day-view.spec.ts
src/datepicker/datepicker-day-view.ts
src/datepicker/datepicker-i18n.spec.ts
src/datepicker/datepicker-i18n.ts
src/datepicker/datepicker-integration.spec.ts
src/datepicker/datepicker-month-view.ts
src/datepicker/datepicker-navigation-select.ts

Useful for calendars that do not use arabic numerals like Hebrew
Related to #1668

feat(datepicker): allow overriding day, week number and year numerals

---

angular.json
demo/src/app/components/accordion/demos/preventchange/accordion-preventchange.ts
demo/src/app/components/datepicker/demos/range/datepicker-range.ts
demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts
demo/src/app/components/shared/api-docs/api-docs-class.component.ts
demo/src/app/components/shared/api-docs/api-docs-config.component.ts
demo/src/app/components/shared/api-docs/api-docs.component.ts
demo/src/app/components/tabset/demos/preventchange/tabset-preventchange.ts
demo/src/app/components/typeahead/demos/basic/typeahead-basic.ts
demo/src/app/components/typeahead/demos/config/typeahead-config.ts
demo/src/app/components/typeahead/demos/format/typeahead-format.ts
demo/src/app/components/typeahead/demos/http/typeahead-http.ts
demo/src/app/components/typeahead/demos/template/typeahead-template.ts
demo/tslint.json
package.json
src/tslint.json

- enables linting for the demo site sources
- adds two more `tslint.json` (as in CLI projet)
- fixes lining minor linting issues in the demo

chore: add proper tslint configs and enable linting for the demo

---

src/modal/modal-ref.ts

[ng-bootstrap 3.0.0 requires Angular version ^6.1.0](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#300-2018-08-13) and [Angular 6.0.0 depends on TypeScript 2.7](https://github.com/angular/angular/blob/master/CHANGELOG.md#600-2018-05-03).

feat(modal): remove TS1.8 support

---

demo/src/app/components/modal/demos/stacked/modal-stacked.html
demo/src/app/components/modal/demos/stacked/modal-stacked.ts
demo/src/app/components/modal/modal.module.ts
src/modal/modal-backdrop.ts
src/modal/modal-stack.ts
src/modal/modal-window.ts
src/modal/modal.spec.ts

P.S. if you think the project is not ready to have stacked modals in the demo, at least consider merging changes related to the `modal-open` class.

feat(modal): stacked modals

---

demo/src/app/components/datepicker/datepicker.module.ts
demo/src/app/components/datepicker/demos/hebrew/datepicker-hebrew.html
demo/src/app/components/datepicker/demos/hebrew/datepicker-hebrew.ts

Adds a new calendar demo (without refactoring existing onces for now)

demo(datepicker): Hebrew calendar demo

---

src/datepicker/adapters/ngb-date-native-adapter.ts
src/datepicker/adapters/ngb-date-native-utc-adapter.ts

refactor(datepicker): use 'instanceof' in adapters

---

demo/src/app/components/modal/demos/basic/modal-basic.html

demo(modal): fix missed calendar icon in modal demo

---

misc/plunk-gen.js
misc/stackblitz-gen.js

demo: fix entryComponent generation for Plunkers and StackBlitzes

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts

fix(datepicker): avoid updating the model twice (on input and on change)

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts

fix(datepicker): no longer trigger onChange when the value is equivalent

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts

fix(datepicker): don't close on Esc if autoClose is false

---

src/alert/alert.scss
src/alert/alert.ts
src/browserslist
src/datepicker/datepicker-day-view.scss
src/datepicker/datepicker-day-view.ts
src/datepicker/datepicker-month-view.scss
src/datepicker/datepicker-month-view.ts
src/datepicker/datepicker-navigation-select.scss
src/datepicker/datepicker-navigation-select.ts
src/datepicker/datepicker-navigation.scss
src/datepicker/datepicker-navigation.ts
src/datepicker/datepicker.scss
src/datepicker/datepicker.ts
src/popover/popover.scss
src/popover/popover.ts
src/timepicker/timepicker.scss
src/timepicker/timepicker.ts
src/tooltip/tooltip.scss
src/tooltip/tooltip.ts
src/typeahead/highlight.scss
src/typeahead/highlight.ts

This change enables autoprefixer and CSS minification
Fixes https://github.com/ng-bootstrap/ng-bootstrap/issues/2701
Comparison on file `/dist/esm2015/datepicker/datepicker-navigation.js`
<details><summary>esm2015 output before</summary>
```ts
NgbDatepickerNavigation.decorators = [
{ type: Component, args: [{
selector: 'ngb-datepicker-navigation',
changeDetection: ChangeDetectionStrategy.OnPush,
styles: [`
:host {
display: -ms-flexbox;
display: flex;
-ms-flex-align: center;
align-items: center;
}
.ngb-dp-navigation-chevron {
border-style: solid;
border-width: 0.2em 0.2em 0 0;
display: inline-block;
width: 0.75em;
height: 0.75em;
margin-left: 0.25em;
margin-right: 0.15em;
transform: …
```

Use autoprefixer and SCSS for library build

---

src/carousel/carousel.spec.ts
src/carousel/carousel.ts

fix(carousel): do not crash if there are no slides

---

src/modal/modal-stack.ts
src/modal/modal.spec.ts
src/modal/modal.ts

Closes #1600
A tiny PR for a good start of the weekend!

feat(modal): allow checking if there are open modals

---

misc/validate-commit.js

fix(hook): git commit msg hook fail

---

misc/api-doc.ts

- type checker wasn't passed everywhere
- `unknown` was renamed to `error` for generic type extraction (must be a better way to check this). Leaving both to add backward-compatibility
Part of #2764

chore(build): support TS 3.1 for doc extraction script

---

e2e-app/e2e/protractor.conf.js
e2e-app/e2e/src/datepicker/datepicker-autoclose.e2e-spec.ts
e2e-app/e2e/src/datepicker/datepicker-autoclose.po.ts
e2e-app/e2e/src/datepicker/datepicker-focus.e2e-spec.ts
e2e-app/e2e/src/datepicker/datepicker-focus.po.ts
e2e-app/e2e/src/datepicker/datepicker.po.ts
e2e-app/e2e/src/dropdown/dropdown-autoclose.e2e-spec.ts
e2e-app/e2e/src/dropdown/dropdown-autoclose.po.ts
e2e-app/e2e/src/modal/modal-focustrap.e2e-spec.ts
e2e-app/e2e/src/modal/modal-focustrap.po.ts
e2e-app/e2e/src/popover/popover-autoclose.e2e-spec.ts
e2e-app/e2e/src/popover/popover-autoclose.po.ts
e2e-app/e2e/src/tools.ts
e2e-app/e2e/src/tooltip/tooltip-autoclose.e2e-spec.ts
e2e-app/e2e/src/tooltip/tooltip-autoclose.po.ts
e2e-app/e2e/src/typeahead/typeahead-focus.e2e-spec.ts
e2e-app/e2e/src/typeahead/typeahead.po.ts
e2e-app/src/app/app.component.ts
e2e-app/src/app/app.module.ts
e2e-app/src/app/app.routing.ts
e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.ts
e2e-app/src/app/datepicker/focus/datepicker-focus.component.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.ts
e2e-app/src/app/modal/focustrap/modal-focustrap.component.ts
e2e-app/src/app/popover/autoclose/popover-autoclose.component.ts
e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.ts
e2e-app/src/app/typeahead/focus/typeahead-focus.component.ts
e2e-app/src/main.ts
e2e-app/src/polyfills.ts
gulpfile.js

- turn on clang-format
- report with 'dots' in CI and with more details locally

E2e test refinements

---

e2e-app/e2e/src/modal/modal-focus.e2e-spec.ts
src/util/focus-trap.ts

fix(modal): focus stays trapped with Shift+Tab

---

e2e-app/e2e/src/typeahead/typeahead-focus.e2e-spec.ts
src/typeahead/typeahead.ts

feat(typeahead): fix focus on item click

---

e2e-app/src/app/typeahead/focus/typeahead-focus.component.ts
e2e-app/src/app/typeahead/focus/typeahead-focus.e2e-spec.ts
src/typeahead/typeahead-window.ts
src/typeahead/typeahead.ts

fix(typeahead): prevent dropdown to be reopen after an item click

---

.travis.yml
README.md
angular.json

Integration with codecov.io

---

src/carousel/carousel.spec.ts
src/carousel/carousel.ts

Change detection wasn't triggered when slides were changed, see use case in the `'should mark component for check when slides change'` test
Fixes #2900

fix(carousel): do change detection when slides change

---

src/timepicker/timepicker.spec.ts
src/timepicker/timepicker.ts

Closes #2851
Also added some tests for step setting via component input properties

fix(timepicker): setting hour/minute/second step to undefined

---

demo/src/app/components/pagination/overview/pagination-overview.component.html
demo/src/app/components/pagination/overview/pagination-overview.component.ts
demo/src/app/components/pagination/pagination.module.ts

Just adding some documentation to highlight how to setup properly pagination.
Closes #2931 
---
Here is the screenshot

chore(demo): pagination overview tab

---

src/modal/modal.ts

fix(modal): update incorrect grammar

---

e2e-app/src/app/app.module.ts
e2e-app/src/app/app.routing.ts
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.component.html
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.component.ts
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.e2e-spec.ts
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.po.ts
e2e-app/src/app/typeahead/focus/typeahead-focus.e2e-spec.ts
e2e-app/src/app/typeahead/typeahead.po.ts

Adding missing typeahead e2e tests for #2727
@divdavem FYI

test(typeahead): e2e tests for typeahead autoclose

---

e2e-app/src/app/app.module.ts
e2e-app/src/app/app.routing.ts
e2e-app/src/app/tooltip/position/tooltip-position.component.html
e2e-app/src/app/tooltip/position/tooltip-position.component.ts
e2e-app/src/app/tooltip/position/tooltip-position.e2e-spec.ts
e2e-app/src/app/tooltip/position/tooltip-position.po.ts
src/datepicker/datepicker-input.ts
src/dropdown/dropdown-config.spec.ts
src/dropdown/dropdown-config.ts
src/popover/popover.spec.ts
src/popover/popover.ts
src/tooltip/tooltip.spec.ts
src/tooltip/tooltip.ts
src/typeahead/typeahead-config.ts
src/util/positioning.spec.ts
src/util/positioning.ts

fix(positioning): use CSS translate for positioning

---

src/popover/popover.scss
src/tooltip/tooltip.scss

fix(popover): arrow positioning issues

---

src/timepicker/timepicker.spec.ts
src/timepicker/timepicker.ts

fix(timepicker): display correct NgModel value inside OnPush component

---

src/util/autoclose.ts

Tested on Android, Windows 10 with touch and iOS.
Autoclose was broken only on iOS, other browsers work fine with `mousedown/mouseup` while `iOS` needs to have `touchstart/touchend`
Fixes #2995
cc @divdavem

fix(autoclose): fix popup automatic closing on touch on iOS

---

src/util/positioning.ts

The purpose is to have the first given placement of a popup as the default one.
If any position of a  popover/tooltip/dropdown/... can't enter in the viewport, it's not natural to keep the last one as the preferred one.

fix(positionning): set the first placement as the default one

---

demo/src/app/components/dropdown/demos/basic/dropdown-basic.html
demo/src/app/components/dropdown/demos/config/dropdown-config.html
demo/src/app/components/dropdown/demos/form/dropdown-form.html
demo/src/app/components/dropdown/demos/form/dropdown-form.ts
demo/src/app/components/dropdown/demos/manual/dropdown-manual.html
demo/src/app/components/dropdown/demos/split/dropdown-split.html
demo/src/app/components/dropdown/dropdown.module.ts
src/dropdown/dropdown.module.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts
src/index.ts

This is a resubmit for #1417 by @wolfgangteves updated for the latest master branch

feat(dropdown): add keyboard navigation support

---

src/util/autoclose.ts

A temporary fix without proper platform detection
Fixes #3025

fix(autoclose): browser detection for SSR

---

e2e-app/src/app/app.module.ts
e2e-app/src/app/app.routing.ts
e2e-app/src/app/tooltip/focus/tooltip-focus.component.html
e2e-app/src/app/tooltip/focus/tooltip-focus.component.ts
e2e-app/src/app/tooltip/focus/tooltip-focus.e2e-spec.ts
e2e-app/src/app/tooltip/focus/tooltip-focus.po.ts
src/tooltip/tooltip-config.spec.ts
src/tooltip/tooltip-config.ts
src/tooltip/tooltip.spec.ts
src/util/triggers.ts

Relates to #3022 
To improve A11Y this update adds "focus" trigger to the NgbTooltip component.

feat(Tooltip): Add trigger "focus" to enhance A11Y

---

src/datepicker/datepicker-input.ts
src/dropdown/dropdown.ts
src/popover/popover.spec.ts
src/popover/popover.ts
src/tooltip/tooltip.spec.ts
src/tooltip/tooltip.ts
src/typeahead/typeahead.ts
src/util/positioning.ts

feat(position): accept placement values with a space separated string

---

e2e-app/src/app/tooltip/position/tooltip-position.component.html
e2e-app/src/app/tooltip/position/tooltip-position.e2e-spec.ts
src/popover/popover.spec.ts
src/tooltip/tooltip.spec.ts
src/util/positioning.ts

fix(position): wrong placement class applies in some cases

---

e2e-app/src/app/app.component.ts
e2e-app/src/app/app.module.ts
e2e-app/src/app/app.routing.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
e2e-app/src/app/dropdown/dropdown.po.ts
e2e-app/src/app/dropdown/position/dropdown-position.component.html
e2e-app/src/app/dropdown/position/dropdown-position.component.ts
e2e-app/src/app/dropdown/position/dropdown-position.e2e-spec.ts
e2e-app/src/app/dropdown/position/dropdown-position.po.ts
e2e-app/src/app/tooltip/position/tooltip-position.component.html
src/dropdown/dropdown-config.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

feat(dropdown): enable container="body"

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts
src/datepicker/datepicker-service.spec.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts

feat(datepicker): make '(navigate)' event cancellable

---

src/buttons/radio.spec.ts
src/buttons/radio.ts

fix(aria): set radio buttons role as "radiogroup"

---

src/util/positioning.ts

fix(positioning): round translated positions

---

src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

fix #3056 
The fix only adds the 'show' class before the positioning, but I don't know if it's the best solution as the class attribute is bound. I tried to 'unbind' the class, but it's much more painfull.

fix(dropdown): wrong positioning calculation

---

src/datepicker/datepicker.module.ts
src/index.ts

fix(datepicker): export Gregorian calendar

---

src/util/autoclose.ts

Fixes #3079
P.S. No tests for iOS

fix(autoclose): take into account inside 'touch' events on iOS

---

demo/src/style/app.scss

Basically fix the below issue
&rarr;

chore(demo): fix toggle-code buttons alignment

---

demo/src/app/app.component.html
demo/src/app/shared/side-nav/side-nav.component.html

Also checked that everything's fine on mobile.
Before:
After:
Bootstrap:

demo: align 'home' link with Bootstrap site

---

demo/src/style/app.scss

chore(demo): fix code tabset layout broken on FF

---

demo/src/style/app.scss

... and also tested on Edge ✅ and Firefox ✅

chore(demo): fixing code tabset styling in IE11

---

e2e-app/src/app/dropdown/focus/dropdown-focus.component.html
e2e-app/src/app/dropdown/focus/dropdown-focus.component.ts
e2e-app/src/app/dropdown/focus/dropdown-focus.e2e-spec.ts
e2e-app/src/app/dropdown/focus/dropdown-focus.po.ts
e2e-app/src/app/start.e2e-spec.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

(hide whitespace changes for review)
Fixes #3117

fix(dropdown): don't fail on keypress if there are no ngbDropdownItems

---

src/dropdown/dropdown.spec.ts
src/karma.conf.js

This is a proposal. The purpose of this is:
- Check that everything is alright with the bootstrap css applied. By the way, there were `fixture.detectChanges();` to add in some tests, which were failing with Bootstrap,
- Open some cases to unit tests, for instance for positioning where Bootstrap classes can be required,
- Beautifying the unit tests :)

test: add the Bootstrap css to unit tests

---

src/dropdown/dropdown.ts

fix(dropdown): z-index set when appended to body

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts
src/datepicker/datepicker.scss

Two commits here:
- refactoring of `datepicker.scss`
- `z-index` fix for the datepicker popup with `.ngb-dp-body` class
Fixes #3133

fix(datepicker): z-index set when appended to body

---

src/datepicker/datepicker-integration.spec.ts

In Ivy, @Injectable() is required on all injected items

test(datepicker): add @Injectable() on CustomI18n

---

demo/src/app/components/dropdown/demos/form/dropdown-form.html
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.po.ts
e2e-app/src/app/tools.po.ts
src/dropdown/dropdown.ts
src/util/autoclose.ts
src/util/util.ts

fix(dropdown): close dropdown only on dropdown-item click

---

src/alert/alert.spec.ts
src/alert/alert.ts

Fixes #3171
@benouat could you PTAL / merge if ok ?

fix(alert): project content before the closing button

---

src/datepicker/datepicker-service.spec.ts
src/datepicker/datepicker-service.ts
src/datepicker/datepicker-tools.spec.ts
src/datepicker/datepicker-tools.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts

fix(datepicker): 'startDate' change was preventing arrow navigation

---

e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.po.ts
src/dropdown/dropdown.ts

fix(dropdown): close dropdown menu on Enter / Space

---

e2e-app/src/app/app.module.ts
e2e-app/src/app/app.routing.ts
e2e-app/src/app/timepicker/navigation/timepicker-navigation.component.html
e2e-app/src/app/timepicker/navigation/timepicker-navigation.component.ts
e2e-app/src/app/timepicker/navigation/timepicker-navigation.e2e-spec.ts
e2e-app/src/app/timepicker/navigation/timepicker-navigation.po.ts
e2e-app/src/app/tools.po.ts
src/timepicker/timepicker.spec.ts
src/timepicker/timepicker.ts

Fixing tab navigation between inputs and handling keyboard arrow up and down to change time.
close #1836

fix(timepicker): fixing tab navigation & handling keyboard arrows

---

demo/src/app/components/datepicker/datepicker.module.ts
demo/src/app/components/datepicker/demos/positiontarget/datepicker-position-target.module.ts
demo/src/app/components/datepicker/demos/positiontarget/datepicker-positiontarget.html
demo/src/app/components/datepicker/demos/positiontarget/datepicker-positiontarget.ts
src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts

feat(datepicker): add positionTarget property

---

src/timepicker/timepicker.ts

refactor(timepicker): readOnly is the actual property of <input>

---

src/dropdown/dropdown.module.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

feat(dropdown): display attribute and navbar management

---

src/typeahead/highlight.spec.ts
src/typeahead/highlight.ts

feat(highlight): highlight array of terms instead of just one term

---

demo/src/app/components/modal/demos/options/modal-options.html
demo/src/app/components/modal/demos/options/modal-options.ts
misc/api-doc-test-cases/interface-with-properties.ts
misc/api-doc.spec.ts
src/modal/modal-config.ts

feat(modal): Add xl size for modal #2943

---

src/typeahead/highlight.ts

refactor(highlight): simplified the highlight component

---

demo/src/app/components/timepicker/demos/i18n/timepicker-i18n.html
demo/src/app/components/timepicker/demos/i18n/timepicker-i18n.module.ts
demo/src/app/components/timepicker/demos/i18n/timepicker-i18n.ts
demo/src/app/components/timepicker/timepicker.module.ts
src/index.ts
src/timepicker/timepicker-i18n.spec.ts
src/timepicker/timepicker-i18n.ts
src/timepicker/timepicker.module.ts
src/timepicker/timepicker.spec.ts
src/timepicker/timepicker.ts

feat(timepicker): use Angular locale data for AM and PM

---

e2e-app/src/app/dropdown/position/dropdown-position.component.html
e2e-app/src/app/dropdown/position/dropdown-position.e2e-spec.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

fix(dropdown): allow template directive on the menu

---

.gitignore

chore: Ignore IntelliJ IDEA generated files

---

demo/src/app/default/default.component.html

fix(demo): wrong tabset link on home page

---

src/dropdown/dropdown.ts

- [✔️] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
- [] built and tested the changes locally.

docs(NgbDropdownItem): Minor typo in summary

---

README.md

Fix link to stackblitz in README

---

demo/src/app/components/toast/toast.module.ts

demo(toast): fix broken stackblitz url for global demo

---

CHANGELOG.md

spell correction
- [] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
- [] built and tested the changes locally.

Small correction in changelog.md

---

src/modal/modal-ref.ts
src/modal/modal.spec.ts

componentInstance is undefined if _contentRef is null

---

demo/src/app/components/typeahead/demos/prevent-manual-entry/typeahead-prevent-manual-entry.html
demo/src/app/components/typeahead/demos/prevent-manual-entry/typeahead-prevent-manual-entry.module.ts
demo/src/app/components/typeahead/demos/prevent-manual-entry/typeahead-prevent-manual-entry.ts
demo/src/app/components/typeahead/typeahead.module.ts

Please let me know if I need to change the base branch

demo(typeahead): demo for editable=false

---

demo/src/app/components/datepicker/datepicker.module.ts
demo/src/app/components/datepicker/demos/range-popup/datepicker-range-popup.html
demo/src/app/components/datepicker/demos/range-popup/datepicker-range-popup.module.ts
demo/src/app/components/datepicker/demos/range-popup/datepicker-range-popup.ts

Added an example of datepicker range selector in popup.
Probably many users of the framework would like to use a datepicker range selector in popup, so hosting such example would be useful.

feat(datepicker): Add example of datepicker range selection in popup.

---

src/pagination/pagination.spec.ts
src/pagination/pagination.ts

The purpose of this PR i to fix focus on disabled pagination control using TAB key

fix(pagination): disallow tab focus on disabled pagination

---

src/karma.sauce.conf.js

chore: bump SauceLabs browser versions

---

.github/PULL_REQUEST_TEMPLATE.md

fix PR template to render checkboxes not list of `[]`

---

src/accordion/accordion.ts

feat(accordion): use readonly arrays for inputs (#2773)

---

src/datepicker/hebrew/ngb-calendar-hebrew.ts
src/datepicker/hijri/ngb-calendar-hijri.ts
src/datepicker/jalali/ngb-calendar-persian.ts
src/datepicker/ngb-calendar.ts

feat(datepicker): use readonly arrays for inputs (#2773)

---

src/modal/modal-ref.ts
src/modal/modal.spec.ts
src/modal/modal.ts

This reverts commit f450a7c9
Fixes #3464

revert: fix(modal): add typing for `modalRef.componentInstance` (#2815)

---

e2e-app/src/app/modal/autoclose/modal-autoclose.e2e-spec.ts
e2e-app/src/app/modal/focus/modal-focus.e2e-spec.ts
e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.component.html
e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.e2e-spec.ts
e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.po.ts
e2e-app/src/app/modal/stack/modal-stack.component.html
e2e-app/src/app/modal/stack/modal-stack.e2e-spec.ts
e2e-app/src/app/modal/stack/modal-stack.po.ts

test: fix more flaky modal keyboard tests

---

demo/src/app/components/tabset/tabset-warning.component.ts
demo/src/app/components/tabset/tabset.module.ts
demo/src/app/shared/component-wrapper/component-wrapper.component.html
demo/src/app/shared/component-wrapper/component-wrapper.component.ts

docs(tabset): add a visual warning to use nav directives

---

src/index.ts

fix(nav): allow importing 'NgbNavModule' independently

---

demo/src/app/components/dropdown/demos/manual/dropdown-manual.html

Focus on dropdown items between dropdown button and manual triggers in example "Manual and custom triggers" of "Dropdown" component.
Refactor proposal for #3543

demo(dropdown): manual triggers demo markup fix

---

demo/src/app/components/datepicker/demos/custommonth/datepicker-custommonth.html
demo/src/app/components/datepicker/demos/custommonth/datepicker-custommonth.ts
src/datepicker/datepicker-integration.spec.ts
src/datepicker/datepicker-month.spec.ts
src/datepicker/datepicker.module.ts
src/datepicker/datepicker.ts
src/index.ts

Renaming due to possible future support of the month/year picker

refactor(datepicker): rename 'ngbDatepickerMonths' to 'ngbDatepickerContent'

---

demo/src/app/components/nav/demos/vertical/nav-vertical.html
demo/src/app/components/nav/demos/vertical/nav-vertical.module.ts
demo/src/app/components/nav/demos/vertical/nav-vertical.ts
demo/src/app/components/nav/nav.module.ts

demo(nav): add vertical pills demo

---

demo/src/app/components/carousel/demos/pause/carousel-pause.html
demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts
demo/src/app/components/progressbar/demos/config/progressbar-config.html
demo/src/app/components/progressbar/demos/showvalue/progressbar-showvalue.html
demo/src/app/components/progressbar/demos/texttypes/progressbar-texttypes.html
demo/src/app/components/rating/demos/decimal/rating-decimal.html
demo/src/app/components/typeahead/demos/focus/typeahead-focus.html
demo/tsconfig.json

Adding strict templates checks for the demo app, fixing some minor issues related to this.
This will fail unless rebased on #3623

demo: enable 'strictTemplates' flag

---

src/karma.sauce.conf.js

ci: bump SauceLabs to latest Edge and Safari

---

e2e-app/src/app/datepicker/focus/datepicker-focus.component.html
e2e-app/src/app/datepicker/focus/datepicker-focus.component.ts
e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
e2e-app/src/app/datepicker/focus/datepicker-focus.po.ts
e2e-app/src/app/tools.po.ts
src/datepicker/datepicker-month.scss

Issue #3648[](https://github.com/ng-bootstrap/ng-bootstrap/issues/3648)

fix(datepicker): disabled date picker is clickable/focusable #3648

---

src/dropdown/dropdown.ts
src/util/positioning.spec.ts
src/util/positioning.ts

This reverts commit 05efeb77
Fixes #3653

revert: fix(dropdown): ngbDropdown adds scrollbars (#3644)

---

demo/src/app/components/shared/api-docs/api-docs-class.component.html
demo/src/app/components/shared/api-docs/api-docs-config.component.html
demo/src/app/components/shared/api-docs/api-docs.component.html
demo/src/app/components/shared/examples-page/demo.component.html
demo/src/app/components/shared/overview/overview-section.component.ts
demo/src/app/shared/page-wrapper/page-header.component.ts
demo/src/app/shared/page-wrapper/page-wrapper.component.html

demo: fix routerLinks broken with #3641

---

misc/generate-stackblitzes.ts
misc/stackblitzes-templates/angular.json
misc/stackblitzes-templates/polyfills.ts
misc/stackblitzes-templates/tsconfig.json

build: run StackBlitzes with ivy by default (#3618)

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts

fix(datepicker): set min/max dates correctly with custom adapters

---

src/nav/nav-config.spec.ts
src/nav/nav-config.ts
src/nav/nav.spec.ts
src/nav/nav.ts

issue [#3327](https://github.com/ng-bootstrap/ng-bootstrap/issues/3327)

feat(nav): add keyboard interaction according to accessibility support

---

src/modal/modal-config.spec.ts
src/modal/modal-config.ts
src/modal/modal-stack.ts
src/modal/modal-window.ts
src/modal/modal.spec.ts

feat(modal): need aria-describedby on modal container (#3678)

---

demo/src/app/components/datepicker/datepicker.module.ts

demo: fix wrong stackblitz link in the datepicker example page

---

demo/src/app/app.component.html

demo: npm link markup for better screen reader experience

---

angular.json
src/environment.test.ts
src/environment.ts
src/index.ts
src/ngb-config.ts

- extracting only `NgbConfig`-related code from #2817
- adding unit tests

feat: add global 'NgbConfig'

---

src/util/transition/ngbTransition.spec.ts

test(animations): don't test opacity in IE

---

e2e-app/src/app/dropdown/focus/dropdown-focus.e2e-spec.ts
src/dropdown/dropdown.ts

fix of the issue [#3140](https://github.com/ng-bootstrap/ng-bootstrap/issues/3140)

fix(dropdown): close dropdown when focus leaves menu

---

src/progressbar/progressbar.ts

Used percent pipe by default in ngb-progressbar (#3700 )

refactor(progressbar): use PercentPipe by default (#3700)

---

package.json
yarn.lock

Updated Bootstrap CSS to v4.5.0

build: updated Bootstrap to v4.5.0

---

demo/src/app/components/modal/demos/stacked/modal-stacked.html
demo/src/app/components/modal/demos/stacked/modal-stacked.ts
src/modal/modal-stack.ts
src/modal/modal.spec.ts
src/modal/modal.ts

feat(modal): get all the open modal instances using the NgbModal (#3627)

---

demo/src/app/components/table/demos/complete/country.service.ts
demo/src/app/components/table/demos/sortable/table-sortable.ts

fix(demo): correctly sort when property is number

---

demo/src/app/default/default.component.ts

Fixed typo in default.ts installation snippet.

---

README.md

docs: typo: Out -> Our

---

demo/src/app/components/pagination/overview/pagination-overview.component.ts

The current slice example can be slightly simplified.
- [-] built and tested the changes locally.
- [-] added/updated any applicable tests.
- [-] added/updated any applicable API documentation.
- [-] added/updated any applicable demos.

docs(pagination): Simpler slice example.

---

demo/src/app/app.component.html
demo/src/app/app.module.ts
demo/src/app/app.routing.ts
demo/src/app/pages/getting-started/getting-started.component.html
demo/src/app/pages/i18n/i18n.component.html
demo/src/app/pages/i18n/i18n.component.ts
demo/src/app/shared/side-nav/side-nav.component.html
demo/src/style/app.scss

Instead of a long description, I'll put a GIF

demos: improved UX for sidebar

---

src/rating/rating.ts

Check individual commits. Those changes are just a proposal to discuss, nothing major / "must" here.

Minor rating changes

---

src/modal/modal-ref.ts

Mobal typo -> Modal
- [x ] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
- [ x] built and tested the changes locally.
- [x ] added/updated any applicable tests.
- [x ] added/updated any applicable API documentation.
- [x ] added/updated any applicable demos.

modal-ref.ts fix typo

---

demo/src/app/components/progressbar/demos/basic/progressbar-basic.ts
demo/src/app/components/progressbar/demos/height/progressbar-height.ts
demo/src/app/components/progressbar/demos/labels/progressbar-labels.ts
demo/src/app/components/progressbar/demos/showvalue/progressbar-showvalue.ts
src/progressbar/progressbar.ts

Reduced number of elements by moving "progress" class to host element. As result height can be changed via style.

feat(progressbar): simplify template

---

src/datepicker/datepicker.spec.ts

`maxDate` was limited to 31.12.2020 and failed in combination with `new Date()`...

test(datepicker): fix the test failing in 2021

---

package.json
yarn.lock

just enabling Bootstrap 5 css to start investigations on the migration

feat: enable css for bootstrap 5

---

demo/src/app/components/components.e2e-spec.ts

demo: add 'nav' page to e2e test suite

---

src/accordion/accordion.ts
src/alert/alert.ts
src/carousel/carousel.ts
src/collapse/collapse.ts
src/modal/modal-backdrop.ts
src/modal/modal-window.ts
src/nav/nav-outlet.ts
src/popover/popover.spec.ts
src/toast/toast.ts
src/tooltip/tooltip.spec.ts
src/util/popup.ts
src/util/transition/ngbTransition.spec.ts
src/util/transition/ngbTransition.ts
src/util/util.ts

fix(animations): make sure 'ngbRunTransition' runs inside the zone

---

src/carousel/carousel-transition.ts

fix(carousel): respect `[animation]="false"`

---

e2e-app/src/app/tools.pw-po.ts

Added some waitForSelector to stabilize the navigation

test: stabilize e2e navigation with Playwright

---

demo/playwright.conf.ts
demo/src/app/components/components.e2e-spec.ts
e2e-app/playwright.conf.ts
e2e-app/setup.pw-spec.ts
misc/check-format.ts
playwright/controller.ts
ssr-app/playwright.conf.ts
ssr-app/src/app/app.e2e-spec.ts

- changes are mostly to `demo` and `ssr-app`
- I haven't changed the way `page()` is handled in `e2e-app` yet

test: simplify playwright controller

---

src/alert/alert.spec.ts
src/alert/alert.ts

fix(alert): new css class for close button

---

demo/src/app/shared/component-wrapper/component-wrapper.component.html
demo/src/app/shared/page-wrapper/page-wrapper.component.html
src/carousel/carousel.spec.ts
src/carousel/carousel.ts
src/pagination/pagination.spec.ts
src/pagination/pagination.ts
src/rating/rating.spec.ts
src/rating/rating.ts
src/timepicker/timepicker.spec.ts
src/timepicker/timepicker.ts
src/util/accessibility/live.ts

fix: renamed .sr-only to .visually-hidden

---

demo/src/app/components/datepicker/demos/custommonth/datepicker-custommonth.html
demo/src/app/components/nav/demos/dynamic/nav-dynamic.html
demo/src/app/components/shared/api-docs/api-docs-class.component.html
demo/src/app/components/shared/api-docs/api-docs-config.component.html
demo/src/app/components/shared/api-docs/api-docs.component.html
demo/src/app/pages/getting-started/getting-started.component.html

fix: renamed .font-weight- utilities as .fw-

---

playwright/controller.ts

test: refactor Playwright page accessor

---

e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.html
src/karma.sauce.conf.js
src/timepicker/timepicker.spec.ts
src/util/positioning.spec.ts

The goal of this PR is to make CI green

Make BS5 CI Green

---

demo/src/app/components/toast/demos/custom-header/toast-custom-header.html
src/toast/toast.spec.ts
src/toast/toast.ts

fix(toast): new css class for btn-close

---

e2e-app/src/app/tools.pw-po.ts
e2e-app/src/app/typeahead/focus/typeahead-focus.pw-spec.ts
e2e-app/src/app/typeahead/typeahead.ts

test(typeahead): improve reliability

---

demo/src/style/app.scss
package.json
yarn.lock

Two commits:
- Upgrade to the beta 2.
- Sidebar fixes

Bootstrap beta2

---

.github/workflows/ci.yml
CONTRIBUTING.md
DEVELOPER.md
README.md
demo/playwright.conf.ts
e2e-app/playwright.conf.ts
e2e-app/protractor.conf.js
playwright/controller.ts
playwright/helpers/spec-reporter.js
scripts/sauce_connect_setup.sh
src/karma.conf.js
src/karma.sauce.conf.js
ssr-app/playwright.conf.ts

test: fixing Saucelabs tunnel identifier after switching to GitHub CI

---

e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.e2e-spec.ts
e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
e2e-app/src/app/datepicker/multiple/datepicker-multiple.e2e-spec.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
e2e-app/src/app/dropdown/click/dropdown-click.e2e-spec.ts
e2e-app/src/app/dropdown/focus/dropdown-focus.e2e-spec.ts
e2e-app/src/app/modal/autoclose/modal-autoclose.e2e-spec.ts
e2e-app/src/app/modal/focus/modal-focus.e2e-spec.ts
e2e-app/src/app/modal/focus/modal-focus.po.ts
e2e-app/src/app/modal/nesting/modal-nesting.e2e-spec.ts
e2e-app/src/app/modal/nesting/modal-nesting.po.ts
e2e-app/src/app/modal/stack-confirmation/modal-stack-confirmation.e2e-spec.ts
e2e-app/src/app/modal/stack/modal-stack.e2e-spec.ts
e2e-app/src/app/modal/stack/modal-stack.po.ts
e2e-app/src/app/popover/autoclose/popover-autoclose.e2e-spec.ts
e2e-app/src/app/tools.po.ts
e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.e2e-spec.ts
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.e2e-spec.ts
e2e-app/src/app/typeahead/focus/typeahead-focus.e2e-spec.ts

- remove `offsetClick` utility
- remove `rightClick` utility
- remove `joinSelectors` utility
- simplify `sendKey`
- remove `Key` enum
- add missing types

test: refactor tools.po.ts

---

src/carousel/carousel.spec.ts
src/carousel/carousel.ts

fix(carousel): fix value of aria-activedescendant attribute

---

demo/src/app/components/datepicker/calendars/datepicker-calendars.component.ts
demo/src/app/components/datepicker/demos/buddhist/datepicker-buddhist.html
demo/src/app/components/datepicker/demos/buddhist/datepicker-buddhist.module.ts
demo/src/app/components/datepicker/demos/buddhist/datepicker-buddhist.ts
src/datepicker/buddhist/buddhist.ts
src/datepicker/buddhist/ngb-calendar-buddhist.spec.ts
src/datepicker/buddhist/ngb-calendar-buddhist.ts
src/datepicker/datepicker.module.ts
src/index.ts

feat(datepicker): add Buddhist calendar

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts

feat(datepicker): allow setting custom popup class

---

src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

feat(dropdown): allow setting custom popup class

---

src/modal/modal-config.ts
src/modal/modal-window.spec.ts
src/modal/modal-window.ts

feat(modal): add modalDialogClass to modal-dialog div

---

demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.html
demo/src/app/components/datepicker/demos/i18n/datepicker-i18n.ts
src/datepicker/datepicker-i18n.spec.ts
src/datepicker/datepicker-i18n.ts
src/datepicker/datepicker-integration.spec.ts
src/datepicker/datepicker-month.spec.ts
src/datepicker/datepicker-month.ts

feat(datepicker): added week number header label + i18n

---

src/typeahead/highlight.spec.ts
src/typeahead/highlight.ts
src/util/util.spec.ts
src/util/util.ts

feat(typeahead): option to configure accent sensitivity in highlight

---

package.json
yarn.lock

feat(bootstrap5): enable beta3

---

demo/src/app/components/modal/demos/options/modal-options.html
demo/src/app/components/modal/demos/options/modal-options.ts
src/modal/modal-stack.ts
src/modal/modal.spec.ts

fix(modal): honor modalWindowClass option

---

src/modal/modal-stack.ts
src/modal/modal-window.ts
src/modal/modal.spec.ts

fix(modal): missing detectChanges

---

e2e-app/playwright.conf.ts
misc/playwright.js

The headless parameter didn't work (`yarn playwright --headless` to reproduce the issue).

test: fix e2e headless parameter

---

.github/workflows/ci.yml
e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts

fix: e2e failed because of changed error message

---

scripts/sauce_connect_setup.sh

build: bump sauce connect to 4.7.1

---

demo/src/app/components/nav/overview/nav-overview.component.html
demo/src/app/components/shared/api-docs/api-docs-badge.component.ts
demo/src/app/components/shared/api-docs/api-docs-class.component.html
demo/src/app/components/shared/api-docs/api-docs.component.html
demo/src/app/components/tabset/tabset-warning.component.ts
demo/src/app/pages/animations/animations.component.html
e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.component.html
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.component.html
e2e-app/src/app/modal/autoclose/modal-autoclose.component.html
e2e-app/src/app/popover/autoclose/popover-autoclose.component.html
e2e-app/src/app/tooltip/autoclose/tooltip-autoclose.component.html
e2e-app/src/app/tooltip/focus/tooltip-focus.component.html
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.component.html

demo: replacing badge-info by bg-info (and similar classes)

---

package.json
yarn.lock

build: update bootstrap to 5.1.3

---

demo/src/style/app.scss

demo: fixing -15px margins (which removes horizontal scroll bar)

---

demo/src/app/app.component.html

demo: put active class on nav-link instead of nav-item

---

demo/src/app/components/nav/demos/dynamic/nav-dynamic.html

Before this PR (with the mouse on ...):
After this PR (with the mouse on ...):

demo: fixing display of dynamic navs

---

src/modal/modal-stack.ts
src/util/scrollbar.ts

fix(modal): adds overflow: hidden from code and fixes scrollbar measurement

---

src/modal/modal-stack.ts
src/modal/modal.spec.ts

fix(modal): scrollbar issue with stacked modals

---

e2e-app/src/app/datepicker/autoclose/datepicker-autoclose.po.ts
e2e-app/src/app/datepicker/focus/datepicker-focus.e2e-spec.ts
e2e-app/src/app/datepicker/multiple/datepicker-multiple.e2e-spec.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.e2e-spec.ts
e2e-app/src/app/dropdown/autoclose/dropdown-autoclose.po.ts
e2e-app/src/app/dropdown/click/dropdown-click.e2e-spec.ts
e2e-app/src/app/dropdown/focus/dropdown-focus.e2e-spec.ts
e2e-app/src/app/modal/autoclose/modal-autoclose.e2e-spec.ts
e2e-app/src/app/modal/autoclose/modal-autoclose.po.ts
e2e-app/src/app/modal/focus/modal-focus.e2e-spec.ts
e2e-app/src/app/modal/modal.po.ts
e2e-app/src/app/modal/nesting/modal-nesting.e2e-spec.ts
e2e-app/src/app/modal/stack/modal-stack.e2e-spec.ts
e2e-app/src/app/popover/autoclose/popover-autoclose.e2e-spec.ts
e2e-app/src/app/timepicker/navigation/timepicker-navigation.e2e-spec.ts
e2e-app/src/app/tools.po.ts
e2e-app/src/app/tooltip/tooltip.po.ts
e2e-app/src/app/typeahead/autoclose/typeahead-autoclose.e2e-spec.ts
e2e-app/src/app/typeahead/focus/typeahead-focus.e2e-spec.ts

This PR contains the changes suggested by @fbasso in #4260

Refactoring e2e tests to use native @playwright/test features

---

src/accordion/accordion.module.ts
src/accordion/accordion.spec.ts
src/accordion/accordion.ts

fix(accordion): ids that begin with number were not accepted, #4195

---

src/datepicker/datepicker-input.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts
src/popover/popover.ts
src/typeahead/typeahead.ts
src/util/positioning-util.ts

fix(positionning): add offset to match Bootstrap

---

e2e-app/src/app/modal/nesting/modal-nesting.component.html
e2e-app/src/app/modal/nesting/modal-nesting.component.ts
e2e-app/src/app/modal/nesting/modal-nesting.e2e-spec.ts
e2e-app/src/app/modal/nesting/modal-nesting.po.ts
src/dropdown/dropdown.ts
src/typeahead/typeahead.ts

Follow-up for #4278 concerning typeahead and dropdown.
Also added e2e-tests for all components nested in the modal.

Fix z-index for modal nested components

---

src/rating/rating.spec.ts
src/rating/rating.ts

fixes issue described in #4132

fix(rating): changing [max] doesn't update displayed number of stars

---

src/datepicker/buddhist/ngb-calendar-buddhist.spec.ts

test(datepicker): get same date when period is not a NgbPeriod type

---

demo/src/app/components/dropdown/demos/disabled/dropdown-disabled.html
demo/src/app/components/dropdown/demos/disabled/dropdown-disabled.module.ts
demo/src/app/components/dropdown/demos/disabled/dropdown-disabled.ts
demo/src/app/components/dropdown/dropdown.module.ts

demo(dropdown): add demo with disabled items

---

demo/src/app/components/tooltip/demos/customclass/tooltip-customclass.ts

demo(tooltip): fix custom css for tooltip arrow

---

src/datepicker/datepicker-input.spec.ts
src/datepicker/datepicker-input.ts
src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts
src/popover/popover.spec.ts
src/popover/popover.ts
src/tooltip/tooltip.spec.ts
src/tooltip/tooltip.ts
src/typeahead/typeahead.ts

Popper is now created outside Angular and updates are scheduled only after popups are shown
cc @fbasso

Fix popper setup and updates

---

README.md

Fixed a few grammar errors in the README.md

---

src/offcanvas/offcanvas-panel.ts
src/offcanvas/offcanvas.spec.ts

fix(offcanvas): changed animations to be like in Bootstrap 5.2.0 JS

---

demo/src/app/components/offcanvas/demos/options/offcanvas-options.html
demo/src/app/components/offcanvas/demos/options/offcanvas-options.ts
src/offcanvas/offcanvas-backdrop.spec.ts
src/offcanvas/offcanvas-backdrop.ts
src/offcanvas/offcanvas-config.spec.ts
src/offcanvas/offcanvas-config.ts
src/offcanvas/offcanvas-stack.ts
src/offcanvas/offcanvas.spec.ts

this aligns with Bootstrap 5.2.0 functionality

feat(offcanvas): add static backdrop option

---

demo/src/app/app.module.ts
demo/src/app/pages/positioning/positioning.component.html
demo/src/app/pages/positioning/positioning.component.ts
package.json
src/datepicker/datepicker-input.ts
src/dropdown/dropdown.ts
src/karma.conf.js
src/popover/popover.ts
src/tooltip/tooltip.ts
src/typeahead/typeahead.ts
src/util/positioning.spec.ts
src/util/positioning.ts
src/util/rtl.ts
yarn.lock

The purpose is to have the right placement for widgets using popper when the dir="rtl" is set on the html tag

fix(positionning): fix start/end placements for popper

---

src/timepicker/timepicker.spec.ts
src/timepicker/timepicker.ts

Added test for this new feature and minimal documentation for the newly exposed method on export.

feat(timepicker): add exportAs property for ngbTimepicker

---

angular.json
src/progressbar/progressbar-config.spec.ts
src/progressbar/progressbar-config.ts
src/progressbar/progressbar.spec.ts
src/progressbar/progressbar.ts

fix(progressbar): adds aria-label

---

src/typeahead/highlight.ts

docs(typeahead): fix typo in highlight.ts

---

angular.json
demo/src/app/components/datepicker/demos/adapter/datepicker-adapter.html
demo/src/app/components/datepicker/demos/config/datepicker-config.html
demo/src/app/components/datepicker/demos/customday/datepicker-customday.html
demo/src/app/components/datepicker/demos/footertemplate/datepicker-footertemplate.html
demo/src/app/components/datepicker/demos/multiple/datepicker-multiple.html
demo/src/app/components/datepicker/demos/popup/datepicker-popup.html
demo/src/app/components/datepicker/demos/positiontarget/datepicker-positiontarget.html
demo/src/app/components/datepicker/demos/range-popup/datepicker-range-popup.html
demo/src/app/components/modal/demos/basic/modal-basic.html
demo/src/app/components/offcanvas/demos/basic/offcanvas-basic.html
demo/src/app/components/rating/demos/decimal/rating-decimal.html
demo/src/app/components/rating/demos/decimal/rating-decimal.ts
demo/src/app/components/rating/demos/template/rating-template.html
demo/src/app/components/rating/demos/template/rating-template.ts
demo/src/style/demos.css
misc/generate-stackblitzes.ts
misc/stackblitzes-templates/index.html.ejs
package.json
yarn.lock

demo: use `bootstrap-icons` for demos

---

demo/src/app/components/nav/demos/custom-style/nav-custom-style.ts

fix(demo): add missing module for Nav Custom style

---

commitlint.config.js
src/datepicker/datepicker-input.ts
src/dropdown/dropdown.ts
src/popover/popover.ts
src/tooltip/tooltip.ts
src/typeahead/typeahead.ts
src/util/positioning.spec.ts
src/util/positioning.ts

This should help people extending components with dependency on `NgbRTL`

Use `inject` function for private dependencies

---

src/progressbar/progressbar.spec.ts
src/progressbar/progressbar.ts

fix(progressbar): aria attributes in parent and class text-bg-color when no textType

---

demo/src/app/components/rating/demos/decimal/rating-decimal.html
demo/src/app/components/rating/demos/decimal/rating-decimal.ts
src/rating/rating.spec.ts
src/rating/rating.ts

Small PR to add the possibility to change the aria-valuetext in the rating component.

feat(rating): add customization to aria-valuetext

---

demo/src/app/components/accordion/accordion.routes.ts
demo/src/app/components/accordion/demos/directive/accordion-basic.html
demo/src/app/components/accordion/demos/directive/accordion-basic.ts
demo/src/style/app.scss
src/accordion/accordion.directive.spec.ts
src/accordion/accordion.directive.ts
src/accordion/accordion.module.ts
src/index.ts

[WIP] feat(accordion): wip accordion directive

---

src/accordion/accordion.directive.spec.ts
src/accordion/accordion.directive.ts

fix(accordion): fix onpush change detection strategy behavior

---

demo/src/app/components/modal/demos/updatable/modal-updatable-options.html
demo/src/app/components/modal/demos/updatable/modal-updatable-options.ts
demo/src/app/components/modal/modal.routes.ts
package.json
src/index.ts
src/modal/modal-config.ts
src/modal/modal-ref.ts
src/modal/modal-stack.ts
src/modal/modal.module.ts
src/modal/modal.spec.ts
yarn.lock

feat(modal): update modal options

---

src/accordion/accordion.directive.ts

Transforms `NgbAccordionBody` to a directive to avoid confusion with `[ngbAccordion]` selector.
Should not be a breakng change, The only thing changing:
`<div ngbAccordionBody #el>` → `el` will point to an element, not a component instance.
Fixes #4502

fix(accordion): use a directive for `NgbAccordionBody`

---

demo/src/style/app.scss
src/datepicker/datepicker-navigation.scss
src/datepicker/datepicker-navigation.ts

Related issue is:    #3872
[demo](https://stackblitz.com/edit/angular-bootstrap-datepicker-arrow-issue?file=src/app/datepicker-basic.html)

fix(datepicker): navigation arrow class override

---

misc/api-doc-test-cases/directives-with-inputs.ts
misc/api-doc.spec.ts
misc/api-doc.ts

docs: fix the logic to get name/alias of inputs

---

src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

fix(dropdown): set display when inside a navbar and guarded by ngIf

---

src/accordion/accordion.directive.spec.ts
src/accordion/accordion.directive.ts

feat(accordion): add 'show' and 'hide' events

---

src/accordion/accordion.directive.spec.ts
src/accordion/accordion.directive.ts

fix(accordion): fix destroyOnHide behaviour Fixes #4541

---

e2e-app/src/app/app.routes.ts
e2e-app/src/app/dropdown/shadow/dropdown-shadow.component.html
e2e-app/src/app/dropdown/shadow/dropdown-shadow.component.ts
e2e-app/src/app/dropdown/shadow/dropdown-shadow.e2e-spec.ts
src/dropdown/dropdown.ts
src/util/util.spec.ts
src/util/util.ts

fix(dropdown): fix arrow navigation inside shadow dom

---

.eslintrc.json
.prettierignore
e2e-app/src/app/app.routes.ts
e2e-app/src/app/tooltip/triggers/tooltip-triggers.component.html
e2e-app/src/app/tooltip/triggers/tooltip-triggers.component.ts
e2e-app/src/app/tooltip/triggers/tooltip-triggers.e2e-spec.ts
package.json
src/popover/popover.ts
src/tooltip/tooltip.scss
src/tooltip/tooltip.ts
src/util/triggers.spec.ts
src/util/triggers.ts
yarn.lock

Fixes #3997
Fixes #4369
Fixes #3889

Multiple tooltip positioning fixes

---

.github/workflows/saucelabs.yml

Adds a simple sauce connect action

build: sauce labs connect action

---

demo/src/app/components/accordion/demos/config/accordion-config.html

feat(accordion): migrate demo config

---

demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/components/collapse/demos/navbar/collapse-navbar.html
demo/src/app/components/dropdown/demos/navbar/dropdown-navbar.html
demo/src/app/components/modal/demos/options/modal-options.html
demo/src/app/default/default.component.html
demo/src/app/demo-theme.component.ts
demo/src/app/shared/api-docs/api-docs-class.component.html
demo/src/app/shared/api-docs/api-docs-config.component.html
demo/src/app/shared/api-docs/api-docs.component.html
demo/src/app/shared/component-wrapper/component-wrapper.component.html
demo/src/app/shared/examples-page/demo.component.html
demo/src/app/shared/overview/overview-section.component.ts
demo/src/app/shared/page-wrapper/page-header.component.ts
demo/src/app/shared/page-wrapper/page-wrapper.component.html
demo/src/public/index.html
demo/src/style/app.scss
package.json
src/datepicker/datepicker-month.scss
src/datepicker/datepicker.scss
yarn.lock

Rebase of #4451 + some other fixes
Fix #4450

Bootstrap 5.3 and dark mode

---

demo/src/app/components/components.e2e-spec.ts
demo/src/app/components/table/demos/basic/table-basic.html
demo/src/app/components/table/demos/complete/table-complete.html
demo/src/app/components/table/demos/filtering/table-filtering.html
demo/src/app/components/table/demos/pagination/table-pagination.html
demo/src/app/components/table/demos/sortable/table-sortable.html
demo/src/app/components/table/overview/demo/table-overview-demo.component.ts
package.json
src/carousel/carousel.ts
yarn.lock

feat: accessibility fixes + e2e axe

---

demo/src/app/shared/examples-page/demo.component.html
demo/src/app/shared/examples-page/demo.component.ts

Demo: fix StackBlitz URL

---

src/accordion/accordion.directive.spec.ts
src/accordion/accordion.directive.ts

fix(accordion): allow querying body template

---

src/dropdown/dropdown.spec.ts
src/dropdown/dropdown.ts

fix(dropdown): allow setting custom tabindex on items

---

demo/src/app/components/datepicker/demos/customday/datepicker-customday.ts
demo/src/app/components/datepicker/demos/custommonth/datepicker-custommonth.ts
demo/src/app/components/datepicker/demos/hebrew/datepicker-hebrew.ts
demo/src/app/components/datepicker/demos/multiple/datepicker-multiple.ts
demo/src/app/components/datepicker/demos/range-popup/datepicker-range-popup.ts
demo/src/app/components/datepicker/demos/range/datepicker-range.ts
demo/src/app/components/datepicker/overview/demo/datepicker-overview-demo.component.ts
demo/src/app/components/modal/demos/options/modal-options.ts
demo/src/app/components/nav/demos/dynamic/nav-dynamic.ts
demo/src/app/components/offcanvas/demos/component/offcanvas-component.ts
demo/src/app/components/toast/overview/toast-overview.component.ts
demo/src/app/components/tooltip/demos/container/tooltip-container.ts
demo/src/app/shared/api-docs/api-docs-class.component.ts
demo/src/app/shared/api-docs/api-docs.component.ts
ssr-app/src/app/components/rating.component.ts

demo: remove styles array

---

demo/src/app/components/datepicker/calendars/datepicker-calendars.component.ts
demo/src/app/components/datepicker/demos/ethiopian/datepicker-ethiopian.html

add the Ethiopian calendar to the calendar list in demo and add basic information about the calender to the demo calendar.

docs(datepicker): add info on ethiopian calender

---

demo/src/app/components/carousel/demos/navigation/carousel-navigation.html
demo/src/app/components/carousel/demos/pause/carousel-pause.html
demo/src/app/components/modal/demos/basic/modal-basic.html
demo/src/app/components/modal/demos/component/modal-component.ts
demo/src/app/components/modal/demos/config/modal-config.html
demo/src/app/components/modal/demos/stacked/modal-stacked.ts
demo/src/app/components/modal/demos/updatable/modal-updatable-options.ts
demo/src/app/components/modal/modal.routes.ts
demo/src/app/components/offcanvas/demos/basic/offcanvas-basic.html
demo/src/app/components/offcanvas/demos/component/offcanvas-component.ts
demo/src/app/components/offcanvas/demos/config/offcanvas-config.html
demo/src/app/components/offcanvas/demos/focus/offcanvas-focus.ts
demo/src/app/components/offcanvas/demos/options/offcanvas-options.html
e2e-app/src/app/modal/focus/modal-focus.component.html
e2e-app/src/app/offcanvas/focus/offcanvas-focus.component.html
e2e-app/src/app/tooltip/triggers/tooltip-triggers.component.html
ssr-app/src/app/components/modal.component.ts

Replace btn outline dark

---

src/typeahead/highlight.ts

fix: track by index in NgbHilight

---

demo/src/app/components/dropdown/demos/split/dropdown-split.html

docs(dropdown): fix split button radius

---

src/accordion/accordion.directive.spec.ts
src/carousel/carousel.spec.ts
src/datepicker/datepicker-navigation-select.spec.ts
src/datepicker/datepicker.spec.ts
src/datepicker/datepicker.ts
src/pagination/pagination.ts
src/test.ts
src/test/common.ts
src/typeahead/typeahead-window.ts

Some commits fix the code (and duplicate fixes done in two other concurrent PRs).
Some commits fix the tests.
The most interesting commit is the last one. Please see the commit comment for an explanation.

Avoid track-related warnings in tests

---

angular.json
demo/src/main.ts

demo: enable zoneless CD on the demo site

---

src/toast/toast-config.ts

fix(toast): added correct ariaLive values

---

demo/src/app/components/modal/demos/basic/modal-basic.html
demo/src/app/components/modal/demos/basic/modal-basic.ts
demo/src/app/components/modal/demos/stacked/modal-stacked.html
demo/src/app/components/modal/demos/stacked/modal-stacked.ts
demo/src/app/components/offcanvas/demos/basic/offcanvas-basic.html
demo/src/app/components/offcanvas/demos/basic/offcanvas-basic.ts

demo(modal & offcanvas): fix dismiss reason not updated on ESC and backdrop dismiss

---

src/accordion/accordion-config.spec.ts

🔶 Notes:
|               | Before  | After  |
|---------------|---------|--------|
| **Statements**|99.24%  | 100%   |
| **Branches**  | 100%   | 100%   |
| **Functions** | 97.61%  | 100%   |
| **Lines**     | 99.17%  | 100%   |

test(accordion): add missing tests

---

demo/src/app/components/datepicker/overview/datepicker-overview.component.ts

docs(datepicker): replace strange quote

---

src/index.ts

fix(types): export PlacementArray in main index
